### ISSUE TITLE
Save on exit and History

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#101]
Currently I have settings autosaving disabled. I noticed several strange things:

1. File Open dialog (Ctrl+O) remembers last used directory. This is expected, we have specifically implemented this remembering as part of extension of the dialog (with open by prefix) two years ago. But how is it implemented? Does it write the directory to the INI immediately, without using settings? Otherwise I can't explain why last directory is remembered for me even though settings autosaving is disabled.

2. History list is not saved on exit. I thought that the checkbox (Alt+H - _Save recent files on exit_) made it save the list immediately. It doesn't? How complex it is to make it so?

3. If I do this: start Notepad 2e, Alt+G, Ctrl+O - the dialog starts in the directory of the last file in the history (because history is not saved with autosaving disabled, this is the last file used when autosaving was enabled). Then I do Ctrl+N, Ctrl+O - and the dialog starts in the directory of the last file "globally", i.e. of the previous Notepad 2e process (no matter if autosaving is enabled or not). Shouldn't second Ctrl+O start in the directory of the same file as the first Ctrl+O?

**Comment by cshnik** [comment]
> 1. File Open dialog (Ctrl+O) remembers last used directory. This is expected, we have specifically implemented this remembering as part of extension of the dialog (with open by prefix) two years ago. But how is it implemented? Does it write the directory to the INI immediately, without using settings? Otherwise I can't explain why last directory is remembered for me even though settings autosaving is disabled.  
  
Here are some points:
a) There are **many different** cases for execution of File Open dialog which uses different values for the initial directory.
b) File Open dialog uses folder path corresponding to a currently opened file (e.g. opened with Alt+G or Ctrl+O)
c) There is an INI-settings "DefaultDirectory" which can be used in some cases.
Please specify your exact case and I'll describe the way it works.

> 2. History list is not saved on exit. I thought that the checkbox (Alt+H - Save recent files on exit) made it save the list immediately. It doesn't? How complex it is to make it so?  

No, "Save recent files on exit"-checkbox is only a visual setting control which affects the work of SaveSettings()-subroutine. Please clarify next points:
a) Do you want to make "Save recent files on exit"-setting work independently from other settings (i.e. be able to save "recent files"-list even if regular SaveSettings()-subroutine will never be called)?
b) Do you want to save [settings]/["recent files"-list only] (depends on the previous answer) when "Open Recent File"-dialog closed on OK/Cancel/X button?
c) Please describe in details how/when this functionality should be executed.

> 3. If I do this: start Notepad 2e, Alt+G, Ctrl+O - the dialog starts in the directory of the last file in the history (because history is not saved with autosaving disabled, this is the last file used when autosaving was enabled). Then I do Ctrl+N, Ctrl+O - and the dialog starts in the directory of the last file "globally", i.e. of the previous Notepad 2e process (no matter if autosaving is enabled or not). Shouldn't second Ctrl+O start in the directory of the same file as the first Ctrl+O?  

Current implementation uses different initial paths for File Open dialog depending on the internal application's state. Specified difference in behavior relates to the next case: whether Notepad2e already has an opened file or not (please see answer 1.b). Please confirm if we need to change this behavior.

**Comment by ProgerXP** [comment]
>  a) Do you want to make "Save recent files on exit"-setting work independently from other settings (i.e. be able to save "recent files"-list even if regular SaveSettings()-subroutine will never be called)?

Yes, I am asking how complex it is to detach this setting from other settings so that no matter if _Save Settings on Exit_ is enabled or not:

1. The _Save recent files on exit_ setting is saved as soon as Open Recent File (Alt+H) is closed by any means.
2. When Notepad exits, if _Save recent files on exit_ setting has been enabled - file list (history) is saved as if I have pressed F7 (_Save Settings Now_) but without saving other settings except the file list itself.

If settings autosaving is enabled then last point is a regular save of all settings, _including_ the history list. If autosaving is disabled, only history list is saved, no other settings.

**Comment by ProgerXP** [comment]
To extend the last message: right now, almost all state is discarded when Notepad2 exits if settings autosaving is disabled; I want to introduce a new value for the autosaving option that allows saving part of the state. 

In particular, if this option is set, I want these items to be saved to the INI when the program exits:
- file history
- find/replace history (Ctrl+F/H)
- last directory for file dialogs (this is probably handled by file history)

I don't want regular settings like window position, wrap, etc. saved this way. Only history records.

File history needs to be saved only when _Save recent files on exit_ is checked (note that there's also an alias under Settings menu). Find/replace history - only when _Remember search strings_ is checked.

However, the state of these checkboxes must not be saved in this mode (they are considered "regular settings").

**Comment by cshnik** [comment]
Fixed. New "Save Settings"-mode added: "Recent Files/Search Strings"
![notepad2e_savesettings](https://cloud.githubusercontent.com/assets/8019354/25104964/c2d3b952-23ec-11e7-8bfc-b78ba3da3a4a.png)

**Comment by ProgerXP** [comment]
1. Under which conditions File | Recent is grayed? 
2. File | Recall must be grayed under the same conditions.

**Comment by cshnik** [comment]
> 1. Under which conditions File | Recent is grayed?

Empty recent history causes "Recent (History)"-menu item disabled state. E.g.:
1. Uncheck "Settings> Remember Recent Files"-menu item
2. Press F7 (Save Settings Now)
This will cause saving of all current settings with empty recent files history.

> 2. File | Recall must be grayed under the same conditions.

Done.

**Comment by ProgerXP** [comment]
It works except one random bug: sometimes this setting becomes set to No even though it was set to save Recent Files/Search Strings. Usually it happens when I run Notepad 2e on the next day.

Check it please.

**Comment by cshnik** [comment]
> Check it please.

Fixed. There was a bug related to saving of the current SaveSettings-mode when switching from No to Recent Files/Search Strings.
