### ISSUE TITLE
Input locale switches on Alt

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#103]
When ru_RU (my secondary input locale) is active and I press Alt (either alone or in a combination like Alt+G, Alt+Ctrl+Enter), the locale is switched to en_US (my primary locale): Why? This doesn't occur in other applications.

**Comment by cshnik** [comment]
Cannot Reproduce.
I reviewed the sources and confirmed there are no API-calls in the Notepad2e sources which are responsible for changing of the input language.
Are you using any keyboard layout switcher applications?

**Comment by ProgerXP** [comment]
You are right, there is one program that is causing this although I don't understand why it does that for Notepad or why it does that at all. When I close it, this no more happens. Strange.

Not a bug.
