### ISSUE TITLE
Un/Grep cancelling by Escape

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#104]
I remember you have said that now Grep can be cancelled by Escape while the progressbar is visible in the statusbar. Was it implemented? Doesn't seem to work.

**Comment by cshnik** [comment]
No, progressbar was implemented as a visual indicator of the process state to drop a hint for user on how long can it take. I assume implementation of the "break-on-Escape"-feature will take up to 2-4 hours.

**Comment by ProgerXP** [comment]
No need for this now.
