### ISSUE TITLE
Open by prefix and file name with dots

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#105]
1. Create two files in the same folder, named `a.a.txt` and `aa.txt`.
2. Run Notepad 2e, Ctrl+O, navigate to that folder.
3. Type `aa` in the filename input in the open file dialog and Enter.
4. Instead of opening `aa` it opens `a.a`.

**Comment by cshnik** [comment]
Done. Additional improvements were implemented as a part of this fix:
1. Open file by relative path ("..\a.a")
2. Open file by absolute path (C:\a.a)
