### ISSUE TITLE
Autodisable controls in Ctrl+F/H 

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#108]
Not all checkboxes work in all modes. It's necessary to automatically disable (and check or uncheck) certain controls.

For example, I know that:
* When regexp mode is active, match whole word (and probably match word beginning?) are ignored. Thus they should be disabled and unchecked when user checks the regexp mode checkbox.
* Regexp mode and transform backslashes are mutually exclusive so they can't be checked both at the same time. 

Check for other combinations too, please.

**Comment by cshnik** [comment]
Fixed. There are no other intersections between the options except those specified.
