### ISSUE TITLE
Drag & drop inside the editor

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#110]
Previously you have implement the feature when dropping an object onto an empty line results in an extra line break placed after the object. This is correct. However, this should not be used when dragging lines inside the editor itself (this should only happen when user drops an external object like an URL).

Currently:

1. Drop and drop an URL onto an empty line - you will get that URL + line break (correct)
2. Create a document with 3 lines (first line = `a`, second `b`, third empty); select `[a]`, drag and drop it onto line 3. You will get `\nb\na\n` instead of `\nb\na`.

**Comment by cshnik** [comment]
Fixed.
