### ISSUE TITLE
Lua comments

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#111]
- Add line comment (identical to C's `//` but uses `--`: `...--comment...` like in SQL) - Ctrl+Q
- Add stream comment: starts with `--[[`, ends with `]]` (both tokens can be anywhere on the line, not necessary at start or end) - Ctrl+Shift+Q

**Comment by cshnik** [comment]
Current Lua syntax scheme already implements comment/comment line options:
![lua](https://cloud.githubusercontent.com/assets/8019354/26370984/9adf7726-4023-11e7-8530-ec08d3d58e74.png)

**Comment by cshnik** [comment]
Done.
