### ISSUE TITLE
Broken X-Mouse

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#113]
One of your fixes has broken X-Mouse support in Windows. Tested on XP. 

1. Given a fresh XP installation, enable X-Mouse (e.g. using TweakUI from MS - go to Mouse > X-Mouse > check `Activation follows mouse`, don't check `Autoraise`, set delay to 0).
2. Download ff8eed9a280042d837e74f93980c6d9402355f46's build exe. Run it and open another window so that both Notepad's window and another window are visible. Move the mouse from one window to another. The window under mouse will become activated. This is correct.
3. Download 7ddcda8cf59622621bbdc8c70cc549cccba5a855's exe. Do the same - this time when the mouse is moved over Notepad's window it will **not** be activated. This is incorrect.

**Comment by cshnik** [comment]
Fixed.
