### ISSUE TITLE
Grep and $

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#114]
How is `$` processed in regexp mode when doing Grep? Does it match end of file? If so then `^` must match start of file but it still matches start of line - why?

Document:
```
aa
ab
bb
```

Grep `a$` - empty document. Grep `^a` - correct (first 2 lines). Grep `a\z` - correct. 

There is some discrepancy between ^ and $.

**Comment by cshnik** [comment]
There were bugs in different places:
1.  In the Boost RegEx implementation added to Scintilla
2. In the optimized Grep implementation
The fix was tested considering the test cases from issue #102 .

**Comment by ProgerXP** [comment]
Another bug with `$`. Document:
```
1
2
1
```

1. Do Replace with from = `$`, to = `\n` in regexp mode.
2. Result = same document with a line break added after last line (wrong).
3. Do Replace with from = `1$`, to = `\n` in regexp mode.
4. Result = correct document, with line breaks added after 1st and 3rd lines.

In the original Notepad2 both work as expected.

**Comment by cshnik** [comment]
Bugfix and cleanup in BoostRegex-adapter class.
