### ISSUE TITLE
Find > Match word not unset

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#115]
The Match whole word checkbox cannot be unset.

1. Ctrl+F
2. Check Match word
3. Find Next
4. Ctrl+F
2. Uncheck Match word
3. Find Next
1. Ctrl+F
1. Match word is checked

This also causes invalid results (no matter the state of the checkbox the search happens in match word mode).

**Comment by cshnik** [comment]
Fixed.
