### ISSUE TITLE
Scintilla repaint issue when using Ctrl+Shift+Backspace/Del

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#116]
These were not present in the original Notepad2 nor in the hacc version.

1. Create a document with word wrapping disabled and the following 2 lines:
```
<long line that wraps>
foo
```
https://i.imgur.com/zEO0SK4.png
2. Place caret in the middle of the first line.
3. Press Ctrl+Shift+Backspace - this will remove half of the first line so that it now doesn't become wrapped. You will see repaint issue (https://i.imgur.com/MazrzOq.png) that will disappear once the program's window is repainted (e.g. minimized or reactivated (https://i.imgur.com/hYfXOW2.png).
4. Similarly, instead of Ctrl+Shift+Backspace above press Ctrl+Shift+Del - note the location of `foo` and line gutter numbers (https://i.imgur.com/4hEUyMs.png), correct is (https://i.imgur.com/LJI8AtV.png).

Did one of your Scintilla modifications break it?

**Comment by cshnik** [comment]
There is a bug introduced in the updated Scintilla (at least versions 3.6.5+ are affected).
I was able to reproduce the same problem within official build of SciTE.
You can download most recent version of SciTE here: https://sourceforge.net/projects/scintilla/files/SciTE/3.7.5/
Steps to reproduce:
1. Download and launch Sc375.exe
2. Click on View>Line Numbers to enable line numbers
3. Click on Options>Wrap to switch to wrap mode
4. Click on Language>Text to switch to default lexer
5. Paste text to editor:
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
foo
6. Place caret in the middle of the first line.
7. Press Ctrl+Shift+Backspace
![scite375](https://user-images.githubusercontent.com/8019354/26953879-3b79ee04-4cd7-11e7-8132-bdffc6dae903.png)

Unfortunately, at this point I have no solution to fix this bug.

**Comment by ProgerXP** [comment]
I see. Didn't think it was a bug in Scintilla itself.

Can you report this to them?

**Comment by cshnik** [comment]
> Can you report this to them?

[Done.](https://sourceforge.net/p/scintilla/bugs/1949/)

**Comment by cshnik** [comment]
The fix was merged from Scintilla's ticket solution.
