### ISSUE TITLE
Ctrl+Backspace and Cyrillics in Find/Replace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#117]
The previous developer has implemented remove word in Find/Replace dialogs. However, it doesn't work with Cyrillic characters.

1. Ctrl+F or Ctrl+H
2. Enter `привет`
3. Ctrl+Backspace
4. Text = `приве` instead of empty

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Why standard Ctrl+Z doesn't work when I use Ctrl+Backspace?

**Comment by ProgerXP** [comment]
Why standard Ctrl+Z and Ctrl+Shift+Z doesn't work after using Ctrl+Backspace?

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
No, wait. This is not right. Now Ctrl+V doesn't work as it does in any normal field.

Can you **not** change any standard text input behaviour and simply add Ctrl+Backspace support?

**Comment by cshnik** [comment]
> No, wait. This is not right. Now Ctrl+V doesn't work as it does in any normal field.  
> Can you **not** change any standard text input behaviour and simply add Ctrl+Backspace support?  

The Ctrl+V bug was introduced when implementing "remove new line characters when pasting clipboard's text"-feature back in 2016. Changes related to #117 or #121 does not affect the Ctrl+V behavior.
Fixed.

**Comment by ProgerXP** [comment]
Access violation when using Ctrl+Backspace in XP!

**Comment by cshnik** [comment]
> Access violation when using Ctrl+Backspace in XP!  

Fixed.
