### ISSUE TITLE
Alt+M improvements

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#119]
1. If selection is empty - operate on whole document (but don't select it).
2. When user clicks a link (`$(L)`, etc.) - instead of replacing entire input value, replace selection (or insert at cursor if it is empty).

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
After inserting `$(L)` or other placeholder don't select it, just place the cursor after that placeholder. E.g. it was `fo|o`, I inserted `$(L)`, it should be `foo$(L)|o`.

**Comment by cshnik** [comment]
Fixed.
