### ISSUE TITLE
Base64 de/coding

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#122]
Implement Base64 en/decoding similarly to String/Hex. Without active selection operate on whole document. 

Place the commands below `Hex to String` and assign hotkeys Alt+Shift+W (b64 -> str) and Ctrl+Alt+Shift+W (str -> b64).

**Comment by cshnik** [comment]
TODO: problem with Unicode mode.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Decoding works incorrectly with binary data. This should work like Notepad++ does.

In Notepad++, you can decode any encoded binary string and it will be identical to the original data. In your version, decoded data is truncated.

For example, try to encode Notepad2e.exe and then decode what you have got - you will get a buffer 97 bytes long. Notepad++ decodes it fine and produces identical EXE file.

**Comment by cshnik** [comment]
Fixed.
Please make sure next option is OFF when decoding/saving binary data:
File> Line Endings> Default...> Ensure consistent line endings when saving.

**Comment by ProgerXP** [comment]
Binary decoding now works perfectly.

**Comment by ProgerXP** [comment]
Base64 en/decoding must skip and consume whitespace (space 0x20 and line breaks 0x0A/0x0D). Currently presence of these breaks decoding. Take these 3 docs:

1.
```
aaa
a
```
2.
```
aaa a
```
3.
```
aaaa
````

All of them must decode to the same content but only 3rd one decodes to the proper value.

In other words, when input contains 0x20/0xA/0xD - they must be removed (but preserved outside of block selected for base64 decoding, of course).

**Comment by cshnik** [comment]
Base64 decoding algorythm changed. The same logic from #123 was implemented:
```When decoding, literal (raw) characters like spaces and line breaks (with ASCII code <= 0x20) are ignored. ```
