### ISSUE TITLE
Edit Mode bugs

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#125]
Document: 3 lines of `aaa`. Enter Edit Mode.

Bugs:
1. Press Shift+Enter or Ctrl+Enter - instead of leaving Edit Mode they replace all `aaa` with blank lines or break it in some other way.
1. Before entering Edit Mode, make some change and Undo it. In Edit Mode, Redo it - this will break the document.

**Comment by cshnik** [comment]
>1.

**Comment by cshnik** [comment]
>1. Press Shift+Enter or Ctrl+Enter - instead of leaving Edit Mode they replace all `aaa` with blank lines or break it in some other way.  
  
Fixed.  
>2. Before entering Edit Mode, make some change and Undo it. In Edit Mode, Redo it - this will break the document.  
  
Unable to reproduce. Please provide your exact scenario.

**Comment by ProgerXP** [comment]
You have broken Edit Mode (Enter) in the latest build.

**Comment by cshnik** [comment]
> You have broken Edit Mode (Enter) in the latest build.  

Fixed
