### ISSUE TITLE
Loading large file silently stops

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#126]
~~Notepad 2e is unable to load a 75 MiB file while Notepad2 loads it with no issues.~~ (Max size may be different on your machine.) 

I was wrong, this issue is also present in Notepad2 but the file has to be very large (tested with 590 MiB and 70,000,000 lines with numbers from 0 to 70M).

Why does the program just silently stops loading, not even crashes, as if it has loaded the file successfully? Instead, it should produce an error message and cancel FileOpen.

**Comment by cshnik** [comment]
Fixed.
