### ISSUE TITLE
Unindent and tabs

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#128]
1. Set indentation settings to: use spaces, indentation level = 2, tab size = 2.
2. Document = `\t\tfo|o`
3. Press Shift+Tab.
4. Document is:
```
  |foo
```

Instead of correct (cursor is mispositioned):
```
  fo|o
```

Note that Edit > Block > Unindent produces correct result but Shift+Tab - not.

**Comment by cshnik** [comment]
The similar problem was already noticed in #61.
> Shift+Tab hotkey was not properly assigned for the menu item and was actually processed by Scintilla's internals. This caused the specified problem with dual behavior of "Unindent"-functionality.

After assigning the specified unindent hotkey ~~Ctrl+Shift+Tab~~  **<Shift+Tab>** to **Edit>Block>Unindent**-menu item the change was rolled back when working on #82:
> Unindent and whitespace #82: rollback for Shift+Tab hotkey

The point is: **Shift+Tab** hotkey  (SCI_BACKTAB command) is internally processed by Scintilla's engine.
I was able to reproduce the bug with cursor position with \t chars at line start.
At this point it looks like we can report the problem to Scintilla team. What do you think?

**Comment by ProgerXP** [comment]
> The point is: Shift+Tab hotkey (SCI_BACKTAB command) is internally processed by Scintilla's engine.

As I have said in one of the issues, we need **identical** behaviour for Shift+Tab. For Tab, behaviour may be different, that is not a problem.

Why does this bug reappear every now and then? Can you either disable Scintilla processing Shift+Tab or fix Unindent so that both Shift+Tab and menu's unindent work the same way?

>  At this point it looks like we can report the problem to Scintilla team. What do you think?

How could you reproduce it? SciTE.exe doesn't have Unindent command in the menu and Shift+Tab works differently from what was implemented in #61 (i.e. it only works at line start).

**Comment by cshnik** [comment]
> Can you either disable Scintilla processing Shift+Tab or fix Unindent so that both Shift+Tab and menu's unindent work the same way?  
  
Done.

**Comment by ProgerXP** [comment]
Broken Ctrl+Tab - **again**. _Stop breaking what was fixed long time ago, please!_ We will never finish cleanup if you keep on creating more work!

**Comment by cshnik** [comment]
> Broken Ctrl+Tab - **again**  

Latest [build](https://github.com/ProgerXP/Notepad2e/commit/58b8d98b7ec5e736399d88723bf85ea4cb1e108a) works as expected: Ctrl+Tab starts "Edit Selection"-mode. Please provide your scenario.

**Comment by ProgerXP** [comment]
Sorry, I mean Shift+Tab. Unindent again does not work, it's 3rd or 4th time it breaks.

**Comment by cshnik** [comment]
> I mean Shift+Tab. Unindent again does not work  

Latest [build](https://github.com/ProgerXP/Notepad2e/commit/58b8d98b7ec5e736399d88723bf85ea4cb1e108a) works as expected: Edit>Block>Unindent / Shift+Tab hotkey causes line shift to the left.
The only condition required for unindent to work is line should start with a space(0x20) or tab character(/t). Probably there are some other whitespace chars used in your specific case. Please provide your scenario.

**Comment by ProgerXP** [comment]
> Edit>Block>Unindent / Shift+Tab hotkey causes line shift to the left.

No, Shift+Tab no more unindents if any line doesn't start with a whitespace. We had this problem already. Have you rolled back the working solution after my comment above (https://github.com/ProgerXP/Notepad2e/issues/128#issuecomment-311902725)?

We do need identical behaviour for Shift+Tab and Unindent menu command but it means Unindent should work like Shift+Tab worked before, i.e. even if some lines don't start with whitespace - it should unindent anyway.  **Or** you can leave the menu command as is and only fix Shift+Tab hotkey (as it is now for Indent command and Tab hotkey). Both variants are fine.

Look, we have 4 issues about indentation commands (#61 #82 #91), first one was created in November. Can you sit down and carefully solve this issue once and for all? Or ask me if you need more clarification about exact expected behaviour?

**Comment by cshnik** [comment]
Fixed.  
1. Edit>Block>Unindent menu command is processed within the Sci-code, the same as for Shift+Tab hotkey (SCI_BACKTAB handler).
2. Additional changes required for correct cursor transition implemented in the Sci-code. Scintilla_ChangeLog was updated.
3. The fix was tested on all recent scenarios from #61, #82, #91, #128.
