### ISSUE TITLE
Eval bugs

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#130]
Write unit tests for the eval feature because it contains at least two bugs. Focus on testing features added to TineExpr, not TinyExpr itself.

**Comment by cshnik** [comment]
Eval tests added.

**Comment by ProgerXP** [comment]
> Focus on testing features added to TineExpr, not TinyExpr itself.

I do not see any tests for added features - symbolic and named operators, base prefix/suffixes, symbols that are ignored, etc. You can refer to my description of this feature in the README.

**Comment by cshnik** [comment]
1. Fixed bug related to symbolic operators (div was broken).
2. Added new tests to cover the most of "Math Evaluation" feature functionality.

**Comment by ProgerXP** [comment]
Are there any constants? If so how are they handled? Example: `12 e` is evalutated but `12e` is not, and `+12 e` is also not evaluated. There is some issue here, `e` shouldn't be evaluated at all for consistency.

**Comment by cshnik** [comment]
1. Additional fix added for builtin functions (abs, sin, cos, ln, log...)
2. Added original test set from TinyExpr with details on no longer working tests.
3. Regarding the constants:
``pi`` is  3.14159265358979323846
``e``  is 2.71828182845904523536
Scientific number notation is also available: ``1e3`` for 1000.
``12 e`` is converted to ``12 + e`` and results with 14.718282
Neither ``12e`` or ``+12e`` are the valid expressions.

**Comment by ProgerXP** [comment]
>  12 e is converted to 12 + e and results with 14.718282

1. Why `12 pi` is not converted to, by the same logic?
2. `12e2` = 1200 but so is `12e 2`?

Shortcut expression (`1 2 3`) is only allowed with a restricted set of tokens and constants are not one of them. Please read the relevant README section. Current processing, if not bogus, is at best counterintuitive.

**Comment by cshnik** [comment]
>>  12 e is converted to 12 + e and results with 14.718282
> 1. Why `12 pi` is not converted to, by the same logic?

The issue relates to the next point: `e` is a valid hex digit while `p` and `i` are not hex digits. This was a showstopper to make it possible to treat expression as a shortcut one (i.e. spaces are not replaced with `+`).

> 2. `12e2` = 1200 but so is `12e 2`?

`12e 2` is converted to `12e+2` which means exactly the same as `12e2`.

> Shortcut expression (`1 2 3`) is only allowed with a restricted set of tokens and constants are not one of them. Please read the relevant README section. Current processing, if not bogus, is at best counterintuitive.

Please check current version: implemented logic allow using of literal constants (`e`, `pi`) as a part of shortcut expression: `12 e 2` (=14+e), `12 pi 2`(=14+pi) (corresponding tests added). If current implementation of the feature is unclear and/or weird there are 2 ways to go:
1. Remove support of scientific number notation `1e3`.
2. Restrict criteria for shortcut expression. Currently used one:
> Special case: expression with only digits, periods and any ignored symbols (above) is treated as a series of whitespace-separated numbers, which are summed up. For example: `12,3 45.6 $78` = `123+45.6+78` = 246.6.

does not distinguish the actual used number formats which enter ambiguity when using scientific number notation (`12e 2`).

>>  Next tests are no longer passed due to added enhancements: 
>Keep them but change expected result.

Done.

>>  TODO? broken methods: functions with 2 arguments separated with comma 
>Won't be implemented.

Removed.

**Comment by ProgerXP** [comment]
> The issue relates to the next point: e is a valid hex digit 

I see. Didn't think about this. Now the bug makes sense.

Current implementation is still fragile though. For example, `1e_1` (_ = space) is evaluated but `1e__1` doesn't. I don't see an easy way to work around this without full expression parsing. 

Let's roll back this fix (for constants in shortcut expressions). I will document special behaviour with non-hex `e` in the README. This way, allowed shortcut symbols are digits, periods, ignored symbols and hex digits and radix prefix/suffixes.

**Comment by cshnik** [comment]
Done.
