### ISSUE TITLE
@ breaks ungrep

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#131]
Document:
```
a
a@
aa
```

Do Ungrep on string `a@` - instead of getting:
```
a
aa
```

you get:
```
a

aa
```

How can `@` possibly impact this operation?

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
What was the cause?

**Comment by cshnik** [comment]
> What was the cause?

There was a bug in the optimized Grep/Ungrep implementation. This algorithm was totally revised and tested in details.
