### ISSUE TITLE
Open by prefix 

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#132]
In the same folder, create a file e.g. `a.txt` and (sub)folder `a`. In Open File dialog, enter `a` + Enter - the dialog will navigate to the subfolder (correct). Go back and instead of `a` type `a.` + Enter - it will again navigate to subfolder (wrong, should open `a.txt` instead).

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Not done.

**Comment by cshnik** [comment]
Here are some points:
1. There was no code in the Notepad2e which controls folder navigation in the Open-file dialog (until now).
2. The actual problem relates to the fact that folder's name "a" matches the "a."-filter passed to FindFile() API call.
3. There is no other way to implement this feature except of using the direct subclassing for the Open-file dialog.

Here is how Open-file dialog works:
1. User enter some text in the "File name"-field and press Enter
2. Open-file dialog try to find the folder matching the filter from the "File name"-field
3. If there is no matching folder found - user's hook proc will get CDN_FILEOK notification (the place in code where Notepad2e will choose the actual file to open)
4. If matching folder was found - Open-file dialog will navigate to this folder without any notification to user's hook proc

You can easily check exactly the same behavior in any other Windows application.

**Comment by ProgerXP** [comment]
> You can easily check exactly the same behavior in any other Windows application.

I see, you are correct. In this case no need to fix this rare issue. Revert your fix (it doesn't work anyway).

**Comment by cshnik** [comment]
>(it doesn't work anyway)  

The fix was tested both for Windows XP/7. Current behavior matches the expected results from the original scenario. Can you describe your test cases or do you insist on a rollback?

**Comment by ProgerXP** [comment]
>>  (it doesn't work anyway)

> The fix was tested both for Windows XP/7. 

My mistake, it works. Keep.
