### ISSUE TITLE
Replace in regexp mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#134]
Document:
```
a a
```
1. Ctrl+H, from `a` to `a(`, enable regexp mode
2. Expected result: `a(a(` or inability to submit this form (if `a(` is considered an invalid regexp due to unmatched `(`).
3. Actual result: `a a` (document unchanged).

**Comment by cshnik** [comment]
Fixed. Added regexp validation for replace-text value.
