### ISSUE TITLE
Join Lines/Paragraphs - ignore trailing break

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#135]
Currently these two commands have the following limitation:

1. Create document and select lines like this (`[ ]` indicate selection range):

```
[a
b
]c
```

Note: this happens when you drag the mouse over the left-side gutter (with line numbers) - it selects trailing line breaks, hence the need for a change.

2. Now press Ctrl+J and you will get this:

```
a b c
```

Instead, the result should be:

```
a b
c
```

In other words, the original selection must be transformed to:

```
[a
b]
c
```

------

Similarly, with Ctrl+Shift+J:

```
[a
a

b
b

]c
c
```

should normalize to:

```
[a
a

b
b]

c
c
```

and transform to:

```
a a

b b

c
c
```

Note: in both commands only the end position (trailing line breaks) are adjusted; selection start is always unchanged.

To summarize: in Ctrl+J and Ctrl+Shift+J, move the selection end leftwards until it's *not* immediately after the line break (so for both commands if selection's tail contained more than 1 line break they all will be skipped).

**Comment by cshnik** [comment]
Done.
