### ISSUE TITLE
Open Folder command

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#136]
Add a new command after File > Launch > Execute Document. Assign hotkey of Ctrl+Shift+L (if unavailable - report). The command should open the file's folder in Explorer, and the file itself should be selected (explorer.exe has command-line switches for that).

**Comment by cshnik** [comment]
Ctrl+Shift+L hotkey is already reserved for "View> Long Line Marker" menu command.
Ctrl+Alt+L was assigned to newly added "File> Launch> Open Folder" menu command.

**Comment by ProgerXP** [comment]
Correct the closing comment please:

```
    // [2e]: Open Folder command #136
    case IDM_FILE_OPENFOLDER: {
        SHELLEXECUTEINFO sei = { 0 };
        ...
    // [2e]: Open Folder command #136     <<<
```

**Comment by cshnik** [comment]
Done.
