### ISSUE TITLE
Remove "font" from new schemes

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#137]
Some of newly added syntax schemes (e.g. YAML) have custom non-monospace font face specified.

For all schemes, ensure no "font:" style is specified at all. For example, **Lisp > String EOL** is currently defined as:

```
fore:#000000,font:Verdana,back:#fefecc,eolfilled
```

It should be changed to:

```
fore:#000000,back:#fefecc,eolfilled
```

**Comment by cshnik** [comment]
Done.
