### ISSUE TITLE
Keep caret position on Edit Word

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#141]
When Edit Word command is invoked, currently caret is moved to the end of the word:

```
aa |aa  
(Ctrl+Tab or Ctrl+backtick)
aa [aa|]
```

Instead, the caret should remain where it was, i.e. `[|aa]`

1. This issue equally applies to Ctrl+Tab and Ctrl+backtick (i.e. edit word on screen and on line)
2. This issue equally applies to when there was initial selection as here:

```
aaa [|aa]a
(Ctrl+Tab or Ctrl+backtick)
aaa [aa|]a   - current (wrong)
aaa [|aa]a   - expected (correct)
```

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
My requirement was not accurate enough. The fix must be corrected as follows:

* if before entering Edit Mode selection was empty then set selection to as it was before the change (i.e. select all substring being edited, with caret at selection's end: `[aaa|]`)
* if selection was not empty then do nothing (don't change selection when Edit Mode is entered) - like now

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Now it always moves caret even on active selection. Try this:

```
aa aa [|aa]  << (aa| then shift+left then again = [|aa])
(Ctrl+Tab or Ctrl+backtick)
aa [aa|] << instead of keeping [|aa]
```

**Comment by cshnik** [comment]
Fixed.
