### ISSUE TITLE
Increasingly slow to hex/base64/qp

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#142]
1. Open a big binary file. 
2. Call one of the Special Encoding commands. 
3. Observe the progress bar: notice that it starts working quite fast (for me, first 2 dashes appear after less than 2 seconds) but then it slows down more and more until it's not moving at all - hardly reaching 40% of the overall progress.

Why so? 

I could understand if it was just slow, but it should be linearly slow. I don't see a reason for non-linear convertion progression.

Related: ~~I believe you said Escape was implemented (back when Grep/Ungrep were implemented) so the operation can be cancelled but it doesn't work. Am I wrong?~~ Found a similar issue: #104 - no need to implement it now.

Related: #102 `Grep speed`.

**Comment by cshnik** [comment]
This was a lack of progress bar update logic: percentage of completion was calculated on-fly based on current current cursor position and current document length. Encoding/decoding of the each next document's part (buffered text block) caused updating of document (and it's length) and progress bar state. Encoding caused notable increase of document length and decreases the speed for further progress bar updates (i.e. next progress update get shifted in time).
Improved progress bar update logic to display updates at regular intervals (based on expected document length instead of previously used current (recalculated) value).

**Comment by ProgerXP** [comment]
> percentage of completion was calculated on-fly based on current current cursor position and current document length. 

Why you don't use number of processed symbols rather than estimating the size of result? Even if you are updating the document along with recoding, it's enough to store total document length before starting recoding and compare current symbol's index (offset) during recoding to get an ideal estimate of work performed.

**Comment by cshnik** [comment]
Fixed. Reverted previous changes, required changes added.

**Comment by ProgerXP** [comment]
Likely not related to the problem in this issue but still: progress bar is now updated more or less linearly but once recoding finishes (in my case I'm trying to Base64-encode a 10 MiB file) Notepad 2e's window will freeze and become unresponding forever. Why? Is it because of a very long line? 

Notepad++ has no problems base64-encoding the same file and it doesn't freeze in the end.

**Comment by cshnik** [comment]
> Why? Is it because of a very long line?

This is a result of Scintilla's logic related to updating of internal data when painting very long line for the first time. Sometimes this process may take several seconds/minutes (depends on line length). 
![image](https://user-images.githubusercontent.com/8019354/34841395-b91b3a26-f73a-11e7-9fbc-f6688ae118a1.png)

**Comment by ProgerXP** [comment]
Notepad++ also uses Scintilla but its performance is significantly better and like I said it doesn't freeze at all in the end. It seems to more like a loop in Notepad2 than some Scintilla issue (my Notepad++ is from December 2015 so its Scintilla must be the same or older than the one we have upgraded to).

**Comment by ProgerXP** [comment]
There is too drastic difference between Notepad++ and ours Base64 encoding. Notepad++ has no trouble encoding a 50 megabyte file while Notepad 2e never goes through 20% or so.

**Comment by cshnik** [comment]
Multiple improvements/optimizations were implemented to increase the performance of recoding procs.
1. Most of the changes are used to temporary disable Scintilla's internal logic related to updating/redrawing when replacing substrings during the execution of recoding procedure.
2. Added new linker flag /LARGEADDRESSAWARE to increase the amount of the available memory for process (extremely useful when working with such a huge files).
