### ISSUE TITLE
Year update

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#143]
Bump year in the copyright:
```
Extended Edition (c) 2013-2018
```

Look for other occurrences in the code and elsewhere, please.

---

- [ ] https://github.com/ProgerXP/Notepad2e/blob/master/doc/Readme.txt#L11
- [ ] `src/Notepad2.rc`
- [ ] `src/version.h`

**Comment by cshnik** [comment]
Done.

**Comment by PranavMathur** [comment]
Copyright should again be updated to 2019.

**Comment by ProgerXP** [comment]
@PranavMathur Good observation.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Let's now update to 2020.

**Comment by cshnik** [comment]
Done.

**Comment by cshnik** [comment]
Done.

**Comment by Anton-V-K** [comment]
It is the time to update to 2022 already? :)

**Comment by Anton-V-K** [comment]
Draft implementation plan to support dynamic year update:
1. Exclude custom-built `_version.h` from the project (it needs to be manually removed from disk, so it isn't picked up by the build).
2. Exclude `printtime.bat` from the project - it is to be replaced with enhanced script `PreBuild.cmd`.
3. Add extra property sheet `Version.props`, which will apply following changes:
    - call `PreBuild.cmd $(OutDir)` at the pre-build step, which will generate `_version.h` in `$(OutDir)`
    - add `$(OutDir)` as extra C++ include directory
    - add `$(OutDir)` as extra RC include directory
4. in `version.h`: `#define VERSION_EXT_VERSION          L"Extended Edition © 2013-"TOSTRING(BUILD_YEAR)`
5. in `Notepad2.rc`: `LTEXT           "Extended Edition © 2013-"BUILD_YEAR_STR,IDC_EXT,42,81,174,8`
6. (optional) remove `printtime.bat`

The script `PreBuild.cmd` may be written this way:
```
@echo off
set DEST_FILE=%1_version.h
echo #ifndef _H_VERSION_> %DEST_FILE%
echo #define _H_VERSION_>>%DEST_FILE%
echo #define H_TIMESTAMP L"%DATE% %TIME%">>%DEST_FILE%
echo #define BUILD_YEAR %DATE:~-4%>>%DEST_FILE%
echo #define BUILD_YEAR_STR "%DATE:~-4%">>%DEST_FILE%
echo #endif>>%DEST_FILE%
```
The generated `_version.h` will have following content:
```
#ifndef _H_VERSION_
#define _H_VERSION_
#define H_TIMESTAMP L"21/01/2022  0:55:40.70"
#define BUILD_YEAR 2022
#define BUILD_YEAR_STR "2022"
#endif
```
The string constant `BUILD_YEAR_STR` can be dropped, and `BUILD_YEAR` can be stringified instead.
To go further it makes sense to reduce strings duplication by re-using the defined constants from `version.h` in `Notepad2.rc` with one minor trick in `version.h`:
```
#ifdef RC_INVOKED
#define STRINGIFY(x) #x
#else
#define STRINGIFY(x) L#x
#endif
#define TOSTRING(x) STRINGIFY(x)
```
After that we can re-use same constants in `Notepad2.rc` (for `IDD_ABOUT`) this way:
```
    LTEXT           VERSION_EXT_VERSION,IDC_EXT,42,81,174,8
    LTEXT           VERSION_EXT_BY,IDC_BY,42,93,174,8
```

**Comment by ProgerXP** [comment]
> #390
> The first warning related to "src_version.h" is a side-effect of build time generation step (seems to be redundant in Debug config, which isn't distributed).
> Instead of custom-built "src_version.h" the build time should be updated during the pre-build event, and this should be done only in Release config, because it always triggers the build, so you can't just hit F5 and debug (not a big issue on a modern hardware with SSD).

The warning seems to go away if you put `%(FullPath)` into Outputs.

Since version info is not important for Debug builds and putting it into PreBuildEvent for Debug will only make debug compilation slower, PreBuildEvent should exist for Release only (as you suggest). But this means there must be a stub `_version.h` with default values in case user compiles the project in Debug without first compiling it in Release. The stub may be part of this repo but it'll be overwritten on Release build and so should be somehow excluded from commits (perhaps committing it first, then adding to `.gitignore`?). What is your opinion?

> Add extra property sheet `Version.props`, which will apply following changes:

Why not just create new `<PreBuildEvent>`? Why do we need a new sheet? There is no configuration done here.

**Comment by Anton-V-K** [comment]
> The warning seems to go away if you put `%(FullPath)` into Outputs.

I guess, this trick will stop version re-generation :)

> PreBuildEvent should exist for Release only

`Notepad2e.vcxproj` has 14 configuration, 7 of them are Release ones.
I see that only build in `Release|Win32` is published, so only this configuration will generate `_version.h`, right?
If in future we'll be releasing x64 as well, overwriting single `_version.h` (in same directory) may cause subtle side effects.

> there must be a stub _version.h with default values in case user compiles the project in Debug without first compiling it in Release.

At the moment only `Dialogs.c` includes `_version.h` along with `version.h`. The latter is also included by `Notepad2.rc` and `Notepad2.ver`.
Thus we can conditionally include `_version.h` in `version.h` only for Release config, and hard-code its content for Debug config:
```
#ifdef _DEBUG
#define H_TIMESTAMP L"Debug timestamp"
#define BUILD_YEAR 2022
#else
#include "_version.h"
#endif
```

> Why not just create new `<PreBuildEvent>`? Why do we need a new sheet? 

`Version.props` is mainly needed if `_version.h` is to be generated into `$(OutDir)` - the property sheet makes it easier to patch project settings for different configurations (for instance, you can't mass-edit C++ include path, because it varies between configurations).
Moreover with `Version.props` it is easier to conditionally/locally disable the functionaly (e.g. for Debug config or if global `_version.h` exists).

**Comment by ProgerXP** [comment]
> I see that only build in `Release|Win32` is published, so only this configuration will generate `_version.h`, right?

We also publish 8 flavours (x86/x64 + ICU + LPEG) overnight if that's what you mean: https://proger.me/notepad2e/binaries/

All of them should use this header.

> Thus we can conditionally include `_version.h` in `version.h` only for Release config, and hard-code its content for Debug config:

This will duplicate the file's contents and get in the way of making changes in _version.h while debugging (e.g. About window). And it only works until it has to be included somewhere else in the future. I'd rather have "fallback" _version.h as a real file.

Here is another idea: don't include _version.h in the repo (as I have described before); add PreBuildEvent for all configurations, but in Debug ones pass a flag to .bat that will skip header generation (and thus avoid recompilation of dependent files).

```
@echo off
set DEST_FILE=%1_version.h
if "%2" == "debug" if exist "%DEST_FILE%" goto :eof
echo #ifndef _H_VERSION_> %DEST_FILE%
...
```

Apart from the fact this doesn't need any special treatment of _version.h depending on build config and doesn't duplicate its contents elsewhere, it allows adding debug or release-specific strings to the generated file.

> `Version.props` is mainly needed if `_version.h` is to be generated into `$(OutDir)` - the property sheet makes it easier to patch project settings for different configurations (for instance, you can't mass-edit C++ include path, because it varies between configurations).
> Moreover with `Version.props` it is easier to conditionally/locally disable the functionaly (e.g. for Debug config or if global `_version.h` exists).

I really think a new property sheet is an overkill in this case.

You can implement this if the task is clear. Also, about BUILD_YEAR_STR: use two #define's (string and integer), we don't need to create macros just to stringify it if it takes one extra line in the .bat to provide.

**Comment by Anton-V-K** [comment]
> add PreBuildEvent for all configurations, but in Debug ones pass a flag to .bat that will skip header generation

A configuration name can be passed as 2-nd parameter into `PreBuild.cmd`, though the check will be a bit complex in this case:
```
if not "%2"=="" (
  echo "%2" | findstr /C:"Debug" > nul & if ERRORLEVEL 1 (
    REM Not debug
  ) else (
    REM Skip regeneration for Debug configurations
    if exist %DEST_FILE% goto :eof
  )
)
```

We can also move this logic into `Version.prop` to completely suppress pre-build event (so it isn't triggered, and nothing is printed into Output window):
```
    <PreBuildEvent Condition="!$(Configuration.Contains('Debug')) Or !Exists('$(OutDir)_version.h')">
      <Command>$(SolutionDir)src\Extension\PreBuild.cmd $(OutDir) $(Configuration)</Command>
      <Message>Generating timestamp...</Message>
    </PreBuildEvent>
```
In this case passing `$(Configuration)` into `PreBuild.cmd` isn't needed, of course.

**Comment by ProgerXP** [comment]
> This setting is stored as one line in `Notepad2e.vcxproj`, so it is hard to compare changes side-by-side and easy to run into merge conflicts.

Why you may need to edit include paths? They are supposed to rarely change and be the same for all developers, no? (Excluding BOOST_ROOT and others that we have environmental variables for.)
