### ISSUE TITLE
Default setting values

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#144]
In `src/Extension/ExtSelection.c`, the default for `MaxSearchDistance` is set to 2 MiB:
```
long iMaxSearchDistance = 2048 * 1024;
```

However, if I run `Notepad2e.exe`, press F7 to produce a new clean INI file - I get 64 KiB:
```
MaxSearchDistance=64
```

From brief inspection I couldn't find where in the sources this value is set. 

-----------

Similar problem with `ShellMenuType` - I get 4 even though it's 0 in the code.

-----------

Set new defaults (defined in INI format):

```
WheelScrollInterval = 50 (ms)
MaxSearchDistance = 96 (KiB)

;Attention! 
; Keep existing defaults for settings not in the list below (e.g. 6 for Type).
SelectionColor=0x00AA00

SingleSelectionColor=0x000090

PageSelectionType=7
PageSelectionColor=0x009999
PageSelectionAlpha=50
PageSelectionLineAlpha=255
PageSelectionUnder=1

EditSelectionType=7
EditSelectionColor=0xFF0000
EditSelectionAlpha=50
EditSelectionLineAlpha=255
EditSelectionUnder=1
```

------------

It seems Reload Settings From Disk doesn't work for highlight settings? If I change e.g. SelectionUnder in the INI and Reload - old highlighting styles are used.

**Comment by cshnik** [comment]
All the cases were fixed.
