### ISSUE TITLE
Replace String backreferences

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#145]
Why when any backreference except `\0` is used in Replace String - regexp is considered invalid (buttons disabled)?

```
from: a(\d+)
to:   z\1       << invalid (?)
to:   z\0       << valid 
```

**Comment by cshnik** [comment]
Fixed: removed validation for "Replace With"-string.
Please use the following information regarding the replacement string formatting from [Scintilla's Documentation](http://www.scintilla.org/ScintillaDoc.html#SCI_REPLACETARGETRE):
``The replacement string is formed from the text string with any sequences of \1 through \9 replaced by tagged matches from the most recent regular expression search. \0 is replaced with all the matched text from the most recent search. After replacement, the target range refers to the replacement text. The return value is the length of the replacement string.``

**Comment by ProgerXP** [comment]
>  Please use the following information regarding the replacement string formatting from Scintilla's Documentation:

It doesn't explain why backreferences are considered invalid by your check. Is it because there was no "most recent search" so \1 \2 \3 etc. were never used and the library considers references to them invalid, which invalidates the whole expression?

**Comment by cshnik** [comment]
> It doesn't explain why backreferences are considered invalid by your check. Is it because there was no "most recent search" so \1 \2 \3 etc. were never used and the library considers references to them invalid, which invalidates the whole expression?

Implemented validation uses standalone regex check which means expression is tested by boost regex engine to check if specified string can be used as a correct regex string. There are no external references (e.g. to a search string) or any other extended syntax support. This means listed references \1 \2 \3 relates to the replace string itself (these are invalid due to missing ()-groups) but only \0 is a valid one for provided string: "z\0".
At this point I see no reason to validate replace string. Please confirm if this is OK.

**Comment by ProgerXP** [comment]
Validation is still useful. Let's add 9 pairs of brackets at the end of Replace string if regexp mode is enabled (only for validation of course, not when doing actual replace). This should never break regexp and will pass \0 up to \9.

**Comment by cshnik** [comment]
Done. Empty regexp groups (pairs of brackets) added at the beginning of the replace string (when verifying regexp) to make any back-reference to address actually existing group. The point is: group should be presented before its back-reference.

**Comment by ProgerXP** [comment]
```
+              // insert empty groups to make any back-references (\1..\9) valid to pass regexp check
```

Link to this issue (#145) in the comment, please.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Why `\0` is replaced with an empty string? It used to work. 

Document: `aa`
Replace from: `a` 
Replace to: `\0_`
in regexp mode

Result: empty document.
Expected: `a_a_`.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
What was the cause?

**Comment by cshnik** [comment]
>What was the cause?

Required flag was not set for boost regex in the original implementation (the same issue still(?) exists in Notepad++ where it came from).

**Comment by ProgerXP** [comment]
> Required flag was not set for boost regex in the original implementation (the same issue still(?) exists in Notepad++ where it came from).

Nice, I have checked their last version and this bug indeed exists there. Could you submit a pull request to them? In the description link to this issue and https://github.com/ProgerXP/Notepad2e please.

**Comment by cshnik** [comment]
1. Boost regex was added to Notepad++ when implementing new feature ["Add PCRE (Perl Compatible Regular Expressions) support"](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7e0ed0ebf3fe1d401cf2a44958b0b5390f4713c0#diff-dc00439e018cd32ca43681f05b5bd077).
2. [PCRE syntax description](http://docs.notepad-plus-plus.org/index.php/Regular_Expressions) from Notepad++ Wiki:
**$&, $MATCH, ${^MATCH}** The whole matched text.

Due to the previous statements **\0 backreference** is not supported by original design.

This fix extends PCRE by adding alternate supported regex format [format_sed](http://www.boost.org/doc/libs/1_63_0/libs/regex/doc/html/boost_regex/format/sed_format.html) which implements \0 backreference support. Strictly speaking this change violates the [PCRE specification](https://pcre.org/pcre.txt).

Please confirm if we need to rollback the change to return to "pure" PCRE support.

**Comment by ProgerXP** [comment]
But  `format_sed` help page isn't very informative - \escape sequences already worked before while there's nothing about `\0` support on that page. Exactly what changes does this flag enable?

I don't know why `\0` is part of sed extension because, for instance, PHP's PCRE allows `\0` natively. I would rather have *just* `\0` without `&` because I'm not used to escaping `&` (unless I'm indeed using sed).

**Comment by cshnik** [comment]
It looks like official ``format_sed`` help stated valid backreference range is wrong and was copy-pasted from the ``perl_format``-one.
> I don't know why \0 is part of sed extension because, for instance, PHP's PCRE allows \0 natively. I would rather have just \0 without & because I'm not used to escaping & (unless I'm indeed using sed).

The actual requirement of ``format_sed`` flag for ``\0`` processing was found during debugging of the boost regex implementation:
![image](https://user-images.githubusercontent.com/8019354/37484215-844bd0ce-28ba-11e8-88e1-7c4be2004ed8.png)
> Exactly what changes does this flag enable?

At this point I'm not sure where to find the correct description of this format flag.

**Comment by ProgerXP** [comment]
Boost's documentation really doesn't explain most of the features and even those it covers is inaccurate. According to the sources, format_sed is used mainly in two places:

1. xpressive/match_results.hpp
https://github.com/boostorg/xpressive/blob/develop/include/boost/xpressive/match_results.hpp#L969
2. regex/v4/regex_format.hpp
https://github.com/boostorg/regex/blob/develop/include/boost/regex/v4/regex_format.hpp

And some usage is covered in tests:
https://github.com/boostorg/regex/blob/develop/test/regress/test_replace.cpp#L59

From a quick look, I could gather that format_sed:

1. Disables Perl-style escape sequences `\` + `lLuUE` (as in `\U`) for outputting lower (only next), lower, upper (only next), upper, copying.
2. Enables `&` which is equivalent to `$0`.
3. Enables `\0`, which is also equivalent to `$0`. `\n` where n > 0 work in any mode.
4. Disables `$` which is a prefix of a large number of other constructs (some I'm not even familiar with): `$&`, $ + backtick, `$'`, `$$`, `$+`, `${`, **`$n` where n >= 0**.

Let's remove format_sed. I will update the README.

> That said, shouldn't NUL (in any form, e.g. \x00) be inserted directly into the buffer rather than clipping it? I know Notepad++ has the same flaw but it's strange that you can cut the buffer just like that while both editors support and display NUL characters in-buffer.

What about this one?

**Comment by ProgerXP** [comment]
Without format_sed, shouldn't `$n` (n > 0) be also usable in Search string? Currently it seems Search string only supports `\n` (n > 0) while Replace supports both `$n` and `\n`.

**Comment by cshnik** [comment]
> Let's remove format_sed.

Done.

> That said, shouldn't NUL (in any form, e.g. \x00) be inserted directly into the buffer rather than clipping it? I know Notepad++ has the same flaw but it's strange that you can cut the buffer just like that while both editors support and display NUL characters in-buffer.

Required changes added to allow Notepad2e to insert NULL character when using regex replace.

> Without format_sed, shouldn't $n (n > 0) be also usable in Search string? Currently it seems Search string only supports \n (n > 0) while Replace supports both $n and \n.

No, $n (n > 0) is unusable within Search string.
http://www.boost.org/doc/libs/1_63_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html
>Anchors
A '^' character shall match the start of a line.
A '$' character shall match the end of a line.

Please check Explain tab: https://regexr.com/3mini

**Comment by ProgerXP** [comment]
> No, $n (n > 0) is unusable within Search string.

Uh huh, of course not. I was temporary incapacitated by boost obscurity on this entire matter.
