### ISSUE TITLE
Save Copy doesn't work second time

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#148]
1. Open Notepad 2e
2. Enter anything, e.g. `123`
3. File > Save Copy, save somewhere
4. Enter anything, e.g. `456`
5. File > Save Copy; expected: you get a dialog; actual: command does nothing

**Comment by cshnik** [comment]
Fixed.
The actual test case is:
3. File > Save Copy, save **to the root of the disk**.
