### ISSUE TITLE
Toolbar Labels section

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#150]
Notepad2 has an INI section "Toolbar Labels". It allows adding text to toolbar buttons like this:

```
[Toolbar Labels]
01=New
```

Notepad 2e has 3 extra buttons: Open Previous/Next and Save Settings On Exit. The section works for first two (under keys 25 and 26) but Save Settings button doesn't display text if added (under key 27). This should be fixed.

**Comment by cshnik** [comment]
Fixed.
1. Source code was improved to get rid of useless counter variable.
2. Toolbar command's indices were adjusted to address legacy bug from Notepad2.
The point is: there was no actual "Copy All" toolbar command mentioned in the INI file:
``;20=Copy All``
This extra item causes incorrect labels for further toolbar commands (these were shifted by one position). Screenshot for Notepad2 using original INI file vs patched INI ("Copy All" item removed):
![image](https://user-images.githubusercontent.com/8019354/35521854-6366a7fc-054d-11e8-8bea-3a7d4d663d22.png)
