### ISSUE TITLE
Edit Word On Line mis-detection

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#152]
1. Fill a document with the following lines so that there are more lines than can be visible on 1 page:
```
aa aa
```
2. Scroll to the middle (Y) and insert the following lines:
```
zz zz
aa aa zz|
```
3. With cursor at `|`, observe that `zz` are highlighted correctly ("multiple occurrences, all visible"):
![sc](https://user-images.githubusercontent.com/1643195/36393586-1b55a394-15a8-11e8-8f14-a17b9ac9ef6c.png)
4. Press Ctrl+backtick. Expected: nothing happens and nothing changes because there are no occurrences of `zz` on that line. Actual: edit mode is **not** entered (which is correct) but highlighting breaks - it now indicates "multiple occurrences, some invisible":
![bug](https://user-images.githubusercontent.com/1643195/36393593-1fce1064-15a8-11e8-9798-293bee859146.png)

Moreover, the 3rd `z` is now highlighted as if separately from the other 2 `zz`s:
![bug2](https://user-images.githubusercontent.com/1643195/36393741-bd282ae8-15a8-11e8-95b8-7d413c0b3a84.png)

**Comment by cshnik** [comment]
Done.
