### ISSUE TITLE
Spaces in accelerated navigation mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#156]
Document:
```
aa  |  aa
aa .... aa
```

Try calling various commands involving navigation, such as: Ctrl+Left/Right, Ctrl+Backspace/Delete. Then compare the effect of the same commands but with caret positioned between dots (`..|..`).

Problem: right now spaces are somehow "special" in that navigation doesn't jump over successive spaces but stops after every space: 
```
aa |   aa
aa|    aa
|aa    aa
```

However, in Standard Navigation mode, and in Accelerated but with non-spaces behaviour is different (and correct) - such successive characters are jumped over:
```
aa|    aa
|aa    aa
```

This should be corrected. Navigation over spaces in Accelerated mode should work the same as in other cases.

Original feature request: #89.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
```
-				if ((ccCurrent == CharClassify::ccNewLine) || (ccPrev == CharClassify::ccSpace))
+				if ((ccCurrent == CharClassify::ccNewLine)
```

Why is this needed at all (checking for ccNewLine)? In normal mode, Notepad2, Notepad++ and overall conventional editors skip consecutive newlines just like they skip spaces or punctuation or alphanumeric symbols.

**Comment by cshnik** [comment]
> Why is this needed at all (checking for ccNewLine)? In normal mode, Notepad2, Notepad++ and overall conventional editors skip consecutive newlines just like they skip spaces or punctuation or alphanumeric symbols.

Standard arrow navigation algorithm is based on switching between different char class groups (ccSpace, ccNewLine, ccWord, ccPunctuation) with skipping of front(when moving forward)/trailing(when moving back) ccSpace-s, e.g.:
|abc..,,  ,,,,def	[Ctrl+->]
abc|..,,  ,,,,def	[Ctrl+->]
abc..,,  |,,,,def	[Ctrl+->]
abc..,,  ,,,,|def

Newly implemented accelerated navigation mode always set cursor:
1. On line start/end
2. At the end of spaces
|abc..,,  ,,,,def	[Ctrl+->]
abc..,,  |,,,,def	[Ctrl+->]
abc..,,  ,,,,def|

Thus, tracing of line start/end position is a part of this algorithm.

> Add [2e] comments with issue #references to Scintilla changes, too.

Done.

**Comment by ProgerXP** [comment]
> Newly implemented accelerated navigation mode always set cursor:
1. On line start/end

This is what I mean. It should skip groups of line breaks like it skips groups of other chars (like spaces) and make no exceptions to stop on every line start/end like it doesn't stop on every space.

**Comment by ProgerXP** [comment]
Why is this setting saved to INI immediately (like Save Settings On Exit and a few others)? It should be saved along with other normal settings (wrap, Tab, font, highlighting, etc.).

**Comment by cshnik** [comment]
> This is what I mean. It should skip groups of line breaks like it skips groups of other chars (like spaces) and make no exceptions to stop on every line start/end like it doesn't stop on every space. This particular behaviour is the same with non-accelerated mode.

Fixed. Empty lines are now skipped when navigating in accelerated mode.

> Why is this setting saved to INI immediately (like Save Settings On Exit and a few others)? It should be saved along with other normal settings (wrap, Tab, font, highlighting, etc.) when appropriate.

Fixed. Unwanted extra call for preserving 2e settings was removed.

**Comment by ProgerXP** [comment]
Inconsistency with whitespace navigation comparing to non-accelerated mode. Document (`.` = space):

```
..|
.

```

Ctrl+Right jumps to line 2, Ctrl+Right again to line 3. Alt+Right jumps straight to line 3.

However, if the caret is on line 3 then both Ctrl+Left and Alt+Left jump to line 2, then to line 1 as expected.

**Comment by cshnik** [comment]
Fixed.
