### ISSUE TITLE
Is there a compiled 64-bit .exe?

### ISSUE THREAD

**Issue by eggbean** [ProgerXP/Notepad2e#157]
I'm using the original version of Notepad2 64-bit version, as the x86 installer refuses to run on 64-bit Windows.  If there was a 64-bit version of Notepad2e I was hoping to just drop the .exe in as a straight replacement.

Also, does Notepad2e include the changes made to allow it to be run as a notepad.exe replacement, as explained here?  
http://www.flos-freeware.ch/doc/notepad2-Replacement.html

Thanks

---

**Update for future readers:** daily x64 builds are now provided, see the README.

**Comment by ProgerXP** [comment]
We don't have a x64 build because I simply replace notepad.exe in %windir% and system32/syswow64 and it works fine for me. But we might make one for you.

> Also, does Notepad2e include the changes made to allow it to be run as a notepad.exe replacement, as explained here?

Not sure. @cshnik, can you check if our x86 build can work under **Image File Execution Options** for Notepad.exe on Win7 x64 or Win10 x64?

**Comment by jason404** [comment]
Replacing the notepad.exe system file isn't ideal for me, as I am using the 'insider' branch builds of Win 10, so I would have to do it every two or three weeks.  As it is I apply .reg files after every update, but at least that is much quicker to do.

If you are using those patches, it would be great to have a 64-bit .exe to replace Notepad.  I've been using the original for years, but it's word highlighting in this extended version that I particularly like.

**Comment by ProgerXP** [comment]
This fork is based on 4.2.25 (the About dialog doesn't lie) but from a quick glance over the patch I don't see it in our code. It should be easy to integrate though. Will keep you updated.

I have added a bunch of GIFs to show case most notable features in this fork. You might want to check out the README.

**Comment by cshnik** [comment]
> can you check if our x86 build can work under Image File Execution Options for Notepad.exe on Win7 x64 or Win10 x64? The mentioned patches are here: http://code.kliu.org/misc/notepad2/

I have just tested specified method on Win7x64 and confirm current Notepad2e build does support it.
You are free to use next REG files for testing purposes:

``Notepad2e_enable.REG``
>Windows Registry Editor Version 5.00
>
>[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe]
"Debugger"="\"C:\\Notepad2e.exe\" /z"


``Notepad2e_disable.REG``
> Windows Registry Editor Version 5.00
>
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe]
"Debugger"=-

Please confirm if we need to implement a user-friendly menu option to automatically control this system wide setting within Notepad2e, e.g. "Register as Windows Notepad".

**Comment by ProgerXP** [comment]
@cshnik Does x86 Notepad 2e work fine under Image File Execution Options on a 64-bit OS? Which OS you have checked it on?

**Comment by cshnik** [comment]
> Does x86 Notepad 2e work fine under Image File Execution Options on a 64-bit OS?

My local tests were successful. Tested the most recent build (uploaded to this repository) of Notepad2e.exe which is x86.

>Which OS you have checked it on?

Win7x64

**Comment by ProgerXP** [comment]
@jason404 If x86 version works as it was suggested, do you really need x64? The only reason really is to be able to edit gigabyte-long text files which I don't think is feasible in any general-purpose text editor.

**Comment by jason404** [comment]
@ProgerXP No, my text files are quite a bit smaller than that.  I only wanted a to replace the .exe from the 64-bit version of Notepad2, which I only have because the 32-bit installer refuses to run on 64-bit Windows. I realise that the installer doesn't really do much for just an simple installation, so it doesn't matter.  Thanks!

**Comment by jason404** [comment]
Hello again.  The reg file above wasn't working for me, so I used this line in a batch script and ran it within the program directory, so that the parameter extension for the directory expands.

`reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%~dp0Notepad2.exe\" /z" /f`

Exporting the reg key shows this to be what is needed for a reg file for the directory location I used,

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe]
"Debugger"="\"C:\\Program Files (x86)\\Notepad2e\\Notepad2.exe\" /z"

```
Cheers

**Comment by cshnik** [comment]
> The reg file above wasn't working for me

My fault. Provided REG file contents were missing quotation for github.

**Comment by ProgerXP** [comment]
I have updated the README with the info on how to use this method. Also added some insight into Notepad2's INI search (not for the faint of heart).

**Comment by csware** [comment]
It's curious that vanilla Notepad2 has a working x64 version and Notepad2e doesn't (I found a few bugs when compiling Notepad2e for x64).

**Comment by ProgerXP** [comment]
I have [already stated my reasons](https://gitlab.com/tortoisegit/tortoisegit/issues/3206):

> What are the practical benefits of this for Notepad2? I can only think of implications like doubled in-memory and on-disk size (neither the benefits nor the implications I see are significant).
>
>A good portion of Windows system itself is still 32-bit based. Even Firefox was not so long ago 32-bit only (officially), being by all means a program that could benefit more from 64-bitness than any Notepad variant. Heck, even Visual Studio is 32-bit only.
>
>Maintaining a separate 64-bit build poses no practical value for me.

I can reconsider this if you can provide some arguments. The only one people usually use one of conceptual pureness ("run 64-bit programs on 64-bit systems") which isn't very concrete.

>  (I found a few bugs when compiling Notepad2e for x64)

If there are obvious bugs, we will fix them. I will compile it after #178 is done and see why it crashes.

**Comment by csware** [comment]
Basically maintaining an x64 build or at least make it work should not cause any extra efford - i.e., casting should always be done right.

Other arguments are here:
https://superuser.com/a/271345/353744
https://stackoverflow.com/a/2378505/3906760
https://stackoverflow.com/a/13990619/390676

**Comment by ProgerXP** [comment]
> i.e., casting should always be done right.

On this I agree, it should be fixed regardless.

We will make the program compiling for x64 and working from at least manual testing. If you strongly wish to use this version, you will be able to do so but I still see absolutely no point. Notepad2 is not a shell extension or a driver.

---

>  https://superuser.com/a/271345/353744

> Processor hardware. Instruction emulation is performed on the chip. On the x64 processor, instructions are executed natively by the micro-architecture. Therefore, execution speed under WOW64 on x64 is similar to its speed under 32-bit Windows. 

No advantage.

> API thunk overhead. This overhead is small compared to the NT kernel call itself. NT kernel functions are intended to be called infrequently.

No advantage.

> Virtual memory size. On the Intel Itanium processor, [...]. This is not the case for the x64 processor.

No advantage.

> Working set. WOW64 increases the size of the application's working set.

Slight advantage in memory - easily beaten by doubled size of data structures - pointers and integers.

> WOW64 enables 32-bit applications to take advantage of the 64-bit kernel. [...] However, 32-bit applications may not be able to create as many threads under WOW64 as they can when running natively on x86-based systems [...]

Notepad2/2e don't even have tabs... what for would we use extra handles?

---

> https://stackoverflow.com/a/2378505/3906760
> https://stackoverflow.com/a/13990619/390676

> [...] you get a bigger address space, so if mmap a file, you can address more of it at once (and load larger files into memory). 

Anyone routinely editing 3+ GB files in Notepad2? 

> [...] many of your arithmetic operations can be parallelized (for example, placing two pairs of 32-bit numbers in two registers and performing two adds in single add operation), and big number computations will run more quickly.

Sounds dubious, but even then - the closest to "heavy arithmetic operations" we have are those from tinyexpr (Math Evaluation) which is even disabled by default and not present in the original Notepad2.

**Comment by csware** [comment]
At least in the TGit case the Notepad2.exe is installed within the x64 Program Files directory which might cause issues with a x86 version.

**Comment by ProgerXP** [comment]
> At least in the TGit case the Notepad2.exe is installed within the x64 Program Files directory which might cause issues with a x86 version.

I have never seen issues with x86 files in x64 Program Files or vice versa but I get your point - one should maintain standard structure anyway, and this would require TortoiseGit to create a special folder in x86 Program Files just for Notepad2e which might not be pretty.
