### ISSUE TITLE
Join Lines with no selection

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#160]
Currently Join Lines only works when there's an active selection. 

Implement this behaviour when selection is empty:
1. Find nearest line break (NLB) to the caret's right.
2. Remove all whitespace adjacent to NLB until old NLB position is surrounded by non-whitespace symbols. Whitespace = `0x20 \t \r \n`.
3. Insert 1 space at old NLB position and set caret after it.

Example:
```
 | ab            << NLB (ab\n  cd)
  cd
  ef
```

After step 2:
```
  ab|cd
  ef
```

Final document:
```
  ab |cd
  ef
```

If caret is in between whitespace (`a | b`) then simply remove all whitespace after caret.

Also make main menu's command always enabled (regardless of selection size).

Join Paragraphs is unaffected by this feature.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
It seems you have implemented it according to the description of before I have rewritten the task. Recheck the updated version please, it is much simpler, no more requires calling original Join implementations and no more works for Join Paragraph.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Bug: if cursor is at line start (i.e. immediately after line break), processing is erroneous.

Example:
```
  ab
|  cd
  ef
```

Expected result:
```
  ab
  cd |ef
```

This is because 
>>Find nearest line break (NLB) to the caret's right.

...scans to the right of the caret, and so finds `...cd\n` but currently it doesn't scan and "finds" `ab\n`.

**Comment by cshnik** [comment]
> Bug: if cursor is at line start (i.e. immediately after line break), processing is erroneous.

This was an incorrect functional intersection with #135 feature. Fixed.
