### ISSUE TITLE
2/2e: different toolbar icons

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#161]
I have noticed that in 2e toolbar looks very different from flo's but I don't remember us doing this at all. In particular:

1. In Notepad2, disabled buttons are not grayed but made half-transparent (Cut icon for example)
2. In Notepad2, enabled icons have smooth edges while in 2e they're noticeably jagged (Undo icon for example)

Screenshot of the differences:

![n toolbar](https://user-images.githubusercontent.com/1643195/37981142-55d50122-31dc-11e8-99ce-5555c1f337d4.png)

Enlarged screenshot where jagged edges are clearly seen:

![n edges](https://user-images.githubusercontent.com/1643195/37981143-5628d3e2-31dc-11e8-8d2f-220c073ca7c6.png)

Can you tell me what has brought these two differences?

**Comment by cshnik** [comment]
The change was introduced in #43: 32bpp Toolbar.bmp image was replaced with 24bpp one.
Additional research required to find the way to preserve Toolbar.bmp in supported 32bpp mode. The point is: LoadImage(..IMAGE_BITMAP, ILC_OLOR32...) API call fail when trying to load 32bpp image created with GIMP/Paint.NET.

**Comment by ProgerXP** [comment]
Can you try Photoshop? Since Notepad2 has no such issue there must be a way to produce a compatible 32bpp BMP file. Maybe it was created with Visual Studio itself?

**Comment by ProgerXP** [comment]
> 1. In Notepad2, disabled buttons are not grayed but made half-transparent (Cut icon for example)

Is this issue also caused by 24bpp image format?

**Comment by cshnik** [comment]
>Is this issue also caused by 24bpp image format?

Yes , this issue relates to using of 24bpp image instead of 32bpp.

Fixed.
There were some problems with creation of proper 32bpp image. Neither of Visual Studio's image editor or GIMP or Paint.NET is able to create the 32bpp BMP with correct alpha channel which can be loaded with LoadImage(..IMAGE_BITMAP, ...LR_CREATEDIBSECTION) API call.
I've used GIMP to create image and Pixelformer to resave GIMP's 32bpp image to the loadable bitmap.

**Comment by ProgerXP** [comment]
Now toolbar looks as it should except that due to earlier reconvertion to 24bpp some icons have lost their edges.

Should Toolbar image have black background? Or is it my editor not supporting this format and rendering alphachannel black instead of transparency? (I tried multiple, including Firefox.)

Image with restored edges on black background: [Toolbar.zip](https://github.com/ProgerXP/Notepad2e/files/1866583/Toolbar.zip)

If background should be transparent, then please convert flo's (http://www.flos-freeware.ch/notepad2.html) Toolbar.bmp into PNG and send to me, I will add missing icons.

**Comment by cshnik** [comment]
Here is the currently used image: 
![Toolbar.png](https://user-images.githubusercontent.com/8019354/38176315-c6e1215a-3616-11e8-8beb-551f49e95f17.png)

**Comment by ProgerXP** [comment]
Give me flo's too as PNG, please.

**Comment by cshnik** [comment]
Original image from Notepad2 (converted to PNG):
![toolbar](https://user-images.githubusercontent.com/8019354/38176429-e74f20c0-3618-11e8-9098-a664c260e8af.png)
PS I've already used it's alpha channel for all original images, except the one: ab->ac. This one was changed in Notepad2e.

**Comment by ProgerXP** [comment]
>  PS I've already used it's alpha channel for all original images, except the one: ab->ac. This one was changed in Notepad2e.

Both the Replace and Stop icons are wrong. Please integrate this version: [Toolbar.zip](https://github.com/ProgerXP/Notepad2e/files/1866615/Toolbar.zip)

**Comment by cshnik** [comment]
Done. By the way, there was a requirement to change replace image in #95.

**Comment by ProgerXP** [comment]
> By the way, there was a requirement to change replace image in #95.

It was an attempt  to fix an icon that was without my consent changed in the very first commit (https://github.com/ProgerXP/Notepad2e/blob/cf2f1d99ad5895b0b50f846533aace1d3aa9270e/res/Toolbar.bmp).
