### ISSUE TITLE
Open by prefix: disable on Win10

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#165]
Windows 10 has a preference that can be enabled with this reg file:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoComplete]
"Append Completion"="yes"
```

When enabled, Explorer starts autocompleting file names in various places (Win+R, open/save dialogs, Explorer windows, etc.). For open dialog, it does exactly what our current implementation does but natively.

Extend OpenDialogByPrefix setting (currently it has simple 0/1 value):

* if it's 1 then read the above key and set OpenDialogByPrefix to 0 if it's `yes`, else set to 2
* if it's 0 then don't enable open-by-prefix feature (dialog hook)
* if it's 2 (or other) then do enable

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
The solution works. Change default value back to UPO_AUTO, please:

```
-BOOL bUsePrefixInOpenDialog = TRUE;
+EUsePrefixInOpenDialog iUsePrefixInOpenDialog = UPO_DISABLED;
+BOOL bUsePrefixInOpenDialog = FALSE;
```

**Comment by cshnik** [comment]
Fixed.

**Comment by gtumanyan** [comment]
The key works even in XP, it works on any system with internet explorer installed.

**Comment by ProgerXP** [comment]
You're right. I was sure it only worked in Vista+.

**Comment by ProgerXP** [comment]
On a Win10 system with disabled "Append Completion" (default OS setting) typing path to a directory in Open File dialog results in opening first file in that directory instead of only navigating the dialog to there. Correct behaviour is for Open By Prefix to require at least 1 file name character, else it is not triggered and default file dialog behaviour (= navigation) happens.

**Comment by ProgerXP** [comment]
Additionally, File Name (prefix) with `"` must be correctly handled. Right now if you try to open `c:\foo.txt` it will work but `"c:\foo.txt"` will not ("not file starting with [...]").

**Comment by cshnik** [comment]
> On a Win10 system with disabled "Append Completion" (default OS setting) typing path to a directory in Open File dialog results in opening first file in that directory instead of only navigating the dialog to there. Correct behaviour is for Open By Prefix to require at least 1 file name character, else it is not triggered and default file dialog behaviour (= navigation) happens.

Fixed.

> Additionally, File Name (prefix) with `"` must be correctly handled. Right now if you try to open `c:\foo.txt` it will work but `"c:\foo.txt"` will not ("not file starting with [...]").

Fixed.

**Comment by ProgerXP** [comment]
Note: wildcards still allow opening a file without typing any other symbol. This is considered a useful feature, for example: `*` will open the first file in that folder (but only if Notepad 2e's Open by prefix is used, not Windows' autocompletion).
