### ISSUE TITLE
Wrong eval normalization

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#168]
Line:
```
12345$ / 1,01
```

According to the rules, it must be equal to
```
12345$ / 1.01
(or) 12345 / 1.01
```

But it isn't. However, it's correctly evaluated when $ is removed. What is causing this?

**Comment by cshnik** [comment]
There was a bug: filtering of ``$`` was not applied when converting ``,`` to ``.`` (which caused expression ``12345$ / 1.01`` evaluation to fail and skip this algorithm's branch).
Fixed. Improved eval normalization logic, added corresponding test case.
