### ISSUE TITLE
Binary Save Options button

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#170]
Add a new toolbar button (no menu command, no hotkey) titled "Binary Save Options" (not on the toolbar by default). Icon: ![bin](https://user-images.githubusercontent.com/1643195/39965096-70095e42-5682-11e8-8052-6989b54a5a9c.png)

The button is in pressed state when both of these checkboxes are *not* checked:

* File > Line Endings > Default - Ensure consistent ...
* File > Line Endings > Default - Strip trailing ...

When any of them is checked then this button is in unpressed state. The purpose of the button is to indicate when binary data (e.g. base64-decoded) will be saved in verbatim form (see https://github.com/ProgerXP/Notepad2e/issues/122#issuecomment-351432074).

Clicking on a *pressed* button checks both those checkboxes. Clicking on an *unpressed* button unchecks them.

**Comment by cshnik** [comment]
Done.

**Comment by cshnik** [comment]
Done.
