### ISSUE TITLE
Regexp Previous Find missing matches 

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#174]
Document:

```
1234
1234|
```

With caret after last `4`, Find, regexp, String `[23]`, Previous selects 

```
1234
1[2]34
```

Shift+F3:

```
1[2]34
1234
```

However, if you do the same but with caret before first `1`, Next selects:

```
1[2]34
1234
```

```
12[3]4
1234
```

```
1234
1[2]34
```

Forward search works correct: it finds all matches after the cursor.

Why backward search (and only in regexp mode) skips all but first match in each line?

**Comment by cshnik** [comment]
> Why backward search (and only in regexp mode) skips all but first match in each line?

The point is: regex search is always applied for every selected/all lines in line-by-line way respecting the find direction option ("next": from first to last, "previous": from last to first). There is no actual reverse search for regex since this feature is hard to implement for unicode encoded files (UTF8).
BTW Backward find direction is disabled in Notepad++ when using regex mode.

**Comment by ProgerXP** [comment]
I see. In Notepad2 (which uses another regexp engine) both directions work correctly. So it's a limitation of Boost regex which we cannot fix?

**Comment by cshnik** [comment]
> So it's a limitation of Boost regex which we cannot avoid?

Yes, since there is no flag to call right-to-left search the only way to implement such a feature is incremental testing of end-of-line/middle-of-line block (increment block length to the left on every step). This is extremely bad and ineffective for big files.

**Comment by ProgerXP** [comment]
> Yes, since there is no flag to call right-to-left search the only way to implement such a feature is incremental testing of end-of-line/middle-of-line block (increment block length to the left on every step). 

I think you mean something else. It's not optimal but not extremely bad: if I understand correctly, Boost regexp always selects first match in a line. Our problem here is that we don't know if it's the only match there or there are others on the right. Therefore we can search all matches (with regular forward search) after selected match, and repeat this until we hit end of line - now we have all matches in that line, and we can go from last match step by step to first match, and after that repeat the search on the previous line.

This approach would depend not on the size of the whole file but on the average number of matches on every line and on average line length.

**Comment by cshnik** [comment]
Fixed.
