### ISSUE TITLE
"Highlight current word" setting is not persisted

### ISSUE THREAD

**Issue by ben-spiller** [ProgerXP/Notepad2e#175]
In LoadSettings, HightLightSelection is read from cchHlIniSection i.e. [Extended], however in SaveSettings it is written in pIniSection i.e. [Settings] - therefore the setting can't be changed (except by manually editing the .ini file)

**Comment by ProgerXP** [comment]
Are you sure you are using last version? https://github.com/ProgerXP/Notepad2e/tree/master/bin

We got rid of HightLightSelection and [Extended] section months ago.
