### ISSUE TITLE
Disable save prompt for some Launch commands

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#176]
Currently all commands under File > Launch submenu trigger the "save changes?" prompt. However, it should not appear for these two:

1. Empty Window
2. Open Folder

**Comment by cshnik** [comment]
Save prompt was caused by "Save on deactivate" feature #164 (e.g. for read-only files). Fixed.

**Comment by ProgerXP** [comment]
No, it can't be caused by that feature because I have it disabled. And even if I enable it for a writeable file, it will just cause its saving (which is correct, no need to skip it). The problem is something else.

Enable Settings > Save Before Running Tools, open any existing file and invoke one of Launch commands. The prompt will appear. I believe your current fix should be reverted.

**Comment by cshnik** [comment]
Fixed. FileSave()-calls (which caused prompt popup) removed for specified menu commands.
