### ISSUE TITLE
Single File Instance sometimes allowing duplicated windows

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#177]
With Single File Instance enabled, open some text file and then repeatedly quickly click on the same file in Explorer - on about every 3rd double click it will open new window despite there being one already opened for that file.

This is an issue at least on Windows 10.

**Comment by cshnik** [comment]
There was a hard coded value:
> //==== Reuse Window Lock Timeout ==============================================
#define REUSEWINDOWLOCKTIMEOUT 1000

mentioned in the [Notepad2 ChangeLog](http://flos-freeware.ch/doc/Notepad2.txt) as:
> "Reuse Window" option timeout improves opening multiple files

which prevents reusing of the Notepad2 window before timeout expiration (specified value in ms).

Fix: decreased value from 1000 to 250.
