### ISSUE TITLE
Edit highlighted word

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#18]
Please estimate how complex this is.

Currently we highlight current word. I want a menu item/hotkey to automatically edit all highlighted words *on the current screen* (not under scrollbars). Example:
* I place cursor on `myVar`. Other occurrences are highlighted.
* I hit *F2*. Highlight mode changes (e.g. it turns to filled rectangle) for occurrences on current screen.
* Whatever characters I replace, add or delete this immediately reflects on all highlighted words on current screen.
* This mode is quit once I do anything but type with keyboard - e.g. leave window, click with mouse, etc. In other words I can type symbols from keyboard and navigate with arrow keys but every other action leaves this mode.

**Comment by ProgerXP** [comment]
**Bug:**
```
|aa aa
```

* Ctrl+Tab
* Select first `a` with Shift and arrows. This means to get: `[a]a aa` (`[ ]` - selection start/end)
* Enter `A` (i.e. replace first lower-case letter with a capital)
* Only the current word is updated, the other one remains at `aa` (must be `Aa`)

**Comment by hacc** [comment]
i`m confused

> Keep in mind that when there is a selected text match must be case-sensitive - this is correct right 
> now, just don't break it fixing the above bug.

i've fixed ... but it needs testing

**Comment by ProgerXP** [comment]
> Keep in mind that when there is a selected text match must be case-sensitive - this is correct right
now, just don't break it fixing the above bug.

This means that the match is case-sensitive when you have selection **before** you press Ctrl+Tab. In my case I have no selection so the match must have been case-insensitive (and it was, correctly). The problem was that after you're in "Edit word" mode the program didn't make changes if you replace one of the letters with the same but in different case (without deleting the old letter or adding new letter - i.e. replacing it by selecting when inside edit word mode).

It seems fixed now, I'll keep testing.
