### ISSUE TITLE
TinyExpr throws assertions when inserting UTF-8 chars

### ISSUE THREAD

**Issue by csware** [ProgerXP/Notepad2e#182]
Run Notepad2e in debug mode and insert UTF-8 chars such as "абцдеф".

You will get assertions (at least with MSVCR 141). This indicates a problem.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
@csware Do you still get assertion errors?

**Comment by csware** [comment]
When "evaluate line" is selected, then no evaluation takes place if you enter e.g. "ä (100+2)".

**Comment by ProgerXP** [comment]
Evaluate Line only enables evaluation if current selection or, if it's empty, current line is a valid expression. In other cases it uses default behaviour, i.e. displays buffer size in the statusbar.

`ä` is not a valid symbol in expressions. 

Please see these README sections: 

- https://github.com/ProgerXP/Notepad2e/#matheval
- https://github.com/ProgerXP/Notepad2e/#new-math-evaluation

**Comment by ProgerXP** [comment]
I am closing this issue since the assertion error has been fixed.

**Comment by csware** [comment]
Ah I see, thanks!
