### ISSUE TITLE
Url encode issue

### ISSUE THREAD

**Issue by tumagonx** [ProgerXP/Notepad2e#189]
I have observed this behavior quite a while, that notepad2 didn't encode `:` or `=`
for example:
`http://site.com/?foo=bar`
become
`http:%2F%2Fsite.com%2F%3Ffoo=bar`
should be
`http%3A%2F%2Fsite.com%2F%3Ffoo%3Dbar`

**Comment by ProgerXP** [comment]
And `%` are also not converted (double convertion). Notepad2 passes URL_ESCAPE_SEGMENT_ONLY flag which acts accordingly to [UrlEscape docs](https://docs.microsoft.com/en-us/windows/desktop/api/shlwapi/nf-shlwapi-urlescapea). We may make it a setting so that all symbols from all URL parts are converted without exceptions.

**Comment by tumagonx** [comment]
Yes, that should do it. are you build the executable regularly? thanks

**Comment by tumagonx** [comment]
Or may be conditionally enable URL_ESCAPE_AS_UTF8 after os version check? unfortunately I use XP :(

**Comment by ProgerXP** [comment]
> unfortunately I use XP :(

Notepad 2e will support XP as long as Visual Studio does. Given VS2017 still does, this will last for many more years.

Will address this issue after more important ones.

**Comment by tumagonx** [comment]
Ok thanks, here is example of RFC3986 https://github.com/dnmfarrell/URI-Encode-C/, just in case we can't use UrlEscape

**Comment by ProgerXP** [comment]
@cshnik 
Add a new ini setting `UrlEscapeFlags` defaulting to escape-everything. The docs are quite convoluted and it's not clear to me what exact flags should be used but it seems URL_ESCAPE_PERCENT | URL_ESCAPE_AS_UTF8  are good, maybe also URL_ESCAPE_ASCII_URI_COMPONENT.

The goal is to percent-escape every unsafe symbol like urlencode() in PHP and encodeURIComponent() in JS.

**Comment by tumagonx** [comment]
I still reproduce the issue with today binary, how to set the `UrlEscapeFlags` in notepad2e.ini ? especially with WinXP

**Comment by ProgerXP** [comment]
@tumagonx We're just starting to work on this issue.

**Comment by cshnik** [comment]
> Add a new ini setting `UrlEscapeFlags` defaulting to escape-everything. The docs are quite convoluted and it's not clear to me what exact flags should be used but it seems URL_ESCAPE_PERCENT | URL_ESCAPE_AS_UTF8  are good, maybe also URL_ESCAPE_ASCII_URI_COMPONENT.

[UrlEscape](https://docs.microsoft.com/en-us/windows/desktop/api/shlwapi/nf-shlwapi-urlescapea) has no option to encode complete url including prefix `http://server/`:

> Examples
The following examples show the effect of the various flags on a URL. The example URL is not valid but is exaggerated for demonstration purposes.
C++
// The full original URL
http://microsoft.com/test/t%e<s t.asp?url=/{ex% ample</abc.asp?frame=true#fr%agment    
> 
>// URL_ESCAPE_SPACES_ONLY 
// Only space characters are escaped. Other unsafe characters are ignored.
// Note: This flag expects the server portion of the URL to be omitted.
Original = test/t%e<s t.asp?url=/{ex% ample</abc.asp?frame=true#fr%agment
Result   = test/t%e<s%20t.asp?url=/{ex%%20ample</abc.asp?frame=true#fr%agment
>
>// URL_ESCAPE_SPACES_ONLY | URL_DONT_ESCAPE_EXTRA_INFO
// Spaces in the segment are converted into their escape sequences, but
// spaces in the query are not.
Original = test/t%e<s t.asp?url=/{ex% ample</abc.asp?frame=true#fr%agment
Result   = test/t%e<s%20t.asp?url=/{ex% ample</abc.asp?frame=true#fr%agment
>
>// URL_ESCAPE_PERCENT
// Here only the segment and query are supplied and the server component is
// omitted, although that is not required. Only the segment is considered.
// All unsafe characters plus the % character are converted in the segment.
Original = test/t%e<s t.asp?url=/{ex% ample</abc.asp?frame=true#fr%agment
Result   = test/t%25e%3Cs%20t.asp?url=/{ex% ample</abc.asp?frame=true#fr%agment
>
>// URL_ESCAPE_SEGMENT_ONLY
// Note: This flag expects only the segment, omitting the server and query 
//       components.
// The / character is escaped as well as the usual unsafe characters.
Original = test/t%e<s t.asp
Result   = test%2Ft%e%3Cs%20t.asp

Neither [InternetCanonicalizeUrl](https://docs.microsoft.com/en-us/windows/desktop/api/Wininet/nf-wininet-internetcanonicalizeurla) can perform required conversion.

Please confirm we should proceed with custom implementation for url encode (implementation + tests) and clarify how specified ini setting `UrlEscapeFlags` should affect this algorythm.

**Comment by ProgerXP** [comment]
@cshnik 
What about UrlCanonicalize? https://docs.microsoft.com/en-us/windows/desktop/api/shlwapi/nf-shlwapi-urlcanonicalizea

The description suggests it does what we want, with URL_PLUGGABLE_PROTOCOL | (URL_DONT_SIMPLIFY) | URL_ESCAPE_PERCENT | URL_ESCAPE_AS_UTF8

**Comment by cshnik** [comment]
> What about UrlCanonicalize?

UrlCanonicalizeA has no options to force using of percent encoding for specific ASCII characters (e.g. :/) as required for UrlEncode functionality. Please check this thread for details: [Win32 API for URL Encoding](https://social.msdn.microsoft.com/forums/vstudio/en-US/454a7884-80e1-41c5-8df7-a35c879bf535/win32-api-for-url-encoding)

**Comment by ProgerXP** [comment]
I see. So there's no API function that really does the job.

Can we use some existing library? Somebody must have coded it already. Perhaps the one @tumagonx has suggested?

**Comment by cshnik** [comment]
> Can we use some existing library? Somebody must have coded it already. Perhaps the one @tumagonx has suggested?

To my mind, this algorithm is pretty simple and we should implement it in the same way we previously did with string-to-hex/base64/QP, i.e.: implement encoding/decoding and cover it with tests. This way looks straight and simple. Please confirm if it sounds reasonable.

**Comment by ProgerXP** [comment]
If you think it's better to write it from scratch then you can do it. The algorithm isn't too complex indeed.

**Comment by cshnik** [comment]
Added implementation for URL encode/decode with corresponding tests.
New INI option ``UrlEncodeMode`` (instead of proposed ``UrlEscapeFlags``) added to switch behavior:
1. Legacy mode is 0 (by default)
2. Improved mode is <>0

**Comment by ProgerXP** [comment]
@cshnik 

> Improved mode is <>0

The idea behind `UrlEscapeFlags` was to allow customization of UrlEscape's flags in case "legacy" behaviour is used. For example, to remove URL_ESCAPE_SEGMENT_ONLY or add some other flag. This is impossible with plain binary value.

>
```
  i = (int)SendMessage(hwndEdit, SCI_GETSELECTIONEND, 0, 0) - (int)SendMessage(hwndEdit, SCI_GETSELECTIONSTART, 0, 0);
  i3 = (int)SendMessage(hwndEdit, SCI_GETLENGTH, 0, 0);
  ...
  EnableCmd(hmenu, IDM_EDIT_URLENCODE, (iUrlEncodeMode == UEM_LEGACY) ? i : i3);
  EnableCmd(hmenu, IDM_EDIT_URLDECODE, (iUrlEncodeMode == UEM_LEGACY) ? i : i3);
```

I believe we should update the "legacy" encoding so that it also uses either selection or the entire buffer, for uniformity with other encoding commands.

**Comment by cshnik** [comment]
> The idea behind ``UrlEscapeFlags`` was to allow customization of UrlEscape's flags in case "legacy" behaviour is used. For example, to remove URL_ESCAPE_SEGMENT_ONLY or add some other flag. This is impossible with plain binary value.

It looks like proposal for UrlEscapeFlags INI option was created to adjust ``UrlEscape()`` argument to make function work as requested in the initial comment. But finally we found that ``UrlEscape()`` is unable to get proper result: complete URL string get never encoded.
At this point we have implemented custom UrlEncode() algorithm which works as expected.

Please confirm if we still need to implement ``UrlEscapeFlags`` INI option to customize ``UrlEscape()`` argument (it will work only when ``UrlEncodeMode`` is missing or set to 0).

**Comment by ProgerXP** [comment]
> Please confirm if we still need to implement UrlEscapeFlags INI option to customize UrlEscape() argument (it will work only when UrlEncodeMode is missing or set to 0).

Alright, I've checked the available flags again and it seems allowing their customization is not worth the potential usefulness.

Let's keep your `UrlEncodeMode`. But let's change the default so that new behaviour is used since UrlEscape is really weird and most people would consider this to be a bug in Notepad 2e.

> Where INTERNET_MAX_URL_LENGTH equals to 2083.

I see. Leave it be then.

**Comment by ProgerXP** [comment]
@tumagonx 
You should be able to make use of the proper encoding with the latest build (see the README for download links).

**Comment by cshnik** [comment]
> Let's keep your UrlEncodeMode. But let's change the default so that new behaviour is used since UrlEscape is really weird and most people would consider this to be a bug in Notepad 2e.

Fixed.

**Comment by ProgerXP** [comment]
@cshnik 
```
Assert failed. Decoding, Unicode encoding,  source: TestFile1__src_UTF8.txt
test\extension\textencodingtests.cpp, DoRecodingTest	line 70
	at DoRecodingTest() in test\extension\textencodingtests.cpp:line 73
	at Notepad2eTests::CStringToHex::TestHex_FileSamples() in test\extension\textencodingtests.cpp:line 116
```
