### ISSUE TITLE
Open dialog - open by name prefix

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#19]
То есть у меня есть файлы abc.txt, aaa.txt, foo.txt; в диалоге открытия я пишу "ab" и открывается файл abc.txt, если пишу "a" - открывается aaa.txt. То есть обычный алгоритм открытия, который в случае неизвестного файла не выдаёт ошибку сразу, а находит все файлы в папке, начинающиеся на введённую строку, и открывает первый из них. Если ни одного файла нет - выводит ошибку.

**Comment by ProgerXP** [comment]
I am back. I have briefly checked and it seems there are no issues. 

Just to be clear - have you reverted old code or fixed it?

**Comment by hacc** [comment]
It’s not so easy clearly revert code ( by git) and i don’t sure it’s right action. I just found more proper solution.

**Comment by ProgerXP** [comment]
I will keep testing it for a while.

**Comment by ProgerXP** [comment]
**Bug:** match has become case-sensitive so e.g. I have a file `Foo` but opening by prefix `f` or `fO` fails with non-existing file. `Fo` works.

**Comment by hacc** [comment]
fixed

**Comment by ProgerXP** [comment]
**Bug:**
* Ctrl+O
* Type `qw`
* Enter
* Get "file not found" (correct)
* Erase and type `q`
* Get "file not found" with the old name (`qw`)

This appears regardless of whether any file starting with `q` exists in the directory or not.

**Comment by ProgerXP** [comment]
Fixed by @cshnik.
