### ISSUE TITLE
Slow open/save file dialogs

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#191]
Suddenly Notepad 2e's file dialogs started to be extremely slow. It looks like some kind of timeout (I use network drives a lot) - bring up such a dialog, the program hangs for ~2 minutes, then proceeds normally. Reboots don't help.

I've checked and the original Notepad2 doesn't suffer from this issue.

Is there any way to debug it? What has changed compared to Notepad2 that might have caused such behaviour? Hooks? But hooks only affect typed names as far as I remember, not how the dialog opens.

**Comment by cshnik** [comment]
Here are some points:
1. "Save file" dialog never used specified hooks.
2. Please provide next details on the issue:
- Are open/save file dialogs hang only on their very first popup?
- Is there any difference which of the dialog is opened first?
- Do they hang for the same period of time?
3. I assume the problem can be in the added n2e_GetLastDir() which may return incorrectly formatted path. Please do the following test and confirm if it helped:
```temporary cleanup [Recent Files] section in the Notepad2e.ini and restart application.```

**Comment by ProgerXP** [comment]
The problem was gone and I couldn't test it further. I'm keeping this issue open just in case it reappears.
