### ISSUE TITLE
Build info

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#195]
1. We're starting over the version counter. Change file version from 4.2.25.0 to 1.0.
2. Provide some means to supply the build number (2nd digit in the version) and commit hash (7 chars) similarly to printtime.bat which provides the compilation date/time. So we will have v1.0, 1.1, 1.2, 1.3, etc. (1 2 3 - build numbers). H_TIMESTAMP remains as is.
  - it can be by adding new lines with `#define` to printtime.bat and/or it can be via find & replace in some file(s) e.g. in Notepad2.rc
3. File description and internal name (in file info) should say `Notepad 2e` or `Notepad 2e-ICU` (#162).
4. Original file name (in file info) should say `Notepad2e.exe` or `Notepad2ei.exe` (`i` for ICU).
5. File comments (new property in file info) should display commit hash.
6. Copyright should say `© Florian Balmer and contributors`.
7. In the About box, change the first line to `Notepad 2e[-ICU] (R#, %)` where `#` = build number, `%` - commit hash. Example: `Notepad 2e-ICU (R123, abcdef1)`.

**Comment by cshnik** [comment]
Done.
Build number and commit hash are hardcoded values in version.h and should be manually adjusted.

**Comment by ProgerXP** [comment]
It's done but let's just remove the "1." part from `R1.xx` in About. I'm not planning on ever having Notepad 2e v2.

> `Notepad 2e[-ICU] (R#, %)` where `#` = build number, `%` - commit hash. Example: `Notepad 2e-ICU (R123, abcdef1)`.
