### ISSUE TITLE
Change main menu accelerators

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#197]
Remove accelerators from menu items (of the top submenu only) which have another hotkey. This is needed because there are many menu items and we waste available letters on commands that can be called with a global hotkey.

This means removing accelerators from:

- File > New, Open, Revert, 3 Save [...], Rename, Print, Recent
  - keep `E&xit` for traditional compatibility
  - also change: `Save On &Lose Focus`
  - submenus (Launch, etc.) here and in other menus are untouched
- Edit - all except Clear Clipboard and 5 commands with submenus
- View - untouched, it's rarely used, small enough and has no accelerator conflicts 
- Settings - Tab Settings, Auto Close, Always On Top, Transparent Mode, File Change, 3 last settings-related commands
  - change: `Evaluate &Math Expressions`, `C&trl+Wheel`, `S&how Toolbar`
- `?` - untouched

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
What about File > Revert?

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
My bad, I have missed several more clashes:

- Rename Save On Lose Focus to `... Fo&cus` 
- Rename Edit > `&Lines` 
- Remove `&` entirely from 6 items in: Edit > Special > `String To Hex` ... untill and including `QP Decode`
- Add to and rename `? > &3rd-Party Code`

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
- Remove `&` from two Edit > Encode > URL ...
- Rename `? > &3rd-Party Code` (3rd plus dash: "third-party")

**Comment by cshnik** [comment]
Fixed.
