### ISSUE TITLE
Printing by default results in tiny characters

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#199]
On Win10 with Default Font's Size of 10 printing using built-in "Microsoft Print to PDF" results in pages with minuscule unreadable font. At the same time, if Default Font's Size is set to about 72 points - results are adequate (however, page header and footer are still printed in tiny font).

Do you have any idea why this can be happening and how to address it?

**Comment by cshnik** [comment]
Fixed. The bug was introduced during implementation #154 .
Regarding the header/footer: they have hardcoded font size 8pt/7pt.

**Comment by ProgerXP** [comment]
>  Regarding the header/footer: they have hardcoded font size 8pt/7pt.

Not even customizable via scheme parameters? That's bad, change them to be 10pt both please.

**Comment by cshnik** [comment]
> Not even customizable via scheme parameters?

No, there is no customization mechanism implemented for them.

>That's bad, change them to be 10pt both please.

Done.
