### ISSUE TITLE
Split Edit > Special

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#201]
Split the Edit > Special submenu into 2 menu submenus, leaving Edit > Special with only Line Comment, Stream Comment, Escape/Unescape C Chars, Strip/Escape HTML, Char To Hex, Hex to Char, Find Matching Brace and 3 last commands.

The new submenu is below Special, called `&Encode`, with URL Encode/Decode, String <=> Hex, Base64 and QP. Each pair of commands is separated with `---`.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Let's also add `---` between Unescape C Chars and Strip HTML Tags.

**Comment by cshnik** [comment]
Done.
