### ISSUE TITLE
Gutter not updated on Replace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#206]
Create a document of 1000 letter `a`. Do Replace `a` with `\n`. Result is a document with 1000 lines. However, the gutter's width wasn't updated and lines >99 are cropped.

Previously we have added automatic gutter update on some commands (Paste and some others). I can't find that issue though.

**Comment by cshnik** [comment]
Fixed all 3 replace subroutines:
![image](https://user-images.githubusercontent.com/8019354/50425490-01d96e00-08aa-11e9-845b-8f4269dbecae.png)
