### ISSUE TITLE
Wheel-scrolling in the opposite direction skips first turn

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#208]
I have a hunch this is related to the Ctrl+Wheel scroll from 2013 (#11).

In Notepad2, when you scroll up (WheelUp) then immediately down (WheelDown) - both scrolls are handled.

In Notepad 2e, first scroll in the opposite direction is skipped (i.e. WheelDown from the above example is ignored). This behaviour is strange and should be removed.

Update: this doesn't occur always or in every window but once it happens, only restarting Notepad helps.

**Comment by cshnik** [comment]
Cannot reproduce.
"Ctrl+Wheel scroll" feature does not affect standard behavior of regular mouse wheel scrolling.
For testing purposes you may try to increase Windows line scrolling option:
![image](https://user-images.githubusercontent.com/8019354/50991649-c3011480-1547-11e9-8a80-b014c9c28279.png).
Please provide next data if this problem remains:
1. What is the document size (bytes/lines)?
2. What is the difference (in lines) on every wheel movement (up/down/up+down)?
3. Is there a CPU load spike when reproducing the issue?
4. Please check if any of the next factors affects behavior: caret position, selection, math evaluation mode?

**Comment by ProgerXP** [comment]
> For testing purposes you may try to increase Windows line scrolling option:

I know about this and other options but that's not the reason why it stops working - again, in one process scrolling works normally, in another process on the same system it suddenly starts skipping scrolls.

> What is the document size (bytes/lines)?

~40 KB, ~1k, happened when editing a PHP and a JS file (two different occasions).

> What is the difference (in lines) on every wheel movement (up/down/up+down)?

Standard. Same difference as in other programs and in another Notepad process that doesn't skip scrolls.

> Is there a CPU load spike when reproducing the issue?

When it starts happening, it doesn't matter if CPU is loaded or not. Even in idle state that particular process continues to skip scrolls.

> Please check if any of the next factors affects behavior: caret position, selection, math evaluation mode?

I can't spot any difference. I didn't change any Notepad or system settings when this started, and caret/selection don't seem to affect it.

This problem appears randomly and I can't reliably reproduce it. Notepad 2e has some debug logging facility - can you add logging of scroll-related conditions?

**Comment by ProgerXP** [comment]
> At this point #18 feature is the most likely reason of these skips 

Sadly, this hypothesis doesn't hold. I have disabled highlighting via the menu (Highlight Current Word) but still the first wheel turn in the opposite direction is skipped. The same happens if I keep highlighting enabled but set the cursor on a non-word (e.g. on a blank line).

> Set INI option HighlightSelection=0, restart app and repeat step 1

That's not really possible since the issue randomly appears in some processes that have been running for hours. But I assume disabling highlighting via the menu does the same as disabling it in the INI and restarting, in which case the cause of this bug is something else.

Even now, I have 2 editor processes opened, both were running for about the same amount of time, both used to edit a similar set of files (PHP, etc.) but one has this issue and another doesn't.

**Comment by cshnik** [comment]
> But I assume disabling highlighting via the menu does the same as disabling it in the INI and restarting

You are correct.

> In Notepad2, when you scroll up (WheelUp) then immediately down (WheelDown) - both scrolls are handled.

I tried to reproduce this behavior and found that I can't track exact number of mouse scrolling strokes for sure. Probably, ability to reproduce these steps heavily depends on the mouse type used. Finally, I switched to [AutoIt script](https://www.autohotkey.com/docs/scripts/NumpadMouse.htm) developed to remap keyboard keystrokes into mouse movements/clicks/scrolls. It allowed me to easily repeat exact number of mouse wheel scrolls when trying to reproduce the issue.
Here are my steps to reproduce:
1. Install AutoIt, download and compile [AutoIt script](https://www.autohotkey.com/docs/scripts/NumpadMouse.htm) or download precompiled [numpad-mouse.zip](https://github.com/ProgerXP/Notepad2e/files/2841881/numpad-mouse.zip)
2. Run script, toggle ScrollLock on to activate numpad mouse mode. ``NumpadSub``/``NumpadAdd`` will move up/down the mouse wheel.
3. Go to Keyboard properties and increase repeat delay, decrease repeat rate:
![image](https://user-images.githubusercontent.com/8019354/52427625-e7461600-2b32-11e9-9069-5db1877944ae.png)
4. Open Notepad2/Notepad2e, press quickly ``NumpadSub``, ``NumpadSub``, ``NumpadAdd``, ``NumpadAdd``. Note the actual result.
In my local tests the actual scrolling result may differ and depends on the physical keystrokes speed/delays (even with Keyboard settings from point 3).
Here is an example of the possible result for Notepad2 (4.2.25):
![notepad2](https://user-images.githubusercontent.com/8019354/52427674-fc22a980-2b32-11e9-9f4e-d4f082dc2017.gif)
Does it look the same as you saw in Notepad2e?

You may note, fast double mouse wheel up caused content to scroll up to 136 line (9 lines up from 145, equals to 3 slow wheel up), while fast double wheel down caused scrolling down to 142 line (6 lines down, equals to 2 slow wheel down).

The point is: this script has a built-in mouse scrolling acceleration logic which **emulates physical mouse** behavior. [WM_MOUSEWHEEL message](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-mousewheel) documentation states:
> wParam
> 
> The high-order word indicates the distance the wheel is rotated, expressed in multiples or divisions of WHEEL_DELTA, which is 120. A positive value indicates that the wheel was rotated forward, away from the user; a negative value indicates that the wheel was rotated backward, toward the user.
>...
> The wheel rotation will be a multiple of WHEEL_DELTA, which is set at 120. This is the threshold for action to be taken, and one such action (for example, scrolling one increment) should occur for each delta.
>
> The delta was set to 120 **to allow Microsoft or other vendors to build finer-resolution wheels (a freely-rotating wheel with no notches) to send more messages per rotation**, but with a smaller value in each message.

I have patched original AutoIt script ([numpad-mouse-no-acceleration.zip](https://github.com/ProgerXP/Notepad2e/files/2842055/numpad-mouse-no-acceleration.zip)) and tested the same scenario for Notepad2/Notepad2e.
There were no difference between Notepad2/Notepad2e when testing on exactly the same number of emulated wheel scrolls with the same provided distance param.

**Conclusion: WM_MOUSEWHEEL message params (and/or number of these messages) may vary depending on the mouse vendor/type/scrolling speed when trying to** ``scroll up (WheelUp) then immediately down (WheelDown)``.

Please do the following:
1. Download and run [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview)
2. Run test build from [Notepad2e-mousewheel-trace.zip](https://github.com/ProgerXP/Notepad2e/files/2842188/Notepad2e-mousewheel-trace.zip)
3. ``scroll up (WheelUp) then immediately down (WheelDown)``
4. Note DebugView output, e.g.:
![image](https://user-images.githubusercontent.com/8019354/52434069-119ed000-2b41-11e9-92f3-2e7506f4e3f7.png)
5. Compare the actual number of received up/down wheel steps.
I assume there will be a missing up/down wheel step (result of the mouse driver/OS work) having near the same nature as described about the AutoIt script work.

PS It is **extremly hard** to repeat **exactly the same number/delayes of wheel up/down strokes** even using key remapping AutoIt script (not to mention even a physical mouse).

**Comment by ProgerXP** [comment]
Likely caused by something on my system.
