### ISSUE TITLE
History dialog: focus third (second) item on show

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#209]
Make it so that when Alt+H dialog appears, the list of files is focused and the second item from top (i.e. target for Alt+G) is focused. Thus pressing Up/Down arrow keys changes selection in the list without the need to click inside the list with the mouse to focus it. 

If the list has fewer entries than 2 (1 or 0) then do whatever is easier to implement (e.g. don't focus at all, or focus 1st item).

**Comment by cshnik** [comment]
Done.
1. First item is selected when current document is untitled or history size < 2.
2. Second item is selected when document is not untitled.
3. Fixed `n2e_OpenMRULast()`-method (handles Alt+G command): recent files were not swapped.

**Comment by ProgerXP** [comment]
Good addition.

**Comment by ProgerXP** [comment]
Add 1 to the focused item's index so that History focuses the item immediately **following** the one subject to Recall (#8). Currently it focuses exactly the Recall item. This way, Alt+G opens previously opened file and Alt+H,Enter opens the file that was opened before the previously opened file.
