### ISSUE TITLE
Show the clock

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#210]
How complex is it to show current date/time (arbitrary format) in Notepad's menu bar or tool bar? Where is it simpler? Or is it the simplest in the status bar?

I know it can be shown in title bar but in Win10 it's pale and not very readable.

Note: the date/time should be updated by a timer.

**Comment by csware** [comment]
Doesn't Windows show this in the systray?

**Comment by ProgerXP** [comment]
> Doesn't Windows show this in the systray?

On a 24+ inch display you hardly see any icons in the corner, let alone can read the numbers. I often spend 8+ hours a day with this editor, and I often need to look up current date/time; straining my eyes every now and then to do that is no good.

For years I've been using a separate program that puts date/time in the titlebar of the active program and once you try it you don't want to come back (even if it's a seemingly trivial tidbit).

**Comment by devclow466** [comment]
> How complex is it to show current date/time (arbitrary format) in Notepad's menu bar or tool bar? Where is it simpler? Or is it the simplest in the status bar?
> 
> I know it can be shown in title bar but in Win10 it's pale and not very readable.
> 
> Note: the date/time should be updated by a timer.

man, please give me your jabber. we have to talk asap.

**Comment by ProgerXP** [comment]
@devclow466 I don't have any Jabber, why?

**Comment by devclow466** [comment]
> @devclow466 I don't have any Jabber, why?

please make some, it's quick. the subject is really important, i dont think its good idea to discuss details here. i sent you email lately but you didn't reply.

**Comment by ProgerXP** [comment]
I don't remember getting any. I don't have time to be online for chatting. If you want to keep something private, encrypt your message with this GPG key and send me an email and your key (using the form on my page or if you know the address then directly): http://proger.me/3eNbH0Sf.txt

Don't clutter this issue page anymore please.

**Comment by devclow466** [comment]
> > Doesn't Windows show this in the systray?
> 
> On a 24+ inch display you hardly see any icons in the corner, let alone can read the numbers. I often spend 8+ hours a day with this editor, and I often need to look up current date/time; straining my eyes every now and then to do that is no good.
> 
> For years I've been using a separate program that puts date/time in the titlebar of the active program and once you try it you don't want to come back (even if it's a seemingly trivial tidbit).

did you get it?

**Comment by devclow466** [comment]
> How complex is it to show current date/time (arbitrary format) in Notepad's menu bar or tool bar? Where is it simpler? Or is it the simplest in the status bar?
> 
> I know it can be shown in title bar but in Win10 it's pale and not very readable.
> 
> Note: the date/time should be updated by a timer.

man, answer please, i sent twice.

**Comment by cshnik** [comment]
> How complex is it to show current date/time (arbitrary format) in Notepad's menu bar or tool bar? Where is it simpler? Or is it the simplest in the status bar?

Status bar is the most suitable place for this auxiliary information. It will take up to 1-2 hours.

**Comment by ProgerXP** [comment]
> It will take up to 1-2 hours.

2 hours for status bar? There is so much code for the clock?

What about menu bar? E.g. a disabled menu item after the `?` menu, updated by a timer.

![clock](https://user-images.githubusercontent.com/1643195/54767583-7d7b5a80-4c0e-11e9-9ca7-2730e105e237.png)

**Comment by cshnik** [comment]
> > It will take up to 1-2 hours.
> 
> 2 hours for status bar? There is so much code for the clock?

This was my raw estimation to display date/time info anywhere (including implementation of possible owner draw proc). Status bar info is the simplest way which will definitely take less time.
Please provide details on the complete set of required options for this feature (e.g. time format support, refresh rate, accessible UI for options (if required), etc). 

> What about menu bar? E.g. a disabled menu item after the ? menu, updated by a timer.

To my mind it looks ugly. Regular applications never use menu items to display extra information.
![image](https://user-images.githubusercontent.com/8019354/54825024-1ed1e180-4cdf-11e9-968c-1a0874901857.png)

**Comment by ProgerXP** [comment]
>  Please provide details on the complete set of required options for this feature (e.g. time format support, refresh rate, accessible UI for options (if required), etc).

Refresh rate - 10 seconds via the regular WM_TIMER. Only one INI option - format (empty string, which is the default, disables the clock display). Are you aware of any standard function that formats date/time? I think WinAPI has no such function. If so, we'll use some simple format.

> To my mind it looks ugly. Regular applications never use menu items to display extra information.

Maybe, but to me it looks really good in this place. See if we can use this approach, if it's easy to update menu text (of course, this menu item should be disabled).

**Comment by cshnik** [comment]
1. ClockFormat INI option added.
2. [strftime](https://en.cppreference.com/w/cpp/chrono/c/strftime) is used to format datetime.
> [Notepad2e]
ClockFormat=%x - %T
![image](https://user-images.githubusercontent.com/8019354/55027565-28897b00-5038-11e9-83a2-88a3b6468b33.png)

**Comment by ProgerXP** [comment]
> `RedrawWindow(hwndMain, NULL, NULL, RDW_INVALIDATE | RDW_UPDATENOW | RDW_ERASE | RDW_FRAME | RDW_NOINTERNALPAINT);`

Uh-huh, we need to repaint the entire window every 10 seconds (after changing the menu text)?

**Comment by cshnik** [comment]
> Uh-huh, we need to repaint the entire window every 10 seconds (after changing the menu text)? Is there any other way, e.g. refresh the menu bar only?

Specified call cause repaint of window's non-client area only (visible text editor area is not affected). The only alternative is to provide pre-calculated update rectangle corresponding to clock menu item but this requires calculation of this rectangle. Please confirm if we need to prepare and provide this parameter for RedrawWindow().

**Comment by ProgerXP** [comment]
> Specified call cause repaint of window's non-client area only 

Are you sure it doesn't repaint NC area in addition to (not instead of) the client area? The documentation doesn't say RDW_FRAME ignores the client area. Besides, I think Windows doesn't allow non-rectangular invalidation.

I find it strange that SetMenuItemInfo doesn't repaint the relevant region automatically. Is this a known/official behaviour?

SetMenuItemInfo docs say: 

> The application must call the DrawMenuBar function whenever a menu changes

I think we need to call this function, it must be way more efficient than RedrawWindow.

**Comment by cshnik** [comment]
> Are you sure it doesn't repaint NC area in addition to (not instead of) the client area? The documentation doesn't say RDW_FRAME ignores the client area.

To skip repainting of client area when calling RedrawWindow() we used RDW_NOINTERNALPAINT + empty update area:

> RDW_NOINTERNALPAINT - Suppresses any pending internal WM_PAINT messages. This flag does not affect WM_PAINT messages resulting from a non-NULL update area.

> I find it strange that SetMenuItemInfo doesn't repaint the relevant region automatically. Is this a known/official behaviour?

This is a very common behavior in WinAPI: most of the functions which are not explicitly described as "will cause window redraw" does not affect visual content.

> > The application must call the DrawMenuBar function whenever a menu changes
> 
> I think we need to call this function, it must be way more efficient than RedrawWindow.

Done.

**Comment by ProgerXP** [comment]
When Reload From Disk is used, old clock menu item is not removed/replaced - a new one is added every time.

**Comment by cshnik** [comment]
Fixed.
