### ISSUE TITLE
Awk syntax highlighting

### ISSUE THREAD

**Issue by cup** [ProgerXP/Notepad2e#216]
- https://github.com/rizonesoft/Notepad3/blob/master/src/StyleLexers/styleLexAwk.c
- https://github.com/zufuliu/notepad2/blob/master/src/EditLexers/stlAwk.c

**Comment by ProgerXP** [comment]
@cshnik see if any of these can be used with our Scintilla version. I'd use the second link (with EDITSTYLE_DEFAULT), it seems to be clearer even though it's missing some keywords.

**Comment by cshnik** [comment]
Added implementation from ``Notepad3`` due to the next reasons:
1. It require less changes (no changes for Scintilla).
2. It use regular python lexer while alternative implementation (from ``notepad2``) is based on extended cpp lexer (SCE_C_FUNCTION option).
3. It declares more keywords.

**Comment by cshnik** [comment]
My bad. I've accidentally committed into ``process_elevation`` branch.
Please confirm if this fix/change is approved an I'll move it into ``master`` branch.

**Comment by ProgerXP** [comment]
> It require less changes (no changes for Scintilla).

The other one requires such changes? It's just strange that Python lexer is used because awk has nothing in common with Python.

In any case, please add a comment linking to the original implementation. Otherwise it's okay.

**Comment by cup** [comment]
https://github.com/stefankueng/BowPad/issues/31

**Comment by cshnik** [comment]
> In any case, please add a comment linking to the original implementation.

Done.
