### ISSUE TITLE
Reduce Ctrl+Wheel delay

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#217]
I remember when we were implementing Ctrl+Wheel scroll (which scrolls by entire page) we added a timer to prevent scrolling more often than N ms (because Windows sends too many scroll messages). What value is it? 1 second?

**Comment by cshnik** [comment]
Default delay value is 50 ms:
> #define DEFAULT_WHEEL_SCROLL_INTERVAL_MS  50

This setting is customizable via INI configuration, setup ``WheelScrollInterval`` option, e.g:
> [Notepad2e]
WheelScrollInterval=25

BTW, this value can't be less then 10 ms: [MSDN: SetTimer](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-settimer).
