### ISSUE TITLE
Charsets - reCODing and reLOADing is opposite things, not the same

### ISSUE THREAD

**Issue by the-Arioch** [ProgerXP/Notepad2e#218]
Just used to show Notepad2 as the simplest (smallest) tool to recode text from DOS/8166 to Windows/1251 codepage.

Just because Notepad2 is so much smaller/faster than UniRed or Notepad++

But the specific GUI for this is rather complicated!

Initial state: I launch N2, I open txt-file encoded as DOS Cyrillic (866). N2 erroneously assumes Win Cyrillic (1251) codepage.

1) double-click in status bar almost does it, but it has no option to assume mis-detected codepage without recoding the text. I vote there to be radiobutton or checkbox for assuming another codepage without actual recoding. In Notepad++ there is a special menus for assuming vs transcoding

2) the EDIT menu has a group of similar submenus mass-changing text, like Encoding. However there is nothing about codepage. That creates the illusion that Notepad2 has no codepages support, not at least in menu. Codepages-related menu is - at least for user - much more logically to find there, in EDIT menu and in the group of other mass-edit submenus.

3) The FILE/Encoding submenu has the needed actions but in quite confusing way

3.1) the placement in FILE instead of EDIT
3.2) the title ENCODING is confusingly similar to ENCODE, it is better to change one of them (codepages, character sets, etc)

3.3) worse of all, the RECODE item - which offers exactly the opposite of the name: it offers assuming WITHOUT recoding - but to learn it you have to run it. Then the other menu items like Unicode and More - those items DO recoding, but they are presented like they do no recode, by mere presence of special RECODE menu item.

Фигня получается....

I think better approach would be one taken by Notepad++ - to have two equal submenus, but one for recoding the text and another for re-attributing text to another charset without actual recoding. The content of those submenus to be identical (those items like Unicode, UTF, More) just with different values for recode-vs-reload flag.

**Comment by ProgerXP** [comment]
> Just used to show Notepad2 as the simplest (smallest) tool to recode text from DOS/8166 to Windows/1251 codepage.

Why not use iconv if you just need the convertion?

> But the specific GUI for this is rather complicated!

You can go without GUI, no?

1. Open your DOS file, let it be mis-detected as ANSI.
2. F8, select OEM, Enter
3. F9, select cp1251 (e.g. by holding `c`), Enter

> double-click in status bar almost does it, but it has no option to assume mis-detected codepage without recoding the text

You can still use it - let it change encoding of the document (and garble it), then simply reload (F5, refusing to save) - it will assume the previously chosen encoding, not the default ANSI.

> Codepages-related menu is - at least for user - much more logically to find there, in EDIT menu and in the group of other mass-edit submenus. 

IMO, encoding is a property of a document or a file, not of its part, and therefore it belongs to File, not Edit menu.

> it offers assuming WITHOUT recoding - but to learn it you have to run it

Or read what the dialog says - and it says "Select source encoding to reload file". The "reload" part makes it quite clear. Although I agree that the "recode" might be a misnomer but we shouldn't change Notepad2's menu organization and the like, by now it's a matter of habit I guess.

**Comment by ProgerXP** [comment]
Thinking about "recode" name again, I think this one we can change. Something like `Reload Using...`, what do you say?

**Comment by ProgerXP** [comment]
@cshnik Rename Encoding > Recode... to `&Reload As...`

**Comment by cshnik** [comment]
Done. Corresponding dialog's caption changed from "Recode" to "Reload As".
