### ISSUE TITLE
Find button states not updated on switch to Transform backslashes

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#219]
1. Open Find
2. Enter `}` into the search string
3. Enable regexps - buttons will be disabled because it's not a valid expression
4. Now enable `Transform backslashes` - the expression is now valid but buttons are still disabled

**Comment by cshnik** [comment]
Fixed.
Step 2 should be read as "Enter `\` into the search string".

**Comment by ProgerXP** [comment]
Related bug so posting here.

Buttons are not updated when the input's value changes using the combobox. For example, enable regexp mode, enter `[` into the search input then switch to another value from the history (which is a valid regexp) with the arrow button and mouse - now Search String is valid but buttons are disabled anyway.

**Comment by cshnik** [comment]
> Buttons are not updated when the input's value changes using the combobox.

Fixed.
