### ISSUE TITLE
Could not use some font.

### ISSUE THREAD

**Issue by efreedev** [ProgerXP/Notepad2e#220]
Notepad 2e R47(built on 05/1/2018) @ Win10
When I choice the Chinese fonts （Exactly the font name contains Chinese chars), the font that the display uses  is not change, and use the system default(maybe).

**Comment by ProgerXP** [comment]
I have used MS Japanese fonts in the past without issues.

Try the original Notepad2 from http://www.flos-freeware.ch/ - does it have the same problem?
