### ISSUE TITLE
Edit > Insert > Random

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#221]
Add a horizontal separator and new menu command `&Random` that inserts (or replaces non-empty selection) a number in range 1..99999 (inclusive) padded as `%05d`. The number is selected.

We need a hotkey for this command too. Which we have available?

**Comment by cshnik** [comment]
Done.

> We need a hotkey for this command too. Which we have available?

Ctrl+Alt+Shift+R was assigned for this command (``R`` was captured to match menu item's accelerator char).

**Comment by ProgerXP** [comment]
> The number is selected.

This doesn't happen.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Please don't use tabs in this project.
