### ISSUE TITLE
Code style - remove tabs

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#228]
Please don't use tabs in this project. I thought we had this set up in vcproj formatting rules, don't we?

Currently the code has a mixture of tabs and spaces and it's growing. 

(I mean only our own `src`, not `scintilla` or other parts.)

**Comment by cshnik** [comment]
The most recent miss was an accidental mistake related to temporary switch to fix Scintilla's sources. I forgot to switch back my config.

**Comment by cshnik** [comment]
Please clarify the places where currently tabs are incorrectly used as a part of Notepad2e sources.

**Comment by ProgerXP** [comment]
```
$ grep -lrP '\t' src test

src/Helpers.c
src/Extension/tinyexpr/Makefile
src/Extension/base64/base64.h
src/Extension/base64/base64.c
src/Extension/Utils.h
src/Extension/StringRecoding.c
src/Extension/DPIHelper.cpp
src/Dialogs.c
test/Extension/TextEncodingTests.cpp
test/Extension/TextEncodingTestCaseData.cpp
```

![tabs](https://user-images.githubusercontent.com/1643195/60746672-c3bfb400-9f88-11e9-874c-424c08d09761.png)

**Comment by cshnik** [comment]
Fixed.

These are original files which came as a part of third-party projects (files are not directly included/attached in Notepad2e):
> src/Extension/tinyexpr/Makefile
> src/Extension/base64/base64.h
> src/Extension/base64/base64.c
