### ISSUE TITLE
Hide pointer while typing

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#230]
Windows Control Panel has an option in Mouse Properties > Pointer Options called `Hide pointer while typing` (enabled by default). For some reason, it doesn't work with Notepad2 or Notepad++. The strangest thing is that if you open a Find dialog and start typing there - the pointer will be hidden. But it isn't hidden while typing in the main window. 

I've also noticed that in Firefox cursor isn't hidden in any part of its window but in Gvim on Windows it is hidden properly. So it seems like a program-specific quirk, maybe even Scintilla-specific.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Windows doesn't hide the cursor by default? Do we really need to manually track mouse movements and key presses? Is it a recommended way you've found somewhere?

Also, why the counter is needed?

**Comment by cshnik** [comment]
Please consider the following articles:
https://superuser.com/questions/928839/what-does-the-hide-pointer-while-typing-feature-actually-do
https://devblogs.microsoft.com/oldnewthing/20091217-00/?p=15643

**Comment by ProgerXP** [comment]
Wow, I've never heard of this story. I was sure this setting was enforced by the default window proc. No wonder it's rarely working.

**Comment by ProgerXP** [comment]
This works for the main textarea but do you know why Hide pointer while typing is not respected for other input fields? As I've written in the first post:

> if you open a Find dialog and start typing there - the pointer will be hidden

But it's even hidden when the setting is disabled.

**Comment by cshnik** [comment]
Specified behavior implemented in the Windows OS code responsible for standard input fields/edit controls. While Scintilla editor is a custom control which is not an edit based one.

**Comment by ProgerXP** [comment]
Issue: the pointer remains hidden when a (modal) dialog appears. For example, start typing and then press Ctrl+O - you'll have no cursor in the file open dialog. 

I think the text area should listen for focus-lost event in addition to mouse-move.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Hide pointer on arrow keys (navigation) as well. Ideally it should be hidden on any keyboard interaction in the text area rather than `WM_CHAR`.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Pointer is correctly shown if you open Notepad2's dialogs (Alt+O, etc.) but if you make a new blank document and press Ctrl+O or Ctrl+S - the file dialog will have no pointer visible.

**Comment by cshnik** [comment]
> 1. Pointer is correctly shown if you open Notepad2's dialogs (Alt+O, etc.) but if you make a new blank document and press Ctrl+O or Ctrl+S - the file dialog will have no pointer visible.

Cannot reproduce.

> 2. Pointer must be shown when calling Launch > Shell Menu.

Fixed.

> 3. ...and when starting to drag text. Test: select text, press and hold Ctrl, then mouse-down on the selection and start dragging - you won't see the cursor. However, if you first drag and then press Ctrl, the cursor is _not_ hidden (correct).

Fixed.

**Comment by ProgerXP** [comment]
> Cannot reproduce.

It's quite easy and the problem is again with holding down Ctrl (like in other 2 cases that you have fixed). Try this: press and hold Ctrl, observe that the cursor became invisible, then just press O or S (while holding Ctrl) and you will notice that the dialog has no cursor. 

It's important that the document should not be changed because if a "Save?" message box is produced, the cursor will be shown and this bug won't trigger.

**Comment by cshnik** [comment]
Fixed.
