### ISSUE TITLE
ICU build: missing regexp warnings

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#232]
Related to #231.

If you do a Find on a non-UTF-8 buffer it will give a warning. But if you do Grep - it won't. Please check all places where regexps are used and add missing buffer encoding warnings.

**Comment by cshnik** [comment]
1. Added missing prompts for Replace(), ReplaceInSelection(), Grep(), Ungrep() commands.
2. Improved UI behavior: decline for "Convert this file to UTF-8?" ICU prompt will not cause "Find/Replace Text" window to be hidden even if "Close after find/replace" flag checked. The point is: no - find, no - close.
3. BTW Grep/Ungrep commands were implemented to always close "Find/Replace Text" window ("Close after find" flag is always treated as CHECKED). Please confirm if this is OK.

**Comment by ProgerXP** [comment]
> BTW Grep/Ungrep commands were implemented to always close "Find/Replace Text" window 

I don't remember such a requirement. Your change must be fine.
