### ISSUE TITLE
Warnings about truncated pointers

### ISSUE THREAD

**Issue by Jordem** [ProgerXP/Notepad2e#234]
Hello,

I suggest to replace the **DeclareGetWindowProp/DeclareSetWindowProp/DeclareSetWindowProp2** lines in **DPIHelper.cpp** and **DPIHelper.h** since they are causing warnings about pointer truncations and even cause compile-errors using GCC.

I replaced them with something like that:

```
BOOL GetWindowDPIInitialized(const HWND hwnd)
{
	return PtrToInt(GetProp(hwnd, PROPERTY_WINDOW_DPI_INITIALIZED));
}

void SetWindowDPIInitialized(const HWND hwnd, const BOOL value)
{
	SetProp(hwnd, PROPERTY_WINDOW_DPI_INITIALIZED, IntToPtr(value));
}

BOOL GetWindowSkipDPIResize(const HWND hwnd)
{
	return PtrToInt(GetProp(hwnd, PROPERTY_WINDOW_SKIP_DPI_RESIZE));
}

void SetWindowSkipDPIResize(const HWND hwnd, const BOOL value)
{
	SetProp(hwnd, PROPERTY_WINDOW_SKIP_DPI_RESIZE, IntToPtr(value));
}

int GetWindowFontSize(const HWND hwnd)
{
	return PtrToInt(GetProp(hwnd, PROPERTY_WINDOW_FONT_SIZE));
}

void SetWindowFontSize(const HWND hwnd, const int value)
{
	SetProp(hwnd, PROPERTY_WINDOW_FONT_SIZE, IntToPtr(value));
}

HANDLE GetWindowDynamicFont(const HWND hwnd)
{
	return GetProp(hwnd, PROPERTY_WINDOW_DYNAMIC_FONT);
}

void SetWindowDynamicFont(const HWND hwnd, const HANDLE value)
{
	SetProp(hwnd, PROPERTY_WINDOW_DYNAMIC_FONT, value);
}

DWORD GetWindowDPI(const HWND hwnd)
{
	return PtrToUlong(GetProp(hwnd, PROPERTY_WINDOW_DPI));
}

void SetWindowDPI(const HWND hwnd, const int value1, const int value2)
{
	SetProp(hwnd, PROPERTY_WINDOW_DPI, (HANDLE)MAKEWPARAM(value1, value2));
}

DWORD GetWindowPosition(const HWND hwnd)
{
	return PtrToUlong(GetProp(hwnd, PROPERTY_WINDOW_POSITION));
}

void SetWindowPosition(const HWND hwnd, const int value1, const int value2)
{
	SetProp(hwnd, PROPERTY_WINDOW_POSITION, (HANDLE)MAKEWPARAM(value1, value2));
}

DWORD GetWindowSize(const HWND hwnd)
{
	return PtrToUint(GetProp(hwnd, PROPERTY_WINDOW_SIZE));
}

void SetWindowSize(const HWND hwnd, const int value1, const int value2)
{
	SetProp(hwnd, PROPERTY_WINDOW_SIZE, (HANDLE)MAKEWPARAM(value1, value2));
}
```

**Comment by ProgerXP** [comment]
> and even cause compile-errors using GCC.

Can GCC actually compile Notepad2 code? Never tried that.

@cshnik Do you find the request reasonable?

**Comment by Jordem** [comment]
@ProgerXP I could compile notepad2-mod with minor changes.
After that I found this project and saw that it is still developed, so I tried to compile it with GCC but there are some problems which I couldn't fix yet.

**Comment by cshnik** [comment]
I've slightly changed DPIHelper module to provide support for gcc.

**Comment by ProgerXP** [comment]
@Jordem Does the change help?

**Comment by Jordem** [comment]
Yes it helps.

Still I can't get pass this error while compiling with gcc:

"Notepad2e\scintilla\boostregex\BoostRegExSearch.cxx|399|error: cannot bind non-const lvalue reference of type 'BoostRegexSearch::Match&' to an rvalue of type 'BoostRegexSearch::Match'"

**Comment by cshnik** [comment]
> "Notepad2e\scintilla\boostregex\BoostRegExSearch.cxx|399|error: cannot bind non-const lvalue reference of type 'BoostRegexSearch::Match&' to an rvalue of type 'BoostRegexSearch::Match'"

Fixed.
