### ISSUE TITLE
HTML: add main keyword

### ISSUE THREAD

**Issue by cup** [ProgerXP/Notepad2e#236]
https://github.com/ProgerXP/Notepad2e/blob/b017e4126aa1001540a44808f9b95a9e90c4e1d6/src/Styles.c#L79-L89

https://developer.mozilla.org/Web/HTML/Element/main

**Comment by ProgerXP** [comment]
@cshnik Add these:

```
main
picture
rb
rtc
template
```

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Any idea why <template> is highlighted as an invalid tag?

![scr](https://user-images.githubusercontent.com/1643195/65711551-c7516b80-e09d-11e9-9964-8706cdf0e265.png)

**Comment by cshnik** [comment]
Fixed.
