### ISSUE TITLE
Disable Launch commands for Unnamed

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#238]
Most Launch commands do not work when there is no file. Currently Execute Document and Open Folder are disabled in such cases but Shell Menu and Open With are enabled - check if they can work without a file (I think not) and disable them if not.

**Comment by cshnik** [comment]
Fixed.
Please consider the following:
1. Shell Menu was already disabled for unnamed in #229 [5106f192].
2. Open With functionality depends on "Settings> Save Before Running Tools" option.
a) If the option is unchecked Open With is disabled for unnamed (the same as Shell Menu).
b) If the option is checked Open With is enabled to allow user to save file and proceed with OpenWithDlg().

**Comment by ProgerXP** [comment]
> If the option is checked Open With is enabled to allow user to save file and proceed with OpenWithDlg().

We better disable it always because even in this case if you pick No ("don't save") it will bring up OpenWithDlg which will not work anyway.

**Comment by cshnik** [comment]
Fixed.
