### ISSUE TITLE
Favorites - focus first item

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#240]
Similarly to how the History dialog (Alt+H) focuses first (or now also second) item, the Alt+I dialog must focus the first item when it's displayed. Currently none is focused.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
The OK button is disabled on show even though the item is selected.

**Comment by cshnik** [comment]
Fixed. The same logic with initial item selection implemented for "Open With" dialog, `Alt+L`.
