### ISSUE TITLE
No File Change Notification for network locations

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#241]
Open a file from a network share (`\\comp\share\file.txt`) or from a mapped network drive (`z:\file.txt`). Set File Change Notification to Display or Reload. Open another instance on the same file (Alt+N), set it there too. Now save (Ctrl+S) in any instance.

Expected: you see a message. Actual: no message appears.

Note that if you have Single File Instance enabled and try to open the same file from Explorer, Notepad 2e doesn't open (as expected) but only switches to one of the running instances. So it does properly recognize what "file" it has opened.

Even if you don't have other computers you can use standard Windows administrative shares (`\\this_comp_name\c$\file.txt`) or use a VM.

Perhaps this should be fixed/refactored together with #129.

**Comment by cshnik** [comment]
This is an old well-known problem: File Change notification mechanism may fail or work incorrectly for network folders. 
https://qualapps.blogspot.com/2010/05/understanding-readdirectorychangesw_19.html
> **Network Drives**
ReadDirectoryChangesW works with network drives, but only if the remote server supports the functionality. Drives shared from other Windows-based computers will correctly generate notifications. Samba servers may or may not generate notifications, depending on whether the underlying operating system supports the functionality. Network Attached Storage (NAS) devices usually run Linux, so won't support notifications. High-end SANs are anybody's guess.

**Comment by ProgerXP** [comment]
Strange, I have shares from Windows and it still doesn't work. It's a big issue for me. We also have #129; maybe these issues can be fixed together by implementing some kind of more reliable file monitoring? Or maybe `FindFirstChangeNotification` works better for network folders?

**Comment by ProgerXP** [comment]
Here is a simple way to reproduce: use a virtual VMware machine with Windows, set up a shared folder with the host system, put a text file into that folder and open it in Notepad 2e in both the host and the guest. Change the file in the host, Save - expect guest's Notepad to report the file change but it doesn't happen. Yet both guest and host are using Windows (tested with Windows 10).

This is the same regardless how you open the file in the guest: via network share (`\\vmware-host\Shared Folders\my folder\file.txt`) or via that folder mounted as a network drive (`Z:\file.txt`).

**Comment by cshnik** [comment]
Switched from directory changes notifications to file attributes/size state survey on timer basis.

**Comment by ProgerXP** [comment]
> I have discovered that Notepad++ correctly displays file change notification in the same setting where Notepad2 fails to do so.

For the sake of completeness, please check how it's implemented in Notepad++.

**Comment by cshnik** [comment]
> For the sake of completeness, please check how it's implemented in Notepad++.

Notepad++ uses [composite scheme](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fc371a1ffeb87559f31b03fbd5a631502204584a/PowerEditor/src/NppIO.cpp#L44-L131) to monitor file changes:
1. [ReadDirectoryChanges()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fc371a1ffeb87559f31b03fbd5a631502204584a/PowerEditor/src/NppIO.cpp#L61-L62)
2. [GetFileAttributesEx()](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fc371a1ffeb87559f31b03fbd5a631502204584a/PowerEditor/src/NppIO.cpp#L112-L117) every 250 ms in case of timeout:
```
BOOL CReadFileChanges::DetectChanges() {


	WIN32_FILE_ATTRIBUTE_DATA fInfo;
	BOOL rValue = FALSE;
	::GetFileAttributesEx(_szFile, GetFileExInfoStandard, &fInfo);


	if ((_dwNotifyFilter & FILE_NOTIFY_CHANGE_SIZE) && (fInfo.nFileSizeHigh != _lastFileInfo.nFileSizeHigh || fInfo.nFileSizeLow != _lastFileInfo.nFileSizeLow)) {
		rValue = TRUE;
	}


	if ((_dwNotifyFilter & FILE_NOTIFY_CHANGE_LAST_WRITE) && (fInfo.ftLastWriteTime.dwHighDateTime != _lastFileInfo.ftLastWriteTime.dwHighDateTime || fInfo.ftLastWriteTime.dwLowDateTime != _lastFileInfo.ftLastWriteTime.dwLowDateTime)) {
		rValue = TRUE;
	}


	_lastFileInfo = fInfo;
	return rValue;
}
```
