### ISSUE TITLE
Math Eval for rectangular selection

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#242]
Allow evaluating math for rectangular selection (Alt+drag), for example, when a column is selected in this text (result=15):

![screenshot](https://user-images.githubusercontent.com/1643195/65766084-9ec78100-e132-11e9-92c0-73184255206f.png)

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Invalid result if rectangular selection contains blank lines:

```
1 [2]

3 [4]
```

Select 3rd column with Alt - result will be either 2 or 4 depending on if you select top down or the other way around.

**Comment by cshnik** [comment]
Fixed.
