### ISSUE TITLE
Lua LPeg Lexers

### ISSUE THREAD

**Issue by cup** [ProgerXP/Notepad2e#245]
Home page:

https://scintilla.sourceforge.io/LPegLexer.html

Code is available here:

https://sourceforge.net/projects/scintilla/files/scintilla/3.11.2

100 lexers already supported, and more can be added easily via Lua.

**Comment by ProgerXP** [comment]
@cshnik See if we can integrate this.

**Comment by cup** [comment]
@ProgerXP thank you. I like Notepad2e as it is very fast. If LPeg is possible will be very useful
