### ISSUE TITLE
Mark Occurences

### ISSUE THREAD

**Issue by ghost** [ProgerXP/Notepad2e#246]
With these programs:

- https://github.com/zufuliu/notepad2
- https://github.com/rizonesoft/Notepad3

The options are available, `View`, `Mark Occurences`:

- Off
- On
- On, Match Whole Word Only

while with Notepad2e those options are not available, but instead `View`,
`Highlight Current Word`.

I have found the Notepad2e option distracting, as it highlights words as the
cursor moves. Contrast with the other programs, which only highlight if you have
selected text. I think the current option should be changed to match the other
programs, or perhaps a new option could be added.

**Comment by ProgerXP** [comment]
> I have found the Notepad2e option distracting, as it highlights words as the
cursor moves. Contrast with the other programs, which only highlight if you have
selected text. 

For me, this is actually a deal breaker. Personally I am using the `Highlight Current Word` setting to spot typos (e.g. in variable names or regular human words) which is not possible if words are highlighted only when selected. I'm also an occasional user of Notepad++ and I find it inconvenient that I need to select something to highlight it, and that I can't highlight parts of a word or multiple words (with spaces).

Perhaps you simply need to configure your highlight styles to be less distracting? E.g. a pale underline. Also, remember you can somewhat "force" a highlighting style by entering Edit Word (Ctrl+Tab), the `Edit` prefix: https://github.com/ProgerXP/Notepad2e#current-word-highlighting, so other prefixes may specify no styling (transparent). But that requires an extra action (select + invoke Edit Word), not just selection.

**Comment by cup** [comment]
Similar issue https://github.com/ProgerXP/Notepad2e/issues/248 was deleted. 
Here is what @ProgerXP had said:

> I suppose we can add a new Highlight Current Selection flag that will work in 
> addition to Highlight Current Word (which can be enabled or disabled). If 
> enabled, it will always highlight substrings, not words because Edit Word 
> (Ctrl+Tab) on a non-empty selection edits a substring.
>
> So if both are enabled then with empty selection you get words highlighted and 
> with non-empty selection you get substrings highlighted. If only Word is 
> enabled then it will highlight the word under cursor even with non-empty 
> selection (like it does now). Both Word and Selection highlighting are using 
> the same INI styles.
>
> @cshnik See my previous message. Make the new mode enabled by default (in 
> contrast with word highlighting). Its options are the same that work when 
> doing Ctrl+Tab on a substring (not empty selection) - i.e. match whole word = 
> off, match case = on.

**Comment by cup** [comment]
https://github.com/ProgerXP/Notepad2e/issues/211

https://github.com/ProgerXP/Notepad2e/issues/246
https://github.com/ProgerXP/Notepad2e/issues/255
