### ISSUE TITLE
Multi-file drop to concatenate all

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#250]
Currently Notepad2 allows dropping only 1 file from Explorer and shows an error otherwise. Instead of the error, let it work this way:  

- first, like with dropping 1 file, close current file (asking to save it, etc. as if user called File > New)
- take every dropped file one after another
- load every file as if it was opened as usual in Notepad2 (`FileLoad` or `FileIO`); this can bring interactive prompts (e.g. for large files)
- after loading (with the usual charset and EOL detection, etc.) append the entire buffer to a common large buffer
- after processing all files create a new file (as if via File > New, i.e. with default charset, highlighting and other settings) and paste the large buffer into it
- any error during processing (loading of any file, etc.) stops it and displays an error (either leaving old file opened or creating a new blank buffer as if after File > New)

Essentially this works like a *nix `cat` command or Windows `copy file1 + file2 + ...` except that it can load files with different charsets, etc. as long as Notepad2 is able to correctly detect each file's options.

**Comment by cshnik** [comment]
Done. Currently implemented scheme is:
1. By default, encoding of new file (`cat` command result) is ASCII.
2. If any of the dropped file has Unicode/UTF-8 encoding then encoding of new file is UTF-8.

**Comment by ProgerXP** [comment]
> By default, encoding of new file (`cat` command result) is ASCII.

In Notepad2 you can set the default encoding (File > Encoding > Defaut). It's good that you have made explicit convertion to UTF-8 if any input buffer has Unicode encoding, however, if no buffers do - then new buffer's encoding should match the configured default. From my tests it already works this way.

```
LPSTR lpDataNew = n2e_Alloc(iDataLength + iCurrentDataLength + 1);
memcpy_s(lpDataNew, iDataLength + iCurrentDataLength + 1, lpData, iDataLength);
```

Why are we using GlobalAlloc() instead of C's alloc/realloc/free? In this situation, realloc() would simplify the code (no need for memcpy and free in the loop). 

```
void* n2e_Realloc(void* ptr, size_t len)
{
  n2e_Free(ptr);
  return n2e_Alloc(len);
}
```

Besides, this isn't an equivalent to realloc() because it doesn't copy the old memory so this should be either rewritten or removed (and occurrences in ExtSelection.c replaced) because the name is misleading.

**Comment by cshnik** [comment]
> > By default, encoding of new file (`cat` command result) is ASCII.
> 
> In Notepad2 you can set the default encoding (File > Encoding > Defaut). It's good that you have made explicit convertion to UTF-8 if any input buffer has Unicode encoding, however, if no buffers do - then new buffer's encoding should match the configured default. From my tests it already works this way.
> 
You are correct. There were no changes for encoding in this case when creating new file. Thus, this point should look like:
1. By default, encoding of new file (`cat` command result) is **default** (File > Encoding > Default).

> ```
> LPSTR lpDataNew = n2e_Alloc(iDataLength + iCurrentDataLength + 1);
> memcpy_s(lpDataNew, iDataLength + iCurrentDataLength + 1, lpData, iDataLength);
> ```
> 
> Why are we using GlobalAlloc() instead of C's alloc/realloc/free? In this situation, realloc() would simplify the code (no need for memcpy and free in the loop).
> 
> ```
> void* n2e_Realloc(void* ptr, size_t len)
> {
>   n2e_Free(ptr);
>   return n2e_Alloc(len);
> }
> ```
> 
N/A. Initial code was added back in 2014 in [38daad3](https://github.com/ProgerXP/Notepad2e/commit/38daad37c0e7914a0bab040c81119615a93dd4a5) (see HL_Realloc).

> Besides, this isn't an equivalent to realloc() because it doesn't copy the old memory so this should be either rewritten or removed (and occurrences in ExtSelection.c replaced) because the name is misleading.

Done.
1. Switched from GlobalAlloc/GlobalFree to malloc/realloc/free.
2. Added code cleanup for file concatenate logic.
