### ISSUE TITLE
Lua LPeg Lexers

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#251]
Home page:

https://scintilla.sourceforge.io/LPegLexer.html

Code is available here:

https://sourceforge.net/projects/scintilla/files/scintilla/3.11.2

100 lexers already supported, and more can be added easily via Lua.

---

Formerly #245 reported by @cup [Steven Penny] on 02.01.2020.

---

Related: #244.

**Comment by ProgerXP** [comment]
To recap, we have upgraded Scintilla to the version supporting LPegLexer. Now this functionality should be exposed - for example, by embedding Lua scripts into the INI file (such as one Lua script in its own `[section]`). We need to keep the 1-file distribution format (a single INI file) so extra files should be avoided. However, I'm not sure if custom (non-INI) format will play along with Windows functions for working with INI files.

**Comment by muv1** [comment]
Bounty of $800 for this issue, thank you!

**Comment by muv1** [comment]
https://github.com/ProgerXP/Notepad2e/issues/299

**Comment by ProgerXP** [comment]
@nu8
This took us some time but it should be virtually ready. The test build is attached if you want to check it; below is the description I will later add to the README.

[Notepad2e-LPeg-RC.zip](https://github.com/ProgerXP/Notepad2e/files/4772521/Notepad2e-LPeg-RC.zip)
[pas.zip](https://github.com/ProgerXP/Notepad2e/files/4772539/pas.zip)

---

- LPeg support adds ~400 KiB to the EXE file size. We have added LPeg build configurations to the solution by analogy with ICU versions.
- We have patched Lua to handle Unicode file paths (1557c00). Sadly, there seems to be no other way to load lexers from arbitrary paths reliably.
  - **Warning:** if it doesn't work for you, try simple paths like `C:\lpeg` until we fix this entirely.
- In LPeg versions, a new syntax scheme (F12) appears in the end of the list. This scheme is one for all Lua lexers: when it's selected, LPeg uses its own rules to determine which scheme to apply to this particular file; basically it searches for a file named `EXTENSION.lua` in the INI's `LPegPath` option (under `[Notepad2e]` section) and if not found - shows an error.
- To enable automatic scheme selection open Customize Schemes (Ctrl+F12), select LPeg and enter desired `Associated file name extensions`. Make sure the list doesn't conflict with other schemes (e.g. `pas` in `Pascal/Delphi` and `pas` in `LPeg Lexer`).
- When `LPegPath` is empty (as it is by default) - the scheme appears in the list but LPeg is essentially disabled. `LPegPath` is relative to the INI folder and may contain `%variables%`. Once you define it, on next run Notepad 2e will create several files inside (unless they exist); they are required for LPeg operation but you can modify those files to configure the lexing and/or highlighting colors. 
- Even though the `theme` folder is created, Notepad 2e doesn't support switching LPeg themes.
- We don't provide support for LPeg itself so to see how these lexers are written go to the project's homepage: https://scintilla.sourceforge.io/LPegLexer.html. Pre-made lexers are available from Scintilla 3's source code archive (`lexlua` folder): https://scintilla.sourceforge.io/LongTermDownload.html. Also see the original project's page: https://foicica.com/wiki/scintillua.

---

@cshnik
Remaining tasks:

- The Unicode patch doesn't work as expected, I still get crashes and errors when LPegPath contains Cyrillic symbols.
- Add the description of the patch to Scintilla's patching readme.
- We need a build configuration for ICU+LPeg combined.
- The pascal.lua file you have included is dated 2019 but current Scintilla archive includes pascal.lua with 2020 in the copyright - same for lexer.lua and default.lua. Is your copy outdated? If so then update both files included with the EXE.

**Comment by nu8** [comment]
> This scheme is one for all Lua lexers: when it's selected, LPeg uses its own
> rules to determine which scheme to apply to this particular file; basically
> it searches for a file named `EXTENSION.lua` in the INI's `LPegPath` option
> (under `[Notepad2e]` section) and if not found - shows an error.

I download this:

https://sourceforge.net/projects/scintilla/files/scintilla/3.11.2/scintilla3112.zip

then put `lexlua\nim.lua` in same folder as Notepad2e. Then I choose View,
Customize Schemes, LPEG Lexas, Associated filename extensions, `nim`. I then
load `a.nim`, but `Default Text` is still reported. It seems `LPegPath` is not
set by default. Perhaps it should be?

**Comment by ProgerXP** [comment]
> It seems LPegPath is not set by default

This is what I have written: `When LPegPath is empty (as it is by default)`

> Perhaps it should be?

It can't have any default value because LPeg won't function without this folder and Notepad 2e cannot create this folder in arbitrary location. For example, if Notepad2e.exe is in Program Files then it can't just create something there, it's not writable by regular users.

Therefore `LPegPath` is something that the user should explicitly specify.

**Comment by nu8** [comment]
`LPegPath` should just be the same folder as the executable, or alternatively `lexlua` folder in executable directory. I am still willing to do bounty, but current solution is not ideal. Some default should be set, then user can change as need be.

**Comment by ProgerXP** [comment]
As I have pointed out, we will not make any default for LPegPath because there are no guarantees where Notepad2e.exe resides. LPeg is not zero-configuration and would not function even if there were a preset value for this setting. 

> Some default should be set, then user can change as need be.

In most cases the EXE is in a read-only location, then why bother with the default if user has to change it anyway? 

Besides, Lua allows executing arbitrary code and the user must explicitly ack this by configuring LPegPath so that `*.lua` stuff that happens to be in whatever default this option would have does not get executed by surprise.

**Comment by nu8** [comment]
> In most cases the EXE is in a read-only location, then why bother with the
> default if user has to change it anyway?

The most likely value is going to be:

~~~
C:\Program Files\Notepad2e
~~~

So it makes sense to set this as default, then user can change if need be. Also
having a default makes a better user experience. If the default is correct,
then user has to change nothing. Even if default is not correct, its better for
the user, because they can just open INI and search for LPEG. If no default,
then user has to try to figure out what setting to add.

Sorry, but this is important point to implement. If default is not set, then
only half bounty can be considered.

**Comment by ProgerXP** [comment]
> the default is correct, then user has to change nothing. 

User still has to figure where to find LPeg lexers because Notepad 2e doesn't include any. 

> C:\Program Files\Notepad2e

How Notepad 2e will create LPeg files there? It's started as a regular user.

Or are you suggesting that the user will have to put the correct files from Scintilla's source archive, including themes, into the correct folders prior to starting Notepad 2e because the latter cannot write to Program Files? Is it really more intuitive?

Otherwise, if your intention is to redistribute a preconfigured Notepad 2e version with lexers then I don't see why you simply don't set LPegPath to whatever value is used in your case.

> Even if default is not correct, its better for
> the user, because they can just open INI and search for LPEG. 

Notepad 2e writes `LPegPath=` to the INI so they can search for "lpeg" no matter if it has the default or not.

@cshnik: actually no, it doesn't right now but it should write the current value to the INI on F7. It's unaffected by Reload From Disk.

> If no default, then user has to try to figure out what setting to add.

Are you trying to prove that the user can avoid reading the documentation at all? It's impossible. Here's another point: file names in Scintilla's archive are scheme names while in LPegPath they are extensions; even if one knew where to get lexlua, they'd still need to learn about renaming files. 

And apart from all that, what about security implications of allowing to execute Lua code via Notepad 2e?

You seem to ignore my arguments.

> Sorry, but this is important point to implement. If default is not set, then only half bounty can be considered.

I see. Then don't bother, I will not consider any more issues from you. We did the absolute bulk of the job that took significantly more time than your bounty, and you invalidate it because you don't like some default. 

Either stop forcing your particular use case or find somebody else who will develop it to your liking.

**Comment by nu8** [comment]
> How Notepad 2e will create LPeg files there? It's started as a regular user.

Another option would be to include the setting, but commented. Example here:

https://github.com/alacritty/alacritty/blob/master/alacritty.yml

> Notepad 2e writes `LPegPath=` to the INI so they can search for "lpeg" no
> matter if it has the default or not.

After my changes before, it looks like this:

~~~
[LPEG]
FileNameExtensions=nim
Default=
~~~

but if you just save the default settings, `LPEG` will not be found. Could be
set like this:

~~~
; [LPEG]
; Default=C:\Program Files\Notepad2e
~~~

**Comment by ProgerXP** [comment]
> but if you just save the default settings, LPEG will not be found. Could be

Yes, saving this option is missing in the test build, I have mentioned this:

>> @cshnik: actually no, it doesn't right now but it should write the current value to the INI on F7. It's unaffected by Reload From Disk.

In the final version LPegPath will be present in the INI file after you Save Settings Now (F7). I am also going to include a comment about LPegPath in the default Notepad2e.ini mentioning that it only has effect in LPeg-enabled builds and how to configure it. But it will remain empty by default.

**Comment by ProgerXP** [comment]
Now that I think about it, it's a good idea if we show a message on start-up in LPeg builds saying that LPegPath is not configured (empty). The message will have "don't show again" flag as other Notepad2 messages.

**Comment by nu8** [comment]
Another option would be: if LPEG is not correctly set, then show a popup like this:

~~~
Warning: LPEG not set. See below for example:
https://github.com/ProgerXP/Notepad2e/blob/master/bin/Notepad2e.ini
~~~

**Comment by cshnik** [comment]
> * The Unicode patch doesn't work as expected, I still get crashes and errors when LPegPath contains Cyrillic symbols.

Cannot reproduce. Tested on WinXP x64/Windows 7. Please provide your INI file if the problem remains.

> * Add the description of the patch to Scintilla's patching readme.

Done.

> * We need a build configuration for ICU+LPeg combined.

"Release ICU LPeg" configuration added.

> * The pascal.lua file you have included is dated 2019 but current Scintilla archive includes pascal.lua with 2020 in the copyright - same for lexer.lua and default.lua. Is your copy outdated? If so then update both files included with the EXE.

Done.

> @cshnik: actually no, it doesn't right now but it should write the current value to the INI on F7. It's unaffected by Reload From Disk.

Fixed.



> Now that I think about it, it's a good idea if we show a message on start-up in LPeg builds saying that LPegPath is not configured (empty). The message will have "don't show again" flag as other Notepad2 messages.

> Warning: LPEG not set. See below for example:
> https://github.com/ProgerXP/Notepad2e/blob/master/bin/Notepad2e.ini

Done.

**Comment by ProgerXP** [comment]
> it should write the current value to the INI on F7

My bad, we can't just write it because it's expanded and changes the user-defined value that may be relative. Instead, let's only write it if there is no such key in the INI yet (this can be checked by giving IniGetString a known unique lpDefault).

> show a message on start-up in LPeg builds saying that LPegPath is not configured (empty). 

This message's text isn't wrapped for some reason (compare with IDS_ASK_ENCODING for example).

If LPeg was disabled due to any error (empty path, unavailable path) then no more related errors should appear, LPeg support should be simply disabled. This means n2e_GetLuaLexerName should do nothing on !bLPegEnabled (currently it shows an error about non-existing lexer every time another file is opened). The MsgLPegNotSet should be also shown if !bLPegEnabled, not only on empty path.

---

@nu8 [Notepad2e.zip](https://github.com/ProgerXP/Notepad2e/files/4791124/Notepad2e.zip)

**Comment by cshnik** [comment]
> My bad, we can't just write it because it's expanded and changes the user-defined value that may be relative. Instead, let's only write it if there is no such key in the INI yet (this can be checked by giving IniGetString a known unique lpDefault like `L"\1"`).

Fixed. Original value is always re-saved to INI without applied changes.

> This message's text isn't wrapped for some reason (compare with IDS_ASK_ENCODING for example).

Fixed.

> If LPeg was disabled due to any error (empty path, unavailable path) then no more related errors should appear, LPeg support should be simply disabled. This means n2e_GetLuaLexerName should do nothing on !bLPegEnabled (currently it shows an error about non-existing lexer every time another file is opened). The MsgLPegNotSet should be also shown if !bLPegEnabled, not only on empty path.

Fixed.

**Comment by ProgerXP** [comment]
@nu8 Should we expect the bounty?

**Comment by nu8** [comment]
Do you have a test build?

**Comment by ProgerXP** [comment]
It was merged into master so yes, in the usual place: https://proger.me/notepad2e/binaries/

**Comment by nu8** [comment]
So following my own instruction here:

https://github.com/ProgerXP/Notepad2e/issues/251#issuecomment-643434891

everything works as expected. However it still requires manual setting of the
`LPegPath`. The default `Notepad2e.ini` offers this:

~~~ini
; For LPeg versions only. WARNING: enables code execution in this location!
; See for details: https://github.com/ProgerXP/Notepad2e/#lpeg
LPegPath=
~~~

but the INI does not offer a default value, even a commented default value.
Further, I dont see a suggestion here:

https://github.com/ProgerXP/Notepad2e/#lpeg

of what a default value would even look like. In the end, I got it working with:

~~~ini
LPegPath=lexlua
~~~

but users shouldnt be made to go through this guesswork. The default INI should
look similar to this:

~~~ini
; For LPeg versions only. WARNING: enables code execution in this location!
; See for details: https://github.com/ProgerXP/Notepad2e/#lpeg
; LPegPath=lexlua
~~~

that way it takes safe of any safety concern, but makes it easy for person to
get started. They only need to uncomment, and optionally change the default
value.

**Comment by ProgerXP** [comment]
> that way it addresses any safety concern, but makes it easy for person to get
started. They only need to uncomment, and optionally change the default value.

Sounds good to me. d306a46

**Comment by ProgerXP** [comment]
@nu8 Judging by absence of any feedback I assume we're not going to see this bounty paid.

**Comment by nu8** [comment]
Please provide payment info

**Comment by ProgerXP** [comment]
Same as last time: https://proger.me/rFq9u6z8nQmw2ZSo831Q.txt

**Comment by nu8** [comment]
ok done, I subtracted the Paypal fee this time, because honestly I am kind of done with this whole thing. I dont even use Notepad2 anymore, I use Gvim, but I stand by my offer

**Comment by ProgerXP** [comment]
Thanks a lot for keeping your word. We basically worked on this only because of your request. 

I have updated the README to reflect this donation.

**Comment by ProgerXP** [comment]
@cshnik If we don't need the branch anymore, delete it.

**Comment by cshnik** [comment]
> @cshnik If we don't need the branch anymore, delete it.

Done.
