### ISSUE TITLE
Rework/remove n2e_Alloc/Free/Realloc

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#253]
Originally from #250.

I know this is a very old code by another developer but since we are using it, it needs to be fixed. First, I don't see why we need such wrappers around C's malloc/etc at all. Moreover, their similarity is misleading:

- Why iAllocCount? To protect against nested calls (alloc, alloc, free, free)? 
- n2e_Alloc() seems to be designed for strings (hence `sizeof(WCHAR)` and `+ 1` for NULL) - however, `n2e_Realloc()` isn't! 

In my opinion, CommonUtils.c should be removed.

**Comment by cshnik** [comment]
I assume these functions were implemented for debugging purposes. At this point I see no reasons to remove these since it still may be very helpful to have current tracing mechanism for memory operations.
Please confirm if you insist on removing of the ``CommonUtils.c``.

**Comment by ProgerXP** [comment]
For debugging these may be simple wrappers around LocalAlloc()/... or malloc()/... See my two points about the risks of the current implementation (iAllocCount, sizeof()). In other words, either they should be removed or their interfaces should exactly conform to standard memory functions.

**Comment by cshnik** [comment]
Changed implementation to conform standard methods.
