### ISSUE TITLE
Edit Word misbehaves on adjacent regions delete

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#257]
1. Create a document with these 5 symbols: `aabab`
2. Select first `a`: `[a]abab`.
3. Press Ctrl+Tab. There are now 3 editable regions: `a` `a` (b) `a` (b).
4. Press `|` - now the document is `||b|b` (still in Edit Mode, first `|` selected).
5. Press Backspace - now the document is `|bb` (and still in Edit Mode).
6. Press `+` - now the document is `+|b+b`.
7. Press Esc - now the document is `a|bab`.

The problem is at step 5: the document must be `bb` because the remaining `|` is an editable region number 2 but for some reason after step 5 it "falls out" from the editing and subsequent modifications no longer affect that region (hence step 6 - `+|bb+` instead of the expected `++b+b`, and step 7 - expected `aabab`).

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Very similar issue so posting here. Create document `aa\\aa\\`, select any `\\`, press Ctrl+Tab and press `\`. As a result, the first symbol (`\` in `\\`) is now outside of the edit region (no colored background).

![sc](https://user-images.githubusercontent.com/1643195/80637610-f848b300-8a67-11ea-930d-e2c054cfc2c7.png)

I noticed this is occurring only if:

1. The region consists of the same symbol
2. You are typing that symbol 

For example: `aabbaabb`, select `aa`, Ctrl+Tab, type `a` - it's now outside of the region.

**Comment by cshnik** [comment]
Cannot Reproduce.
In both cases (Ctrl+Tab/Ctrl+~) edit word works properly.
Please confirm you are using the latest build of the app. If the problem remains please provide video for the issue.

**Comment by ProgerXP** [comment]
[video.zip](https://github.com/ProgerXP/Notepad2e/files/4588098/video.zip)

**Comment by cshnik** [comment]
Fixed.
Please note: "Edit Word" feature was reworked to address specified issue.
These changes caused additional improvements:
1. Fix for incorrect indicator selection (may occur under specific conditions)
2. Fix for incorrect work of Edit-on-line mode for single chars (rare case)
These heavy changes may require additional testing to make sure everything works as expected.

**Comment by ProgerXP** [comment]
Edit mode is no longer committed by moving outside of the edit region.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
New bug:

```
""|
```

1. Ctrl+Shift+Left
2. Ctrl+Tab

```
["][|"]
```

3. Left

```
[|"]["]
```

In other words, caret is now outside of the original edit region (which was around the second `"`). This should not happen (Edit Mode should be committed). As a result:

4. Press any symbol

```
[z|"]["]
```

...the regions are now messed up.
