### ISSUE TITLE
Open/Save dialogs - configurable filters

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#258]
Currently both dialogs display `All files (*.*)`. I have checked the code and it seems this is hardcoded, isn't it?

Need to make this string customizable:

- read the value from the INI (e.g. as a string of form `Caption|*ma.sk|Caption 2|...`) instead of the hardcoded `All files (*.*)`
- the default value for that option is the current `All files (*.*)` (Notepad2 behaviour)
- when an Open or Save dialog is submitted - remember the selected filter 
- when displaying an Open or Save dialog restore previously used filter (if there was none then the first)
- no need to save last used filter to settings (when starting the process default to the first filter)

**Comment by cshnik** [comment]
Please use the following Settings2 INI-section:
> [Settings2]
> FileDlgFilters=DOC Files (*.doc)|*.doc|RTF Files (*.rtf)|*.rtf

``FileDlgFilters`` ini option is used for Open/Save dialogs and is a part of original [Notepad2](http://www.flos-freeware.ch/development-releases/notepad2-FAQs.html).


> * when displaying an Open or Save dialog restore previously used filter (if there was none then the first)

Done.
