### ISSUE TITLE
Ctrl+R - save line until file is reopened/new

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#26]
Currently the Run window is reset each time it opens. Need to have it persistent like HTML tag window we have fixed earlier but it should also reset when a new file is opened or File > New is used.

Also,  when it's executed make current directory = directory of the opened file (right now it seems to be random). This also means that if I have file "c:\path\file.txt" opened and c:\path also has file app.exe then if I type app.exe int the Run box (but no path) the correct program will be called.

**Comment by ProgerXP** [comment]
The input must be reset when file is resaved but it is not. 
* Open `file1.txt`
* Ctrl+R
* Change the input somehow
* OK
* Close the Run window
* File | Save As
* Ctrl+R
* You will get old input value (incorrect)
* Now open any other file
* Ctrl+R
* You will get new value (correct)

**Comment by hacc** [comment]
fixed

**Comment by ProgerXP** [comment]
I get the error saying that Notepad2.exe is not a valid Win32 application.

**Comment by hacc** [comment]
my bad - fixed
