### ISSUE TITLE
Go To dialog - make similar to Find/Replace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#260]
Go To conceptually is very much like Find and Replace but currently there are several differences:

- Go To is modal while Find and Replace are non-modal
- Go To can be displayed on an empty buffer (the menu command is enabled)

Unless there are some specific reasons, Go To should be made non-modal and its menu command and hotkey must be disabled on an empty buffer (as well as other commands in Edit, below Replace Next).

Also, according to #259 these 3 dialogs must be combined in such a way that only one of them is visible (just like currently you can't display both Find and Replace, you shouldn't be able to display both Go To and Find, for example).

**Comment by cshnik** [comment]
Disabled menu command/hotkey for empty buffer.
All other changes are already implemented in #259 .
