### ISSUE TITLE
Math Eval status bar - swap left and right click 

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#261]
Currently left click switches the base, right click copies the number to the clipboard. Swap them so that left click copies, right click switches.

Rationale: some touchpads have no clearly separate left/right buttons and often trigger a mis-click with left button instead of right button. When it happens and the base is switched, it needs 3 more clicks to revert to the old base. The cost of mis-click would be much lower if left click is used to copy to clipboard (this is more frequent operation too).

**Comment by cshnik** [comment]
Done.
