### ISSUE TITLE
Update status bar selection texts

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#262]
After #204 it became confusing which of the two numbers is line, which is byte count. Currently the format is "Sel %d : %d". Make it so: `Sel %d L : %d B` (remember we have several status bar format strings, all relevant should be changed).

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Add `L` to rectangular selection's status text.

**Comment by cshnik** [comment]
Done.
