### ISSUE TITLE
Add submenus to Edit and Settings

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#265]
Edit and Settings grew up very long. Group the following menu commands into their own submenus:

- Edit > `&Clipboard` (add after Encode, before `--`): move all commands from Copy to Swap and also Clear Clipboard
- Edit > `&Find` (add after Clipboard): all from Find to Find Previous Word
- move Edit > Undo, Redo, Go To Last Change and Clear, Select All to above Go To 
- Settings > `Save Setti&ngs` (add in the end, after last `--` after Show Statusbar): Remember Recent Files, Remember Search Strings and last 4 commands (submenu in this order, no `--`)

---

In the end, Edit menu becomes:

- Lines >
- ...
- Clipboard >
- Find >
- `--`
- Undo
- Redo
- Go To Last Change
- Clear
- Select All
- Go To
- Edit Selection
- Edit Selection On Line

Putting submenus on top allows faster mouse access to less used commands like Tabify Selection. I doubt anyone is invoking Undo, Copy or Replace through the menu so they are now going last.

**Comment by cshnik** [comment]
Done.
