### ISSUE TITLE
Unrelated : Need help to get xor+md5sum key for Arctools

### ISSUE THREAD

**Issue by H0R1Z0N** [ProgerXP/Notepad2e#272]
Hi, i am had been trying to find a way to get the key for the latest sonohana game's encryption key for the script but i totally cannot figure out which file i need to md5sum and then xor to get the encrytion key for it. I cannot really progress without it. I know you seem like the only one to having figured out. I know you are also not anymore into VNs community. Sorry for opening an unrelated issues about your old work.

**Comment by ProgerXP** [comment]
Send me an email or leave your address.

**Comment by H0R1Z0N** [comment]
Ok, when you got time, please send an email to "Broken.Dragon.TL{@}gmail.com" without the quote and {}.
