### ISSUE TITLE
Find/Replace - add hints

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#274]
Add standard Windows hints to these buttons:

- Find Next (of Find and Replace) - `Select match (F3, Enter), Select from start (Ctrl+Enter), Select until (F2)`
- Find Previous (of Find and Replace) - `Select match (Shift+F3), Select until (Shift+F2)`
- Replace - `Select match or replace and go to next (F4)`

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Add also to:

- Grep - `Keep only matching lines `
- Ungrep - `Remove matching lines`
- Transform backslashes (see #292) - `Replaces escape sequences: \a \b \f \n \r \t \v \xhh \uhhhh`

**Comment by cshnik** [comment]
Done.

**Comment by cshnik** [comment]
Refixed.
