### ISSUE TITLE
Find/Replace > Shift+F3 - do not select-to

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#275]
This seems to be a bug in Notepad2: 

- F3 selects the next match
- **Shift+F3 selects the previous match**
- F2 selects from current position to the next match
- Shift+F2 does the same but backwards

However, currently Shift+F3 and Shift+F2 do the same thing if called from within the dialog (both Find or Replace work the same).

**Comment by cshnik** [comment]
Fixed.
