### ISSUE TITLE
Open Next/Previous - use current dialog filter

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#277]
#43 is currently using `*` mask to create the file list that it traverses (`n2e_OpenNextFile`). #258 implemented remembering of last used open/save dialog filter (`iOpenSaveFilterIndex`). Make it so that Open Next/Previous now use this filter instead of the hardcoded `*`. This will allow traversing only files matching the filter which was used last.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
> `if (psz[0] == L'*')`

This makes an assumption that filters start with `*` but this is not necessary so. Valid filters like `?foo.*` or `foo.*` won't be recognized. You should count `\0` pairs instead.

**Comment by cshnik** [comment]
> This makes an assumption that filters start with `*` but this is not necessary so. Valid filters like `?foo.*` or `foo.*` won't be recognized.

Fixed.

> If there was a misunderstanding: I meant that szFileFilter should receive the entire filter string (between two `|` or `\0`), not part of that string. For example, for `foo|*;*;*|bar|?;?;?` with iOpenSaveFilterIndex = 2 it should take `?;?;?`, not a single `?`.

Done. But there is a limitation:
1. Multiple file type strings (``*.txt;*.doc``) work for Open/Save dialogs.
2. Multiple file type strings are not supported by [FindFirstFile](https://stackoverflow.com/questions/8780917/findfirstfile-multiple-file-types).
