### ISSUE TITLE
ScrollYCaretPolicy to affect Go To Last Change

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#279]
Respect `ScrollYCaretPolicy` (#41) when calling Go To Last Change.

**Comment by cshnik** [comment]
Duplicate to #97.

> Scintilla has no proper cursor position adjustment when applying undo/redo commands.

``Go To Last Change``-handler:

```
case ID_EDIT_UNDO_REDO:
    SendMessage(hwndEdit, SCI_UNDO, 0, 0);
    SendMessage(hwndEdit, SCI_REDO, 0, 0);
    break;
```

**Comment by ProgerXP** [comment]
It's not exactly a duplicate because here I'm not talking about wrong caret position but about wrong scrolling. But I see what you mean - when I do Undo or Redo the caret is always either on first or last visible line regardless of ScrollYCaretPolicy. Can this be fixed, even potentially? I.e. when Undo or Redo occurs and document area is scrolled - that ScrollYCaretPolicy margin is effective (like with Find and other commands).

**Comment by cshnik** [comment]
> I.e. when Undo or Redo occurs and document area is scrolled - that ScrollYCaretPolicy margin is effective (like with Find and other commands).

Fixed. Scroll position get adjusted after applying "Go To last Change" command.
