### ISSUE TITLE
Enclose Selection - add links with quotation marks

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#280]
Alt+Q, add links on the bottom (horizontally) similar to Alt+M with 16 symbols from a text file in #254. Each link works just like in Alt+M, inserting or replacing the selection of the currently focused input.

However, it may be necessary to increase the font size and/or use a different font face because these symbols are hard to distinguish. It will be clear once implemented.

I assume this task is easy; if not tell me and we'll postpone it.

**Comment by cshnik** [comment]
Done.
![image](https://user-images.githubusercontent.com/8019354/76121047-64d5a180-6025-11ea-9a00-93549bca8007.png)

**Comment by ProgerXP** [comment]
Too much code to support on-hover cursor. In About, Find/Replace/Go To we are using `CONTROL ... "SysLink"` which is handing it automatically - can't this be done with Modify Lines and Enclose Selection too? If no then let's remove the on-hover support code for both this dialog and Modify Lines (`EditModifyLinesDlgProc`), it's not essential. The blue color is enough.

> However, it may be necessary to increase the font size and/or use a different font face 

Let's use `Georgia` instead of the default dialog font face.

**Comment by cshnik** [comment]
![image](https://user-images.githubusercontent.com/8019354/76455013-f5d2c100-6407-11ea-88b3-c3f7346470a7.png)
Please confirm if current solution with ``syslink`` controls works fine and I'll implement corresponding changes for Modify Lines dialog.

**Comment by ProgerXP** [comment]
1. In my XP (default settings) links are cropped from the bottom as if their height was too small.
2. As far as I understand, you are tracking the focused link (dwFocusID) but does adding more code to support it make sense given that it's not possible to select any link with Tab anyway (Tab doesn't select them)? 

In general it works as expected. Are there any drawbacks to using Syslink? It doesn't require much support code and also adds the dashed outline on focus which is a plus.

**Comment by cshnik** [comment]
> 1. In my XP (default settings) links are cropped from the bottom as if their height was too small.

Fixed.

> 1. As far as I understand, you are tracking the focused link (dwFocusID) but does adding more code to support it make sense given that it's not possible to select any link with Tab anyway (Tab doesn't select them)?

dwFocusedID is used to track last active ``edit`` control which will be updated after click on ``syslink``.
Tab selection for these ``syslink`` controls is actually useless since click on `em will always update only last ``edit`` (dwFocusedID will always refer to "Insert after selection"-input).

> Are there any drawbacks to using Syslink?

I see no drawbacks. Current implementation works very close to original one.

**Comment by ProgerXP** [comment]
> In my XP (default settings) links are cropped from the bottom as if their height was too small.

This was fixed partially: bottom links are less cropped (but still no underline visible and bottom dotted outline is invisible too). Top links were not fixed at all (please see my previous screenshot).

**Comment by cshnik** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/8019354/76556852-e9646c00-64cc-11ea-9506-d3e529c59cdf.png)
PS My WinXP refused to display some quote characters.

**Comment by ProgerXP** [comment]
>  PS My WinXP refused to display some quote characters.

XP needs to have support for Asian languages installed separately. Later Windows have it installed by default.
