### ISSUE TITLE
Add to Favorites - selection mode - add /m /-m

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#282]
Add two new radio buttons to #249:

- `Fi&rst substring`
- `Las&t substring`

They create an LNK like Current line/selection but using either `/m` or `/m-` switch. Because Windows command-line quoting rules are strange, these radio buttons are disabled if any of this is met:

- rectangular selection
- empty selection 
- selection contains `"` or non-printable symbols (such as line breaks)
- selection is too long

You can determine more limitations on last two points.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
> ` (wcspbrk(lpParams->pszCurrentSelection, L" \t\r\n\"") != NULL))`

No need to forbid the space - simply wrap the parameter in `"`. As for `\t` - yes, it's invalid, I doubt LNKs can handle it.

**Comment by cshnik** [comment]
Fixed. Space character is now allowed.

**Comment by ProgerXP** [comment]
1. Make radio buttons' click area last until the end (see how it's done in Windows, e.g. Folder options in Explorer).
2. Update radio button texts to this:

```
"&First line"
"L&ast line (/g -1)"
"&Current line (/g)"
"Current &selection (/gs)"
"Fi&rst substring (/m)"
"Las&t substring (/m-)"
```

**Comment by cshnik** [comment]
Done.
However even M$ violates this layout "rule"
![image](https://user-images.githubusercontent.com/8019354/77945452-dfbf6e80-72ea-11ea-9d4d-03f318120056.png)

**Comment by ProgerXP** [comment]
>  However even M$ violates this layout "rule"

They may be sloppy about precise area length but at least in general they make all checkboxes wider than their text.
