### ISSUE TITLE
Visual Brace Matching - handle < >

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#283]
It looks like `< >` were artificially excluded from Visual Brace Matching because it's the only pair of Unwrap Brackets that isn't highlighted.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
With other types of brackets, positioning caret after the closing bracket does highlighting. However, for `>` this doesn't happen. Compare:

```
()|
<>|
```

**Comment by cshnik** [comment]
Fixed.
But strange thing here is that original Notepad2 code use all types of brackets, while [initial commit](https://github.com/ProgerXP/Notepad2e/blob/cf2f1d99ad5895b0b50f846533aace1d3aa9270e/src/Notepad2.c#L3200) in this repository has missing ``<>``:

```
if (StrChrA("()[]{}",c))
   iBrace2 = (int)SendMessage(hwndEdit,SCI_BRACEMATCH,iPos,0);
```

**Comment by ProgerXP** [comment]
>  But strange thing here is that original Notepad2 code use all types of brackets, while initial commit in this repository has missing `<>`

Huh! That must be a present from the first developer. I did compare the code with Notepad2 sources but due to reformatting it was exhausting and I could miss it.

Can we somehow perform a reliable comparison of our initial code against Notepad2? Maybe it's not the only thing that is missing.

**Comment by cshnik** [comment]
> You are mistaken - Notepad2 doesn't handle `<>`

You are right.

Do we need any other changes to address this issue?
