### ISSUE TITLE
Improve selection/word highlighting

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#286]
See duplicates:

- #211 
- #246 
- #248 (deleted; reposted as #285)
- #255

**Comment by ProgerXP** [comment]
.@Progress1
@muv1
@cup
@fdncred
I am reviewing the issues you have previously opened to consolidate the requests in one place. Comment if my description below is missing something you want to see in the ideal case. We might implement it near the end of March.

1. Make `Highlight Current Word` separate from Edit Word functionality. Disabling the former should not disable the latter, i.e. Ctrl+Tab should be always available regardless of any setting since it doesn't incur any performance penalty until explicitly invoked.
2. Rework boolean `Highlight Current Word` setting into `Highlight Current Selection` with values (submenu):
  - Disabled - no word/selection highlighting (Edit Word still works)
  - Word - for empty and non-empty selection, highlight case-INsensitive word at cursor
  - Selection - highlight nothing for empty selection, else highlight case-sensitive substrings
  - Word and Selection - for empty selection behave as Word above, for non-empty - as Selection
  - Word If No Selection - for empty selection behave as Word, else highlight nothing
  - in any case, empty and non-empty selection highlighting are using the same INI styles (none, Page, Single - https://github.com/ProgerXP/Notepad2e#current-word-highlighting)
  - the default is `Word and Selection`
3. Add new INI setting (not in GUI) to remove the restriction on Edit Word to edit only one screen (default is to edit only visible lines, i.e. current behaviour). If changed, Ctrl+Tab edits occurrences of word/substring in the entire document. @fdncred
4. Memo: re-check if `MaxSearchDistance` actually works (must default to 96 KiB). There were some issues before (#53). If `MaxSearchDistance` works then confirm that the issue is caused by something else.

**Comment by fdncred** [comment]
Bullet 3 will address my issue. Thanks!

**Comment by muv1** [comment]
>     1. Make `Highlight Current Word` separate from Edit Word functionality. Disabling the former should not disable the latter, i.e. Ctrl+Tab should be always available regardless of any setting since it doesn't incur any performance penalty until explicitly invoked.

This doesnt really apply for my usage, as I prefer selection over word, but
perhaps this change could be a roundabout way of getting what I need.

>     * Disabled - no word/selection highlighting (Edit Word still works)

Not useful for me, but will be useful to others.

>     * Word - for empty and non-empty selection, highlight case-INsensitive word at cursor

Not useful for me, but will be useful to others.

>     * Selection - highlight nothing for empty selection, else highlight case-sensitive substrings

Exactly what I need

>     * Word and Selection - for empty selection behave as Word above, for non-empty - as Selection

Not useful to me

>     * Word If No Selection - for empty selection behave as Word, else highlight nothing

Not useful to me

>     * in any case, empty and non-empty selection highlighting are using the same INI styles (none, Page, Single - https://github.com/ProgerXP/Notepad2e#current-word-highlighting)

I would like to customize the highlighting, but only as far as
"no highlighting" versus "highlighting" so whatever style chosen is used for
any word/selection stuff. Anything beyond that might be welcome but not needed.

>     * the default is `Word and Selection`

Default can be whatever you want, as long as can be changed via options and/or
INI.

>     1. Add new INI setting (not in GUI) to remove the restriction on Edit Word to edit only one screen (default is to edit only visible lines, i.e. current behaviour). If changed, Ctrl+Tab edits occurrences of word/substring in the entire document. @fdncred

I dont use Edit word, but other editors (and I would hope this editor), when
using selection it highlighting matches in the entire document as default.
This could be configurable, but I think most people would expect and/or want
entire document as the default, even in the face of performance hit.

>     2. Memo: re-check if `MaxSearchDistance` actually works (must default to 96 KiB). There were some issues before (#53). If `MaxSearchDistance` works then confirm that the issue is caused by something else.

Again I am in favor of defaulting to entire document, but if thats not the case
its fine as long as entire document is an option and/or configurable.

**Comment by cshnik** [comment]
> 1. Make `Highlight Current Word` separate from Edit Word functionality. Disabling the former should not disable the latter, i.e. Ctrl+Tab should be always available regardless of any setting since it doesn't incur any performance penalty until explicitly invoked.

Done.

> 2. Rework boolean `Highlight Current Word` setting into `Highlight Current Selection` with values (submenu):
> 
> * Disabled - no word/selection highlighting (Edit Word still works)
> * Word - for empty and non-empty selection, highlight case-INsensitive word at cursor
> * Selection - highlight nothing for empty selection, else highlight case-sensitive substrings
> * Word and Selection - for empty selection behave as Word above, for non-empty - as Selection
> * Word If No Selection - for empty selection behave as Word, else highlight nothing
> * in any case, empty and non-empty selection highlighting are using the same INI styles (none, Page, Single - https://github.com/ProgerXP/Notepad2e#current-word-highlighting)
> * the default is `Word and Selection`

Done.

> 3. Add new INI setting (not in GUI) to remove the restriction on Edit Word to edit only one screen (default is to edit only visible lines, i.e. current behaviour). If changed, Ctrl+Tab edits occurrences of word/substring in the entire document. @fdncred

``EditSelectionUnbounded`` option added to ``Notepad2e`` INI section. Default is 0.
Set to 1 to enable editing in the entire document.

> 4. Memo: re-check if `MaxSearchDistance` actually works (must default to 96 KiB). There were some issues before (#53). If `MaxSearchDistance` works then confirm that the issue is caused by something else.

`MaxSearchDistance` value is used to set the text range for scan in document when detecting whether previous word occurrence is visible or not:

```
    // 2 first words
    {
      ttf1.chrg.cpMin = max(0, ttf.chrg.cpMin - iMaxSearchDistance);
      ttf1.chrg.cpMax = min(len, ttf.chrg.cpMin + iMaxSearchDistance);
    }
    ttf1.lpstrText = (LPSTR)word;
    res = SendMessage(hwndEdit, SCI_FINDTEXT, search_opt, (LPARAM)&ttf1);
    bPreviousMatchIsVisible = ttf1.chrgText.cpMin >= ttf.chrg.cpMin && ttf1.chrgText.cpMin < ttf.chrg.cpMax;
```

This affects the type of indicator applied for the word.
The actual reason of the "issue" described in #53 is: word highlight logic is applied starting from the very first visible line on screen, but not actual caret position. It is impossible to catch the limits of the feature using (mouse) scrolling since highlighting will restart after every scroll.

```
      lstart = SendMessage(hwndEdit, SCI_GETFIRSTVISIBLELINE, 0, 0);
      lstart = (int)SendMessage(hwndEdit, SCI_DOCLINEFROMVISIBLE, lstart, 0);
```

> 5. When entering Edit Mode, display a hint like in #274 but near the caret, with text `Editing %d occurrence%s` (last `%s` = `s` if `%d` is not 1).

Done. Added tooltip at the right bottom corner of the selection.

**Comment by ProgerXP** [comment]
Bug: pressing Escape during active Edit Word puts caret to the beginning of the document.

> `EditSelectionUnbounded` option added to `Notepad2e` INI section. Default is 0.
Set to 1 to enable editing in the entire document.

Let's rename it to `EditSelectionScope` because there may be other options in the future, e.g. limiting to line only (as with Ctrl+backtick).

> .5. When entering Edit Mode, display a hint like in #274 but near the caret, with text `Editing %d occurrence%s` ***(last `%s` = `s` [only] if `%d` is not 1)***. 

Please pay attention to the part in bold.

Let's also extend the text a little: `Editing %d occurrence%s (%s)` where last `%s` is either of:

- if using Ctrl+backtick - always `on line`
- else `visible only` or `document-wise` depending on `EditSelectionScope`

> `MaxSearchDistance` value is used to set the text range for scan in document when detecting whether previous word occurrence is visible or not:

Does it affect Edit Word in any way? It seems that with EditSelectionUnbounded = 1 and MaxSearchDistance = 1 Edit Word affects less values than reported by Replace. 

There may be a related bug, try this: disable highlighting, set those 2 settings, put a caret on some word and press Ctrl+Tab or Ctrl+backtick - Edit Word mode will not be initiated but that word will gain a permanent red outline.

---


@Progress1
@muv1
@cup
@fdncred
The bulk of the discussed features is implemented, you are welcome to test it via the new submenu: View > Highlight Current Selection and the GUI-less `EditSelectionUnbounded` option under `[Notepad2e]` in the INI file.

**Comment by muv1** [comment]
Here is my feedback:

First, thank you for doing this! Seems much work went into it, so I appreciate
it. Looks like you wanted a comprehension solution, rather than adding things
one by one. Personally I prefer the iterative approach, as you can make some
people happy quickly, rather than everyone happy after a longer time. But at any
rate its done now so all good.

As far as the actual changes, its seems many options to choose from now, but I
guess that makes sense as each person will have their own preference.

Something that bothers me, if you click something that is checked, it should
uncheck it. Instead user is required to select the DISABLED option. I think it
would be better to just remove the DISABLED option, then if user clicks
something that is already checked, that implicitly means DISABLED and everything
is then unchecked. Thats a personal preference though, the current menu is easy
enough once you understand it.

As far as the different options, I want SELECTION and not WORD, so I dislike
all options except SELECTION. The SELECTION option is perfect for me.

Couple of questions. Since I have the good feature now, am I able to style the
SELECTION option? I prefer block coloring over the "border" style.

Finally, in this time since you were working on the feature, I started using
Vim as alternative. One feature I like from Vim is that it also has the
SELECTION option, but you can keep matches around the document highlighted while
even editing the document. While with Notepad2e, as soon as you click somewhere
to edit, the highlights go away.

If its not possible I understand, its just nice to have in some cases. Thank you
again!

**Comment by ProgerXP** [comment]
> Looks like you wanted a comprehension solution, rather than adding things
one by one. Personally I prefer the iterative approach, as you can make some
people happy quickly, rather than everyone happy after a longer time. 

We already had several users request word highlighting-related features so it made sense to take them into account at once saving time instead of coming back to this over and over.

Does your bounty promise still hold?

> Something that bothers me, if you click something that is checked, it should
uncheck it. 

Indeed. See #300.

> Since I have the good feature now, am I able to style the
SELECTION option? I prefer block coloring over the "border" style.

Yes, via the INI: https://github.com/ProgerXP/Notepad2e#current-word-highlighting - see the ...SelectionColor option. However, note that it makes the text somewhat harder to read (so also see the ...SelectionAlpha option) but this is how Scintilla draws it, we can't change it.

If you want highlighting to look the same regardless how many times the word/substring appears in the document then set all 3 group of styles (none, Page... and Single...) to the same value. 

> Finally, in this time since you were working on the feature, I started using
gVim as alternative. 

I'm also a G/Vim user myself and we've borrowed a few features from there (like Ctrl+Alt|Shift+Enter for `O`/`o`, Ctrl+J for `J` and [Shift+]Ctrl+8 for `*`).

> One feature I like from gVim is that it also has the
SELECTION option, but you can keep matches around the document highlighted while
even editing the document. While with Notepad2e, as soon as you click somewhere
to edit, the highlights go away.

Are you talking about `set hlsearch`?

Our highlighting is not sticky meaning it depends on current caret position or selection. Technically it should not take long to code persistent highlighting which you dynamically change via some hotkey (say Ctrl+Shift+backtick to add, Ctrl+Alt+backtick to remove). I'm not sure how it will impact performance though. Is this what you have in mind?

**Comment by muv1** [comment]
> Does your bounty promise still hold?

Of course. Just let me know where to send to! Also note I made another issue:

<https://github.com/ProgerXP/Notepad2e/issues/299>

and the same bounty is offered there too.

> Are you talking about `set hlsearch`?
>
> Our highlighting is not sticky meaning it depends on current caret position or
> selection. Technically it should not take long to code persistent highlighting
> which you dynamically change via some hotkey (say Ctrl+Shift+backtick to add,
> Ctrl+Alt+backtick to remove). I'm not sure how it will impact performance
> though. Is this what you have in mind?

Yes correct, here is my config:

<https://github.com/muv1/hearth/blob/master/gvim/_gvimrc>

The important lines are:

~~~vim
set hlsearch
nmap h :nohlsearch
~~~

as gVim doesnt really offer an easy way to turn off the highlighting, I made my
own mapping. Again this is a small issue, but if it was implemented that would
be great.

**Comment by ProgerXP** [comment]
> Of course. Just let me know where to send to!

What is better for you, PayPal or wire transfer?


---

I've created #301 for your request. It might be useful for me although if not for you I'd probably not miss it. We'll see if it's simple to implement.

```
func Enter()
   " If cursor is beyond indent, insert newline and indent to match previous
   " indent. If cursor is at or before indent, insert newline and indent to
   " match previous cursor location.
   let a_cur = Cursor()
   let n_min = min(a_cur)
   return "\n" . repeat("\t", n_min / g:n_tab)
endfunc
```

Have you considered `set ai`/`set si`/`set cin` instead?

> `nmap h :nohlsearch`

FYI, it can be done with shorter `:noh` which I do use.

**Comment by muv1** [comment]
> What is better for you, PayPal or wire transfer?

I think PayPal is good.

> I've created #301 for your request. It might be useful for me although if not
> for you I'd probably not miss it. We'll see if it's simple to implement.

Thank you. Likely I will put bounty, but my focus now is on user defined lexers.

> Have you considered `set ai`/`set si`/`set cin` instead?

I think I tried those, but they were too smart for my liking:

<https://vi.stackexchange.com/questions/22912>

> FYI, it can be done with shorter `:noh` which I do use.

`:noh` is longer than `h` :)

**Comment by ProgerXP** [comment]
> I think PayPal is good.

https://proger.me/rFq9u6z8nQmw2ZSo831Q.txt

If you want to support us again then feel free to send to the same account in the future.

> I think I tried those, but they were too smart for my liking:

I found that it's best to not tamper with default G/Vim behaviour too much, else you end up overriding too many things and it's becoming counter-productive. For me `ai` or `si` work perfectly fine as I tend not to use Enter almost at all (`o` and `O` are much more useful and  convenient).

**Comment by muv1** [comment]
USD ok?

**Comment by ProgerXP** [comment]
> USD ok?

Any currency that's more convenient for you will do.

**Comment by muv1** [comment]
sent

**Comment by ProgerXP** [comment]
Thank you very much for your support!

**Comment by muv1** [comment]
Once Lua LPeg Lexers is finish, I will donate same amount again. Thank you for everything!

**Comment by muv1** [comment]
@ProgerXP can you please list me on a THANKS page somewhere? This way I can link to it so that other projects know I am serious about donating.

**Comment by ProgerXP** [comment]
@muv1 Sure, in fact I was thinking of the same thing. How do you want to be mentioned? Home page, etc.?

**Comment by muv1** [comment]
The readme would be nice, but up to you. it can just be all the way down at the bottom or wherever. it should be its own section, so you can link to it directly, so like this markup:

~~~
## Patrons (or sponsors)

thanks to those or have donated to the project:

@SundayMonday (John Smith)
@muv1 (Steven Penny)
~~~

**Comment by ProgerXP** [comment]
Done, you can use this permalink:

https://github.com/ProgerXP/Notepad2e#thanks

**Comment by muv1** [comment]
Looks good! Thank you

**Comment by cshnik** [comment]
> Bug: pressing Escape during active Edit Word puts caret to the beginning of the document.

Fixed.

> Let's rename it to `EditSelectionScope` because there may be other options in the future, e.g. limiting to line only (as with Ctrl+backtick).

Done.

> Also let's add a new menu checkbox command after `---` after last command in View > Highlight Current Selection (similarly to Find > Line Endings) - `Document-Wise &Edit Word` that toggles this INI setting.

Done.

> > .5. When entering Edit Mode, display a hint like in #274 but near the caret, with text `Editing %d occurrence%s` _**(last `%s` = `s` [only] if `%d` is not 1)**_.
> 
> Please pay attention to the part in bold.

Fixed.

> Let's also extend the text a little: `Editing %d occurrence%s (%s)` where last `%s` is either of:
> 
> * if using Ctrl+backtick - always `on line`
> * else `visible only` or `document-wise` depending on `EditSelectionScope`

Done.

> > `MaxSearchDistance` value is used to set the text range for scan in document when detecting whether previous word occurrence is visible or not:
> 
> Does it affect Edit Word in any way? It seems that with EditSelectionUnbounded = 1 and MaxSearchDistance = 1 Edit Word affects less values than reported by Replace.

Edit Word has 2 modes (original behavior):
1. Click on a word, press Ctrl+Tab to run in WORD mode: case-INsensitive, subwords in other words will not changed.
2. Select word/chars, Ctrl+Tab to run in SUBWORD mode: case-sensitive, ALL subwords will be also changed.

Regarding the case: please use SUBWORD mode to directly compare Edit Word with Replace.

> 
> There may be a related bug, try this: disable highlighting, set those 2 settings, put a caret on some word and press Ctrl+Tab or Ctrl+backtick - Edit Word mode will not be initiated but that word will gain a permanent red outline.

Edit Word will never start for a single word in a document (original behavior).

**Comment by ProgerXP** [comment]
> .5. When entering Edit Mode, display a hint like in #274 but near the caret, with text `Editing %d occurrence%s` ***(last `%s` = `s` [only] if `%d` is not 1)***. 

I just noticed the unnecessary complication given that editing can only work on 1 region (#302) - `%d` can never be 1 so no need for the special case. Although since it's already implemented it can be kept, maybe we'll change this logic some time.

>> There may be a related bug, try this: disable highlighting, set those 2 settings, put a caret on some word and press Ctrl+Tab or Ctrl+backtick - Edit Word mode will not be initiated but that word will gain a permanent red outline.

> Edit Word will never start for a single word in a document (original behavior).

The problem was that it didn't start but the outline of "single match in the document" would remain on the word forever even if the caret is moved. However, it doesn't occur in the current version so it must have been fixed.
