### ISSUE TITLE
Add to favourites - append unique suffix

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#290]
There are two similar functions: File > Create Desktop Link and File > Favorites > Add Current File. The only difference is that the first is placing the shortcut on desktop with default options while the second lets you type the file name and choose open mode, then it places it into the customized folder.

However, the first also ensures the file name ends on a unique suffix like `File (2).txt`. It would be useful if Alt+K did the same by setting the initial dialog's input value to a unique name, i.e. with a suffix if a file with the same name already exists in the favourites folder.

Note: the error message that appears after Alt+K on duplicate name remains, i.e. if user deliberately changed the input to a name which is already taken. It's only the initial name that is made unique.

I am adding this to the upcoming release because the unique-suffix function is already implemented so it should be easy to make it work for Alt+K. If there are complications then let me know.

**Comment by cshnik** [comment]
Done.
