### ISSUE TITLE
Find/Select To Matching Brace - depend on caret location

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#293]
Currently, if cursor is adjacent to a bracket, Ctrl+B puts the caret always before `(` or `)` while Shift+Ctrl+B always selects `(...)`.

Add a setting (INI-only) with 3 values. Value 0 - current/legacy behaviour, 1 affects all commands (Ctrl+B and Shift+Ctrl+B), 2 only affects Shift+Ctrl+B keeping current behaviour for Ctrl+B.

- if caret was inside `(` `)` then only the inner part is affected (ignoring the brackets)
- if it was outside `(` `)` then both brackets and the contents are affected

For example (`|` - caret, `[ ]` - selection):

```
document  ctrl+b    shift+ctrl+b
a|(bc)d   a(bc)|d   a[(bc)|]d
a(|bc)d   a(bc|)d   a([bc|])d
a(bc|)d   a(|bc)d   a([|bc])d
a(bc)|d   a|(bc)d   a[|(bc)]d
```

**Comment by cshnik** [comment]
Done. ``FindSelectToMatchingBraceMode`` INI option added.

**Comment by ProgerXP** [comment]
Need to position caret on the opposite side. Compare with the legacy selection:

```
(a)
```

If selecting from the outside, you get either `(a)|` or `|(a)` but if selecting from the inside you always get `|a`, making it impossible to move the caret if needed without resetting the selection.

**Comment by ProgerXP** [comment]
Buffer corruption in UTF-8 mode with Cyrillic characters with this mode enabled:

1. In a new document, enter: `(ффф)`
2. Press Arrow Left: `(ффф|)`
3. Press Ctrl+Shift+B: `([ффф])`
4. Press Backspace or any other key that results in selection being deleted (such as `я`)

As a result, instead of `(|)` you get some random junk character inside the brackets. It only occurs if you select the brackets' contents with Ctrl+Shift+B first. It doesn't occur in ASCII mode.

**Comment by cshnik** [comment]
> Buffer corruption in UTF-8 mode with Cyrillic characters with this mode enabled

Fixed.


> Need to position caret on the opposite side. Compare with the legacy selection:

Please provide actual and expected results for the further work on this issue.

**Comment by ProgerXP** [comment]
>> If selecting from the outside, you get either `(a)|` or `|(a)` but if selecting from the inside you always get `|a`, making it impossible to move the caret if needed without resetting the selection.
>
> Please provide actual and expected results for the further work on this issue.

This comment of mine is no longer valid because second Select To now extends selection (#367).

**Comment by cshnik** [comment]
Added bugfix for scenario:

```
(a[a]) -> [(aa)],  must be ([aa])
```
