### ISSUE TITLE
Double Ctrl+A in Run clears the value

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#298]
1. Ctrl+R
2. Ctrl+A
3. Ctrl+A

Result: the input is now empty.

**Comment by cshnik** [comment]
Cannot Reproduce.
Which OS version is used? Please provide video for the issue.

**Comment by ProgerXP** [comment]
It's definitely still happening for me (Win10) although only on my host system, not in XP. Do you have any idea what can be causing it?

>  Please provide video for the issue.

Simply open any file, press Ctrl+R (run command is selected), then Ctrl+A (run command is *not* selected, caret is put to the end), Ctrl+A again (run command becomes empty). It doesn't happen on unnamed buffers. It also doesn't happen if, after the second Ctrl+A you type something and press Ctrl+A - it works properly.

Maybe the dialog contains `\n` or some other non-printable character that's confusing Windows?

**Comment by cshnik** [comment]
Still cannot reproduce.
Tested on Windows 10 Enterprise 10.0.18362.
Are you using any tweaker tools for Windows OS?
The point is: command edit behavior is managed by OS and is initialized by [SHAutoComplete()](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shautocomplete) API call which may cause different behavior on different machines.

**Comment by ProgerXP** [comment]
Likely caused by something on my system.
