### ISSUE TITLE
Find/Replace - Skip comments mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#303]
2 new radio buttons under Transform backslashes: `Comments:  [X] skip (&Q)  [X] onl&y`. By default none are checked. If `skip` is checked then If a match starts within a comment region then next match is searched, if `only` - the opposite (match not starting within a comment region is skipped).

I suggest determining comments by searching case-insensitive substring "comment" within Scintilla's style name (e.g. `XML Comment`).

If current syntax scheme has no styles with "comment" then disable Skip comments.

This change is both for Find and for Replace.

**Comment by cshnik** [comment]
Done. Please consider the following:
1. Radio buttons without default selection is not a user-friendly UI.
2. Another problem with unset/unchecked radio buttons is: Find dialog should save its state between openings (i.e: open, find, close, open again - set of options remained the same). How user is expected to reset radio to unchecked if he previously used ``skip``/``only`` mode?
3. Newly added options (Lookup in comments: ``always``, ``never``, ``only``) also affect "Find Word"-feature.
4. Grep/Ungrep commands are functional only when using ``always`` mode.
5. I have slightly rephrased text for label/buttons. UI for current implementation is:
<img src="https://user-images.githubusercontent.com/8019354/114935035-e290f100-9e64-11eb-9886-6ddbea76d497.png" width="50%"><img src="https://user-images.githubusercontent.com/8019354/114935013-dd33a680-9e64-11eb-81e9-1542a3bb239d.png" width="50%">

**Comment by ProgerXP** [comment]
> I have slightly rephrased text for label/buttons. 

Just change the word `Lookup` to `Search` for symmetry with "Search String".

> Grep/Ungrep commands are functional only when using always mode.

Grep/Ungrep are using a different mechanism than Find?

**Comment by cshnik** [comment]
> > I have slightly rephrased text for label/buttons.
> 
> Just change the word `Lookup` to `Search` for symmetry with "Search String".

Done.

> > Grep/Ungrep commands are functional only when using always mode.
> 
> Grep/Ungrep are using a different mechanism than Find?

There is no clear understanding how Grep/Ungrep should work with additional filtering.
``always`` - no filtering, use current algorithm.
``never`` - should comments be always excluded or skipped?
``only`` - should anything except comments be excluded or skipped?

**Comment by ProgerXP** [comment]
> There is no clear understanding how Grep/Ungrep should work with additional filtering.

It's simple: "Search comments" affects where Grep/Ungrep look for the match; if "Search comments" prevents them from looking inside comments then all comments are implicitly removed, if it forces to look only inside comments then all non-comments are implicitly removed.

I assume this is simple to implement, if not then we might reconsider it (I don't want to complicate Find logic).

**Comment by ProgerXP** [comment]
Note for users: given Find/Replace are non-modal, it's possible to change syntax Schema while they are opened but this won't update disabled state of new radio buttons. This is a UI issue and it doesn't affect searching (as expected, `only` will never match).

---

@cshnik Find/Replace checkboxes are saved when you do a search but new radio buttons are saved immediately (even if you Close the dialog). Make them uniform.

**Comment by cshnik** [comment]
> It's simple: "Search comments" affects where Grep/Ungrep look for the match; if "Search comments" prevents them from looking inside comments then all comments are implicitly removed, if it forces to look only inside comments then all non-comments are implicitly removed.
> 
> As a side effect, Grep on `.` in Regexp mode and Search comments `never` removes all comments and leaves all code (and comments that are part of a line which has non-comment contents) while in `only` mode it removes code and keeps only comments (and code which is on the same line).

Done.

> Find/Replace checkboxes are saved when you do a search but new radio buttons are saved immediately (even if you Close the dialog). Make them uniform.

Fixed.

**Comment by cshnik** [comment]
Fixed.
