### ISSUE TITLE
Resize statusbar groups

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#304]
Change width of the last group (current scheme) by -65 pixels and add this number of pixels to the first group (`Ln ...`). Keep width of other groups unchanged.

**Comment by cshnik** [comment]
Status bar groups has dynamic size depending the current window size (and content) and are measured in client coordinates. Group 1 had the following limits: 
1. min width: 120 points
2. max width: 1/3 window width

I had increased min width limit to 200 points. Please confirm if it fix the issue.

**Comment by ProgerXP** [comment]
I see absolutely no difference after the change. Width is still the same as in Notepad2.

**Comment by cshnik** [comment]
Fixed.
I have slightly changed the logic for DocPos pane size calculation. Now it has the greater value from:
1. 1/3 width of the status bar
1. The actual DocPos text width

Note: status bar panes size get updated on window resize.

**Comment by ProgerXP** [comment]
> The actual DocPos text width

Problem is that the text may change. Moreover, it's likely to be different on start-up because the position is at the very beginning and hence the text is shorter by 4-5 digits than it can become (`Pos 0` = `Pos 12 345`). I guess for this reason there was a hardcoded long string.

**Comment by cshnik** [comment]
> > The actual DocPos text width
> 
> Problem is that the text may change. Moreover, it's likely to be different on start-up because the position is at the very beginning and hence the text is shorter by 4-5 digits than it can become (`Pos 0` = `Pos 12 345`). I guess for this reason there was a hardcoded long string.
> 
> ![1](https://user-images.githubusercontent.com/1643195/85436707-22af7c00-b592-11ea-838e-a84716ad1192.png)

Fixed.
Status pane width is updated on-the-fly on text change.
