### ISSUE TITLE
Go To Last Change - do not Redo if no Undo

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#306]
This command (Ctrl+Shift+Alt+Z) moves to the place of last change by doing Undo, then Redo. However, if there is no Undo but there is a Redo - don't do Redo:

1. Document with any content, e.g. empty
2. Modify it, e.g. type `a`
3. Ctrl+Z - document is empty
4. Go To Last Change - expected that cursor is repositioned without changes but in addition to that Redo is performed (so document is again `a`)

**Comment by cshnik** [comment]
Fixed.
