### ISSUE TITLE
Math Eval - empty for large selection

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#310]
Seems very similar to #296 but it's probably due to other reasons.

1. Open Notepad2e.ini
2. Select All
3. Observe empty status group with the file size

Expected: obviously, the selected contents is not a valid math expression so the group should remain to be the file size.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Fixed.
