### ISSUE TITLE
Crash when typing "not-"

### ISSUE THREAD

**Issue by Chwinterhoch5** [ProgerXP/Notepad2e#312]
Notepad2e crashes when typing `not-` into the editor at the beginning of a line. This still happens even if some more characters like whitespace and some special characters precede this sequence. However, there is no crash if e. g. a word precedes this sequence. I tested the behavior also with the latest nightly release.

**Comment by ProgerXP** [comment]
Wow, that's true. Even the previous release is affected (but you have to type `not-`, then close the program - it will crash on exit).

**Comment by Chwinterhoch5** [comment]
In my case the program crashes immediately when entering the last character of the sequence `not-` or when adjusting a line where this sequence is somewhere in the middle until a point is reached where this sequence is sufficiently close to the beginning of the line.

**Comment by cshnik** [comment]
Fixed.

**Comment by Chwinterhoch5** [comment]
The latest build works fine. Thank you!

**Comment by ProgerXP** [comment]
This was caused by a mistake in our version of TinyExpr used to Evaluate Math Expressions (that is enabled by default). Thanks for reporting this serious issue.
