### ISSUE TITLE
mouse triple click is suppose to select current line

### ISSUE THREAD

**Issue by kaala** [ProgerXP/Notepad2e#313]
one click move cursor
double click select word
triple click select line

**Comment by ProgerXP** [comment]
https://github.com/ProgerXP/Notepad2e#line-selection-hotkeys

> Triple-click and triple-Ctrl+Space in Scintilla select entire line. Due to their accidental nature they are disabled in Notepad 2e. Full line can still be selected with standard Ctrl+Shift+Space hotkey or by clicking on the line number (gutter).

**Comment by kaala** [comment]
I didn't read through the entire readme.
This is ok, I will use the gutter.
