### ISSUE TITLE
Default charset for styles

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#315]
During recent fixes in specifying default charset in Scintilla (#308) and after Scintilla upgrade, in Japanese locale (tested on XP/7) fonts stopped being monospace. This was fixed in 13d5996920332e0e63aa84bbdd92b5b9b96da2a6, but it made changes to the default style configuration ("Default Style" and "2nd Default Style") and only works on new INI files.

I suggest that instead of adding `charset:0` to those styles, we make it so that `charset:0` is internally added to every `STYLE_DEFAULT` style *unless* there is an existing `charset:` specification (i.e. user has explicitly set a charset for that style). This will avoid having to modify existing INIs. In most cases user wants to use `charset:0` anyway, else font rendering is broken.

**Comment by cshnik** [comment]
Done. ``charset:0`` is now applied for styles related to default lexer.
