### ISSUE TITLE
Split view

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#316]
Research Scintilla features related to split view, i.e. splitting a Notepad2 window into multiple smaller areas that all display different portions of the opened file, with different scroll position and selection.

For example, a window can be split into 3 areas:

```
==================
| Large top area |
|----------------|
| Left  | Right  |
==================
```

User can resize these areas by dragging splitters (thin resizers) between them.

**Comment by cshnik** [comment]
Demo for initial testing purposes:
![image](https://user-images.githubusercontent.com/8019354/100037267-58ec7280-2e34-11eb-93fc-2e16a0a8f515.png)
At this point even basic operations are not supported in the additional views.
Please provide required set of features which should be implemented for these (highlighting/find-search/cursor navigation/etc/all at once?).

**Comment by ProgerXP** [comment]
>  Please provide required set of features which should be implemented for these (highlighting/find-search/cursor navigation/etc/all at once?).

All views should have the same features, they simply duplicate the "main" view except for scroll position and selection that is unique per view. Actions that affect a buffer (e.g. typing, menu commands, etc.) affect last focused view.

**Comment by ProgerXP** [comment]
A great example is Notepad++ - see how their View > Move/Clone Current Document > Clone To Other View command works.

**Comment by ProgerXP** [comment]
Some notes on the implementation (that is nearly finished):

- unlike Notepad++, our split view supports any layout, not only 2 vertical or 2 horizontal, just like vim's `sp`/`vsp`
- the layout is managed using toolbar buttons only (split right, split bottom, delete split) - no hotkeys for now
- view can be resized by dragging the spliiter
- double click on a spliiter makes adjacent views 50% (`^W, =` in vim)
- mouse wheel scrolls the view under cursor or current active view depending on the Windows setting ("Scroll inactive windows when I hover over them", not present in XP)
- most commands (Find, selection, etc.) affect current active view, others affect all views (Font, Charset, etc.)
- it's technically possible to implement layout saving but this isn't useful for me (feedback welcome)
- same note goes for layout flipping (vertical -> horizontal and back)

---

Remaining questions:

- fix repaint bug in XP after deleting last view
- revise minimum view size 
- replace splitter double click with single right-click to simplify if current implementation involves timers

**Comment by cshnik** [comment]
> * added new Style: `Current Line, Inactive View (Color)` (and same style for 2nd Scheme); used when Highlight Current Line is on to paint line background in a view that has no focus

Works when ``HighlightLineIfWindowInactive`` option is ON.

**Comment by ProgerXP** [comment]
Enhancements:

- position caret in the new view on the line number where the caret was in the previous view (done in e20d94e)
- make splitter's background color (currently `COLOR_BTNFACE`) dependent on new schema rule: `Default Text > Splitter`, that defaults to `back:X` where `X` = default of `back` of `Margin and Line Numbers`
  - also handle `size` style to increment/decrement (`size:1`, `size:-2`) width/height of splitters using some hardcoded step (e.g. 2 pixels), and add `size:0` to default rule styles so users sees it's possible
- if hotkeys Ctrl+PageUp/PageDown are currently the same as Ctrl+`[`/`]` then change the former to work like this: Ctrl+PageUp goes to previous view, Ctrl+PageDown - to next, Shift+Ctrl+PageUp opens new vertical view, Shift+Ctrl+PageDown - new horizontal
- add new setting to `Esc Key Function`: "First Close Current &Split View, If Any" (under `---` in the end of Esc Key Function's submenu, as with View > Highlight Current Selection), enabled by default (if current view can't be closed and this is enabled then Escape does nothing)

For discussion: currently the first (initial) view is special in that it can't be closed. How hard is it to make it closeable as well (as long as there are at least 2 views)?

**Comment by cshnik** [comment]
> * fix color of Long Line Marker in sectondary views (always gray)
> * position caret in the new view on the line number where the caret was in the previous view (done in [e20d94e](https://github.com/ProgerXP/Notepad2e/commit/e20d94ec89ee7486e27069f2933bfa9a24e1eda8))
> * make splitter's background color (currently `COLOR_BTNFACE`) dependent on new schema rule: `Default Text > Splitter`, that defaults to `back:X` where `X` = default of `back` of `Margin and Line Numbers`
>   
>   * also handle `size` style to increment/decrement (`size:1`, `size:-2`) width/height of splitters using some hardcoded step (e.g. 2 pixels), and add `size:0` to default rule styles so users see this change is possible
> * if hotkeys Ctrl+PageUp/PageDown are currently the same as Ctrl+`[`/`]` then change the former to work like this: Ctrl+PageUp goes to previous view, Ctrl+PageDown - to next, Shift+Ctrl+PageUp opens new vertical view, Shift+Ctrl+PageDown - new horizontal

Done.

**Comment by cshnik** [comment]
> * add new setting to `Esc Key Function`: "First Close Current &Split View, If Any" (under `---` in the end of Esc Key Function's submenu, as with View > Highlight Current Selection), enabled by default (if current view can't be closed and this is enabled then Escape does nothing)

Done.

> For discussion: currently the first (initial) view is special in that it can't be closed. How hard is it to make it closeable as well (as long as there are at least 2 views)?

Done. 
Additional improvement added: reduced flickering when creating/deleting split views.
