### ISSUE TITLE
Indent with Tab even single line

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#317]
This is for the Tab hotkey.

Currently it seems that Tab triggers indentation if selection includes a line break, otherwise it erases selection (if it existed) and inserts padding. Make is so that it indents as long as there is non-empty selection, no matter if it's single or multiline.

Example: 

```
    [foo].
```

Currently result after Tab is:

```
      .
```

What should be:

```
      [foo].
```

**Comment by cshnik** [comment]
Current behavior is standard for all text editors (press Tab on single line selection): clear selection, indent remaining text.
Do we need INI option to switch to standard behavior?
