### ISSUE TITLE
Alt+Arrow to invert accelerated mode for single navigation

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#323]
Is it possible to hook two Alt+Arrows (Left and Right) combinations so that they don't trigger any side effects? Asking because Alt is used for &accelerators (main menu, etc.) and it often conflicts in other programs. 

If yes then make them move caret as if `WordNavigationMode` (#89) was inverted. For example, by default Ctrl+Arrow Left moves to the preceding word while Alt+Arrow Left would move to the preceding whitespace. If `WordNavigationMode` is enabled then Ctrl+Left moves to whitespace and Alt+Left - to word. Ctrl+Alt+Arrow are not affected by this change.

This is like vim's word/WORD motions, e.g. `w` (word, move by word symbols) and `W` (WORD, move by whitespace).

**Comment by cshnik** [comment]
Please consider changes (committed to temporary branch) related to Scintilla code required for feature implementation.

**Comment by ProgerXP** [comment]
This works extremely well. 

Add processing of Alt+Shift+Arrow by analogy with Ctrl+Shift+Arrow, i.e. in addition to moving caret make it select the text.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Great. Merge the branch if ready and delete it.

**Comment by cshnik** [comment]
> Great. Merge the branch if ready and delete it.

Done.

**Comment by ProgerXP** [comment]
Let's add two more similar hotkeys:

- Alt+Backspace (`bW` in Vim) - like Ctrl+Backspace, with inverted WordNavigationMode
  - Notepad2 is using it for Undo, remove this binding
- Alt+Delete (`dW` in Vim) - like Ctrl+Delete, with inverted WordNavigationMode

**Comment by cshnik** [comment]
> Let's add two more similar hotkeys:
> 
> * Alt+Backspace (`bW` in Vim) - like Ctrl+Backspace, with inverted WordNavigationMode
>   
>   * Notepad2 is using it for Undo, remove this binding
> * Alt+Delete (`dW` in Vim) - like Ctrl+Delete, with inverted WordNavigationMode

Done.

**Comment by ProgerXP** [comment]
Works but Alt+Backspace produces an audible "beep", as if Windows tries to execute a non-existing hotkey.

**Comment by cshnik** [comment]
> Works but Alt+Backspace produces an audible "beep", as if Windows tries to execute a non-existing hotkey.

Fixed.

**Comment by ProgerXP** [comment]
> Let's add two more similar hotkeys:

Must conform to #348.

**Comment by cshnik** [comment]
Done. Alt+Backspace/Delete works for current selection (if any).
