### ISSUE TITLE
Math Evaluation: format decimal result according to the locale

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#332]
Currently calculation result is both displayed and copied as `123456.789` in the status bar. Instead, display it according to the region settings (e.g. `123 456,789` in Russian). This doesn't affect copying (the number is still copied in locale-independent format) and doesn't affect display or copy of other bases (e.g. hex).

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Please pay attention to the description.

> ***This doesn't affect copying (the number is still copied in locale-independent format)***

**Comment by cshnik** [comment]
> Please pay attention to the description.
> 
> > _**This doesn't affect copying (the number is still copied in locale-independent format)**_

Fixed.

**Comment by ProgerXP** [comment]
Strange issue: 

1. Create new document
2. Paste `12334567.89` - statusbar is correct
3. Type Space - statusbar is correct
4. Type Backsapce - statusbar shows non-localized number

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
What was the problem?

**Comment by cshnik** [comment]
> What was the problem?

Cached value was incorrectly calculated and non-localized text string was always used.

**Comment by ProgerXP** [comment]
Improvement: if the to-be displayed localized text consists of 0s and no other digits (but non-digits such as separators are allowed), increase the default precision up to the default used when copying (6?). This way, user will see that the expression's result is not 0 but some small value (such as `0,0001`).

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
> `if (n2e_CheckStringMatchRegexp(tchBuffer, L"0*[.,]0*"))`

I don't like the idea of running regexp in this case and I said `consists of 0s and no other digits (but non-digits such as separators are allowed)` - do a scan for `'1'..'9'` (regexp equivalent `[1-9]`). `.` and `,` alone may not cover all locales that may use spaces, backticks and other symbols for separators.

**Comment by cshnik** [comment]
Done.
Recently added ``n2e_CheckStringMatchRegexp`` retained for future needs.
