### ISSUE TITLE
Function requirements

### ISSUE THREAD

**Issue by wisenut2009** [ProgerXP/Notepad2e#333]
Add a "Remove Duplicate Lines" function.
Add a "Always On Top" button to the toolbar.

Thanks!

**Comment by ProgerXP** [comment]
> Add a "Remove Duplicate Lines" function.

Already have this in Sort Lines (Alt+O).

> Add a "Always On Top" button to the toolbar.

You need it in the toolbar? Alt+T doesn't work for you?

**Comment by wisenut2009** [comment]
> > Add a "Remove Duplicate Lines" function.
> 
> Already have this in Sort Lines (Alt+O).

Got it. Thank you very much!


> > Add a "Always On Top" button to the toolbar.
> 
> You need it in the toolbar? Alt+T doesn't work for you?

Yes, a button on the toolbar may be more convenient.

**Comment by ProgerXP** [comment]
@cshnik 
1. Rename "Sort Lines..." to "Sort/Deduplicate Lines..."
2. Add toolbar button for the Always On Top command

**Comment by cshnik** [comment]
Done.
![image](https://user-images.githubusercontent.com/8019354/104959856-b69cd580-5a05-11eb-8630-b540ff6ba3f8.png)

**Comment by wisenut2009** [comment]
Thanks! :D
@cshnik
