### ISSUE TITLE
New toolbar button: selection mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#339]
It's possible to select in normal mode with Shift and in rectangular mode with Alt+drag. Add a 2-state button that, when in pressed state, makes it so that any interaction with the document doesn't reset the selection but only extends it, i.e. sets selection start = original caret position and end = current caret position. If there was no selection and this button was pressed, new normal selection is started. If there was a rectangular selection then this button keeps selecting in rectangular mode - this makes it possible to select columns even in documents that cannot fit on one page and without scrolling them with mouse wheel.

This button is visible by default and positioned after Word Wrap.

**Comment by cshnik** [comment]
Done.
New button added:
![image](https://user-images.githubusercontent.com/8019354/145306071-7e436fdf-1cad-48a1-9325-f8f0d75cab9c.png)
"Extended Selection" mode works in active split view only and allow to change current selection using mouse clicks and/or navigation keys (arrows/home/end/page up/page down).
Pressing of non-navigation keys or switching to foreign split view will automatically disable the mode.

**Comment by ProgerXP** [comment]
1. I noticed cancelling Find, Go To, Sort dialogs automatically disables this new mode while submitting (e.g. Sort) doesn't. I would either expect **submit** to end the mode and **cancel** to do nothing (not the reverse), or do nothing in any case (good and simple). What is causing this? I don't see anything related in this issue's commits.

2. Rename "Extended Selection" to "Selection Mode".

3. Why are there no `[2e]` comments in new blocks in Notepad2.c (`case`s, function)? Isn't it our convention in such cases?

4. Attempt to click and drag the caret (which works in normal mode) does nothing. 

5. Combinations that break the new mode: Alt+[Ctrl+]Arrow (#323), all Ctrl combinations (Arrow, Page Up, etc.), Ctrl+`[` `]`. Right mouse button click (#54).

Why did you decide to implement a whitelist in f76f539 instead of allowing any keystroke whilst in the selection mode? This approach may be problematic given Notepad2 has a lot of navigation hotkeys. In addition, we can't catch all document changing attempts anyway (see the bug with Sort). It would be fine with me if we just trust the user not to modify the document whilst in this mode - this will simplify the code.
