### ISSUE TITLE
View > St&arting Line Number...

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#342]
New command under Line Numbers. When called, prompts for a single numerical value (negative or positive), stored in the INI as usual. By default is 1. Affects status bar,gutter, Go To dialog, Modify Lines (`$(L)` and `$(0L)`), #340, and possibly other places where line numbers are accessed. 

The prompt looks similar to Tab Settings (Ctrl+T) but smaller: label `First line number:` on the left, text input, OK button on the right with Cancel below it. The dialog's title is `Starting Line Number` (same as the menu command's text).

With this command it's possible to count line numbers from 0 or even from a negative offset. Useful when you have a list of things associated with sequential IDs; if the first thing's ID doesn't begin with 1 then you won't have to do math with a line number to get the ID.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Memo: Notepad2 pads `$(0L)` but we don't do this for negative numbers:

```
-1
00
01
```

And:

```
-10
-9
```

It's unclear if/how this should be addressed: `-   1`, `-01` look a bit off.
