### ISSUE TITLE
Copy Add (Ctrl+E) to insert line break after, not before

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#344]
Currently Ctrl+E adds `\n` before the copied text - make it add it after.

Old behaviour (Notepad2):

```
a
b
c
```

1. Do Ctrl+Shift+C on line 1
2. Do Ctrl+E on line 2
3. Do Ctrl+E on line 3

Result:

```
a (\n)
(\n)
b (\n)
c
```

In other words, there is an empty line in the middle but no line break after last line. New result:

```
a (\n)
b (\n)
c (\n)
```

There's no empty line but last line ends with a line break.

In other words, we now assume that current clipboard contents always includes the trailing line break necessary to separate it from the newly appended contents.

Another change: when clipboard is empty, currently Ctrl+E adds just selected text but now it will add that text + `\n`.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Delete bClipboardDataAvailable, we won't need it anymore

**Comment by cshnik** [comment]
> Delete bClipboardDataAvailable, we won't need it anymore

This variable is still used to retrieve clipboard text:
```
  if (bClipboardDataAvailable)
  {
    hOld = GetClipboardData(CF_UNICODETEXT);
    pszOld = GlobalLock(hOld);
  }
```

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
> Revert the commit and follow this task description: only add line break if current clipboard contents doesn't end on `\n`.

Amendment: `...and is not empty`. This means when clipboard is empty Ctrl+E should add the text with no additional leading or trailing `\n`, i.e. work as Ctrl+C or Ctrl+Shift+C.

**Comment by cshnik** [comment]
Fixed.
