### ISSUE TITLE
Ctrl+Del/Backspace: delete selection if it exists

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#348]
In Notepad2, pressing Ctrl+Del or Ctrl+Backspace on non-empty selection results in unchanged selection. In Notepad++, Ctrl+Backspace is ignored while Ctrl+Del deletes selection. 

Need to make both hotkeys delete selection if it exists.

**Comment by cshnik** [comment]
Done. Now Ctrl+Del/Backspace works the same way as Del.

> In Notepad++, Ctrl+Backspace is ignored while Ctrl+Del deletes selection.

In v7.8.8 ``Ctrl+Backspace``/``Ctrl+Del`` commands will remove word from the right/left side within selection.

**Comment by ProgerXP** [comment]
> Done. Now Ctrl+Del/Backspace works the same way as Del.

I must have produced a misunderstanding. Ctrl+Delete/Backspace are great as they are (deleting word). However, they only do this when selection is empty; if it is not, they simply clear it. The point is that in case of non-empty selection they must delete what is selected (no matter of "word"). Please confirm this was implemented.

**Comment by cshnik** [comment]
> The point is that in case of non-empty selection they must delete what is selected (no matter of "word"). Please confirm this was implemented.
