### ISSUE TITLE
Support for nScripter and NSIS syntax

### ISSUE THREAD

**Issue by dsp2003** [ProgerXP/Notepad2e#35]
Although ASM highlighting mode partially covers nScripter (since they are alike to some degree), it would be awesome to have those (I think I saw some builds with NSIS syntax support, yet none with nScripter).

<a href="http://unclemion.com/onscripter/api/NScrAPI.html">nScripter API syntax reference</a>

If that's too much of work, I'll understand.

**Comment by ProgerXP** [comment]
NSIS syntax scheme added (and a bunch of others like Rust and TeX). In about a month I'll merge this into master but meanwhile you can get the build from commit 3144308b8c30b6b9dac0bff19c9953c6ca2926e0.
