### ISSUE TITLE
File change notify MsgBox: use icon depending on unsaved state

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#350]
When current file has unsaved changes (`*` in the titlebar), use warning icon, else use question icon. This affects both file-changed and file-deleted notifications.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Memo: 6e0dd6a85e78813ea8318a70992242cbfea45aab affected #164: previously, if document is intact except for a changed charset, Save On Lose Focus won't save it; now it will.
