### ISSUE TITLE
Prevent Edit Mode hint from handling pointer events

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#352]
I have seen hints in Windows that are "physical" or "transparent". Our current hint is like another window: you can click on it and hover over it. Sometimes this is inconvenient (e.g. if mouse pointer happens to be in the position where the hint will appear after pressing Ctrl+Tab). "Transparent" hints do not handle pointer events at all and Windows passes messages to the underlying window. Edit Mode's hint should be of this kind.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Looks like this works only if X-Mouse is disabled. Any way to make it work regardless?

**Comment by cshnik** [comment]
Done.
