### ISSUE TITLE
Edit Mode: implicit commit on Ctrl+Alt/Shift+Enter

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#357]
If Edit Mode is active, currently any version of Enter commits and stops. However, Enter with modifiers is actually a different operation than Enter so committing should be implicit just like when caret is moved outside of the edit region (or other cases).

In other words, Ctrl+Shift+Enter should (implicitly) commit and *then* it should insert a line below. Ctrl+Alt+Enter is similar. 

Update: same should be done for Ctrl+A. But it's interesting that Arrow navigation does the implicit commit. Was it coded specifically?

Related to #403.

**Comment by cshnik** [comment]
Done.

> Was it coded specifically?

Correct. This was a part of SCN_UPDATEUI-notification handler (came from Scintilla), SC_UPDATE_SELECTION code is processed to stop `Edit Mode`.
