### ISSUE TITLE
Add INI setting to disable file save prompt in Launch > New Window

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#361]
Currently New Window brings up the prompt for unsaved file. The new option (disabled by default) removes this prompt, opening new window without saving the file. 

This is irrespective of Save Before Running Tools.

**Comment by cshnik** [comment]
Done.
``SkipFileSavePromptOnNewWindowCommand`` INI option added: 0 (default), 1 - disable file save prompt.

**Comment by ProgerXP** [comment]
Remove `SkipFileSavePromptOnNewWindowCommand`, instead extend Notepad2's `SaveBeforeRunningTools` so that value `2` (2e-specific) works as `SkipFileSavePromptOnNewWindowCommand=1`, given that this setting has no meaning when `SaveBeforeRunningTools` is disabled.

**Comment by cshnik** [comment]
``SaveBeforeRunningTools`` option is tied to main menu item with a checkbox.
How is it supposed to work/switch there (in the case of a new non-boolean value [0,1,2])?
![image](https://user-images.githubusercontent.com/8019354/182218713-8ff78d4e-4650-458f-b60c-587df218580e.png)

**Comment by ProgerXP** [comment]
Right, change this into a submenu with 3 radios:

- Disabled
- Enabled
- Enabled except for New Window

**Comment by cshnik** [comment]
Done.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Memo: the setting affects these commands in Notepad2:

1. New Window
1. Empty Window
1. Execute Document
1. Open with
1. Command (Ctrl+R)

In #176 we have disabled it for Empty Window. Now, **Enabled** affects 1, 3-5 while **except** affects 3-5.
