### ISSUE TITLE
Extremely slow Replace when changing line count

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#363]
For example, take a document with 2000 lines in C format (`line\nline\nline`) and Replace from `\\n` to `\n` in either Regexp or Transform backslashes mode. This will take up to 10 seconds depending on the document, Word Wrap state and probably other parameters. In Notepad++ this takes half a second at most.

This might be because window state is updated during the replace (I see scrollbars changing). 

Related issue: after you convert `\\n` to line breaks, do Ctrl+Z - it will again take many seconds. In constrast, Ctrl+Shift+Z is instant.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Appears to be even faster than Notepad++ in this particular case.
