### ISSUE TITLE
Is Notepad2e bundled with another software?

### ISSUE THREAD

**Issue by lavanyadeepak** [ProgerXP/Notepad2e#364]
I just came to know about Notepad2E when I was trying to type Notepad in Start Menu. However I never knew how and when I installed it.

![image](https://user-images.githubusercontent.com/2217926/125019763-304c7c80-e095-11eb-8958-3d6bbb2dfc6f.png)

**Comment by ProgerXP** [comment]
That's probably TortoiseGit, as mentioned in the beginning of Notepad 2e's README.

**Comment by lavanyadeepak** [comment]
Both these gems (TortoiseGIT) and (Notepad2E) are definitely imperative items in any developer's toolbox. Appreciate the good work
