### ISSUE TITLE
Alt+Backtick: enter Edit Mode with inverse line/document-wise setting

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#366]
If `Document-Wise Edit Word` is enabled, ~~Ctrl+Alt+Tab~~ Alt+backtick enters Edit Mode in `visible only` mode. If it's disabled - in `document-wise`. Thus, Ctrl+Tab is using `setting` and ~~Ctrl+Alt+Tab~~ Alt+backtick is using `!setting`. New menu command: Edit > Edit Selection Not Wise, under Edit Selection.

Update: Ctrl+Alt+Tab is a standard global Windows hotkey.

**Comment by cshnik** [comment]
Done.
