### ISSUE TITLE
Select To Matching Brace to include brackets

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#367]
Extend this command when FindSelectToMatchingBraceMode  is enabled (#293) so that if current selection equals bracketed contents it extends selection by including surrounding brackets (as if FindSelectToMatchingBraceMode  were disabled).

```
<(a|)>
```

First Ctrl+Shift+B selects `a`.  Second selects `(a)` because current selection already equals selection the command would produce (`a`).

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Bug: extension includes up to one trailing symbol:

```
([a]).
```

Press Ctrl+Shift+B to see `[(a).]` selected instead of [(a)].`.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Expansion needlessly depends on caret position:

```
([|a])
([a|])
```

It is expected that in both cases Ctrl+Shift+B would select the outer brackets but the second case currently only moves the caret to the opposite side, requiring one more Ctrl+Shift+B to select all.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Selection isn't extended anymore at all:

```
(|a) -> ([a]) -> must be [(a)] but remains ([a])
```

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
> **if current selection equals bracketed contents** it extends selection by including surrounding brackets 

Bug in R261 7b1cf6f

```
(a[b])
```

Ctrl+Shift+B selects `[(ab)]` rather than `([ab])` even though `current selection <does not> equals bracketed contents`.

**Comment by ProgerXP** [comment]
The above issue has been fixed in some commit.
