### ISSUE TITLE
Edit Mode to highlight matches on screen in all split views

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#369]
Currently Edit Mode highlights occurrences seen on the screen of the focused split view (#316). Make it highlight them in screens of all split views. This does not affect Ctrl+Tab region (it still edits occurrences within the current view's screen). Let me know if it needs substantial refactoring (due to replacing single edit scope with multiple disconnected scopes).

It's possible that different views will use different highlight styles. Consider a window with 2 views: small and large. The small view highlights using "multiple occurrences, some invisible" style. The large view, whose first visible line is the same as small's (and last line is below last small's line), may highlight using "multiple occurrences, **all visible**" style. 

If the small view is focused then Ctrl+Tab would edit only some of occurrences visible in the large view. If the large view is focused then Ctrl+Tab would edit all occurrences.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
> This does not affect Ctrl+Tab region (it still edits occurrences within the current view's screen).
>
> If the small view is focused then Ctrl+Tab would edit only some of occurrences visible in the large view. If the large view is focused then Ctrl+Tab would edit all occurrences.

Currently Ctrl+Tab edits all regions in all views regardless if they're "visible" in the active view.

**Comment by cshnik** [comment]
> Currently Ctrl+Tab edits all regions in all views regardless if they're "visible" in the active view.

Fixed.

**Comment by ProgerXP** [comment]
Memo: now Ctrl+Tab edits only current view's occurrences; highlighting in other views is disabled in Edit Mode except for visible edit regions (blue).
