### ISSUE TITLE
Do not clear Undo history on cancel Edit Mode

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#374]
Enter `aa`, space, Copy All (Alt+C), Paste twice, Undo (Ctrl+Z, another Undo is still possible), Ctrl+Tab, Escape (***no more Undo even though no changes were made***).

**Comment by cshnik** [comment]
Cannot Reproduce.

> Enter `aa`, space, Copy All (Alt+C), Paste twice, Undo (Ctrl+Z, another Undo is still possible)

Gives the following:
> aa aa |

Next step is:
> Ctrl+Tab, Escape

Ctrl+Tab does not work on whitespace. If we move cursor back and repeat ``Ctrl+Tab, Escape``:

> aa |aa 

Undo is available, however first undo action does not affect the documents text (while subsequent call does).

**Comment by cshnik** [comment]
Fixed.
