### ISSUE TITLE
Crash when window is quickly changing focus

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#375]
After merging Split View #316 (R134 is not affected), the process sometimes crashes:

1. Launch this script using AutoHotkey (https://www.autohotkey.com):

```
RunAndActivate(path) {
  Run %path%, , , pid
  WinWait, ahk_pid %pid%, , 0.1
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.2
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.3
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.4
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.5
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.6
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.7
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.8
  WinActivate, ahk_pid %pid%
  WinWait, ahk_pid %pid%, , 0.9
  WinActivate, ahk_pid %pid%
}

^Q::RunAndActivate("path\to\Notepad2e.exe")
```

2. Launch one Notepad2e.exe process
3. Move the window to the left by ~50 pixels and position the mouse pointer near the left edge so that it remains above this window after step 4
4. Launch another Notepad2e.exe process via the script by pressing Ctrl+Q
5. Start clicking on the ***first*** window quickly; you should see repeated activation of first and second processes' windows, in about half the cases followed by a crash

**Comment by cshnik** [comment]
Fixed.
