### ISSUE TITLE
Main window losing focus after closing Find with X-Mouse enabled

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#376]
1. Enable X-Mouse in Windows (Ease of Access > Activate a window by hovering...)
2. Open Notepad 2e
3. Ctrl+F (ensure the document is not empty)
4. Move mouse pointer so that it's on top of the main window but outside of Find
5. Now the main window is focused, Find isn't
5. Type something - keystrokes go to Find's Search input (this is already strange)
6. Press Escape
7. Find dialog closes but the main window loses focus and doesn't respond to keystrokes

Update: this was caused by #316.

**Comment by cshnik** [comment]
Fixed.
