### ISSUE TITLE
Ctrl+Shift+* - search for word

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#38]
Menu items:
- **Edit | Find Next Word** after Replace Next
- **Edit | Find Previous Word** after Find Next Word

In vim, you can type `aa bb aa aa`, position caret at middle `aa`, press `*` or `#` to position caret at next or preceding `aa` (so at `|aa bb aa aa` or `aa bb aa |aa`).

Need to:
- See if Ctrl+\* and Ctrl+Shift+\* hotkeys are available
- Make them work like in vim: we already highlight "word" under cursor; the same definition of "word" should be used to find next/previous occurrence of this word in the document (not limited to visible screen portion). The search should wrap around. The word should be selected after search. If there's no word in the entire document nothing happens.

Essentially this must be identical to using Ctrl+F Find dialog but with a single hotkey. Example:
- Make new document with text `aa bb aa aa`
- Position caret at the beginning
- Press Ctrl+*
- You get this selection: `aa bb [aa] aa`
- Press Ctrl+Shift+*
- You get this selection: `[aa] bb aa aa`
- Press Ctrl+Shift+*
- You get this selection: `aa bb aa [aa]`

You could achieve the same effect by:
- Selecting first `aa` to get `[aa] bb aa aa`
- Pressing Ctrl+F - the input would contain `aa`
- Pressing Enter
- Getting this selection: `aa bb [aa] aa`
- **Or instead of Enter** you could press Alt+P to trigger _Find Previous_ and you'd get `aa bb aa [aa]`

**Comment by ProgerXP** [comment]
Strange bug:
```
public |$foo;

$foo = 123;
$foo = 345;
```

Cursor before first `$`. Ctrl+8. `foo` on the line with 123 gets selected. This is correct. Now F3. This time `$foo` with 345 gets selected which is not correct - `$` should not be included in the selection. In other words:
```
$[foo] = 123;
[$foo] = 345;
```

Should be:
```
$[foo] = 123;
$[foo] = 345;
```

If you go to Find after F3 you will see that Search String is set to `$foo` instead of `foo`.

**Comment by ProgerXP** [comment]
Fixed by @cshnik in dev, mechanism changed.

**Comment by ProgerXP** [comment]
This feature needs to be revisited:

- it's now independent of normal F3 find - make it partially dependent: 
  - when called, Find Word adds current search term to F3's history (so after Find Word F3 will search the same string)
- if there is no selection, Find Word takes closest word - keep this; when there is selection, Find Word currently uses last search - this is removed, make it search for selection instead (like F3 does)
  - as a consequence, there is no more need to remember last Find Word search string in code

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
>when called, Find Word adds current search term to F3's history 

This works.

> (so after Find Word F3 will search the same string)

This doesn't - F3 doesn't "see" the search term added by Ctrl+8.

> if there is no selection, Find Word takes closest word 

This works.

> there is selection, Find Word currently uses last search - this is removed, ***make it search for selection instead (like F3 does)***

This doesn't.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
When there is no selection, Find Next Word takes closest word on the right. Make Find Previous Word do the same (currently it takes word on the left).

**Comment by cshnik** [comment]
> When there is no selection, Find Next Word takes closest word on the right. Make Find Previous Word do the same (currently it takes word on the left).

Fixed.

**Comment by ProgerXP** [comment]
It seems FindWord... settings are no longer respected:
https://github.com/ProgerXP/Notepad2e#findwordmatchcase--findwordwraparound

**Comment by cshnik** [comment]
> It seems FindWord... settings are no longer respected

Cannot reproduce.
In my local tests both ``FindWordMatchCase``/``FindWordWrapAround`` options work as expected when using ``search for word``-commands. Please provide your exact scenario if the problem remains.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
> if there is no selection, Find Word takes closest word - keep this; **when there is selection, Find Word currently uses last search - this is removed, make it search for selection instead (like F3 does)**

Clarification: when there is selection, make Find Word search for selection but using Find Word's settings (`FindWordMatchCase`, etc.), not exactly as normal F3 does (using Find dialog's settings).

Example: `[|aa] aaa aa` - currently Find Next Word selects `[aa]a` but it should select `aaa [aa]` (since Match Word is always enabled for Find Word).

**Comment by cshnik** [comment]
Done.
