### ISSUE TITLE
Use non-proportional font in search/replace dialog

### ISSUE THREAD

**Issue by WebMechanic** [ProgerXP/Notepad2e#381]
It would be nice, if the two text fields would use **any** non-proportional (fixed width) font available on the system; Courier, Consolas, whatever.
Editing regular expressions with a sans-serif font are a pita to type and to look at.

Thank you.

**Comment by ProgerXP** [comment]
> Editing regular expressions with a sans-serif font are a pita to type and to look at.

I always use another Notepad2 window as a scratchpad. But I see your point, will note this for the future.

**Comment by cshnik** [comment]
Fixed.
