### ISSUE TITLE
New command: Insert Replacement

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#387]
Edit > Find > Insert Replacement (Ctrl+F4), after Replace Next. Currently this hotkey works like Alt+F4 (Exit) - reassign it; Notepad2 is not MDI.

Simply replaces current selection (or inserts text at cursor, if none) with Replace dialog's `Replace With` (this text is used by the existing F4 command). Unlike F4, doesn't advance to next match and doesn't test selection before replacing. If `Replace With` is "unset" (as understood by F4), only shows the Replace dialog.

**Comment by cshnik** [comment]
Done.
