### ISSUE TITLE
Ctrl+Shift+3 - unwrap brackets

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#39]
Menu item: **Edit | Block | Unwrap Selection** after Duplicate Selection.

Also see if menu contains the action currently triggered by Ctrl+3 - if not insert it before **Unwrap Selection** as **Wrap Selection** (Ctrl+3).

There is Ctrl+3 command that encloses selection in parenthesis: `(a)`. Need to have its counterpart that will seek current opening brace by going from the caret position to the document beginning, if found - go from original caret position to the end seeking its counterpart (`( { [ <` > `) } ] >`) and if found - should remove opening and closing brackets (just two characters).

When seeking opening brace the code should account for nesting - if it encounters a closing brace it should remember it and if it encounters an opening brace of the same type it should skip it instead of considering it for unwrapping. If it encounters two closing brackets, or multiple brackets of multiple types - it should maintain the counter correctly.

No need to check for cases with bad nesting: `<a (b> c)` - just need to maintain counters. The code assumes opening brace to be found when it has no closing brace counterpart.

After finding it the code seeks the closing brace in the exact same fashion - counts nesting - and stops when it finds a closing brace of the type of the opening brace that has no opening brace counterpart.

If there was either no opening or closing brace - do nothing.

Example:

* Create document with:
```
(function () { 
  "<tag>"
})
```
* Position caret before letter  *a *
* Press Ctrl+Shift+3
* Line changes to `  "tag"`
* Now revert changes
* Position caret before any quote: `"`
* Press Ctrl+Shift+3
* First line changes to `(function () ` + space, last line changes to `)`
* Now revert changes
* Position caret between `})`
* Press Ctrl+Shift+3
* The code goes from right to left like this:
 * `}` - closing brace, remember (count = 1)
 * `\n` `"`
 * `>` - closing brace, remember (count = 1)
 * `g` `a` `t`
 * `<` - opening brace, but we have found a `>` before so skip it
 * 2 spaces, `\n` 
 * `{` - opening brace, but we have found a `}` before so skip it
 * 1 space
 * `)` - closing brace, remember (count = 1)
 * `(` - opening brace, but we have just found a `)` so skip it
 * 1 space, `n` `o` `i` `t` `c` `n` `u` `f`, 1 space
 * `(` - opening brace and we have not met unmatched `)` so this is the opening brace we need, return
* After finding `(` the code goes  from current caret position to right like this:
 * `)` - found closing brace of type `(`, no matching brace found before so we found what we need
* Now first line changes to `function () {` while last line becomes `}`

 **Note:** nesting can be complex so should be parsed correctly: `<a (b <c> d) e>`

**Comment by ProgerXP** [comment]
**Bug:**
```
(array(>) + $zz|)
```
Unwrap, result:
```
(array>) + $zz
```
Expected:
```
array(>) + $zz
```

If `>` is removed upwrapping is correct. 

I don't know how you count nesting level but make sure that you count it per each brace type, not in sum for all braces - so in `(a<b(c` nesting is 2 levels for `(` and 1 level for `<`.

**Bug 2:** 
```
(array(<) + $zz|)
```
Result: nothing happens. I have said in the first post:
> No need to check for cases with bad nesting: `<a (b> c)` - just need to maintain counters. The code assumes opening brace to be found when it has no closing brace counterpart.

This is exactly this case. Even if `<` is left unclosed there is no matching closing brace for the leftmost `(` so the result should be:
```
array(<) + $zz
```

**Comment by hacc** [comment]
fixed both cases

Bug 1 => It was my logical error . 
Bug 2 => I didn't undestand subj. This case is quite complex so it needs  tests.
