### ISSUE TITLE
Put Notepad2e on AlternativeTo

### ISSUE THREAD

**Issue by tasty0tomato** [ProgerXP/Notepad2e#394]
I am a big fan of Notepad2 and Notepad2e, and I want to let more people to know it, so I put it on Alternative.

https://alternativeto.net/software/notepad2e/about/

If a logo of Notepad2e is given, it will be better.

**Comment by ProgerXP** [comment]
@tasty0tomato Hey, thanks for listing it! I was thinking about a new icon for 2e for a while now that it's a mature and distinct project. Will create an issue to put this forth.
