### ISSUE TITLE
Make Escape in main window close visible dialog, if any

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#398]
When the main window handles an Escape keystroke, it should check if there are any visible dialogs and direct Escape to one of them (closing it). If there are no dialogs, `Esc Key Function` should be effected.

Rationale: Several Notepad2 dialogs are non-modal (Ctrl+F, Ctrl+G, etc.) and it's possible to accidentally unfocus them by clicking or hovering (with active X-Mouse) outside of them but inside the main window. Pressing Escape in this case (when a dialog is visible but focus is in the main window) is usually meant for handling by the dialog and current behaviour is frustrating when Escape is configured to close or minimize the program.

**Comment by cshnik** [comment]
Done.
