### ISSUE TITLE
Implicit commit of Edit Mode on Shift+Tab and Ctrl+A

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#403]
Document:

```
    aa aa|
```

Ctrl+Tab, then Shift+Tab causes state corruption. Shift+Tab should behave as if the edit region was left (with arrow keys, etc.), i.e. first commit and exit Edit Mode, then un-indent.

Ctrl+A already works as described but the operation doesn't complete - Edit Mode commits, caret moves to the top but nothing becomes selected.

**Comment by cshnik** [comment]
Done.
