### ISSUE TITLE
Join Lines to keep whitespace of blank line

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#407]
Current Join Lines algorithm with empty selection (#160) is as follows:

> 1. Find nearest line break (NLB) to the caret's right.
> 2. Remove all whitespace adjacent to NLB until old NLB position is surrounded by non-whitespace symbols. Whitespace = `0x20 \t \r \n`.
> 3. Insert 1 space at old NLB position and set caret after it.

Alter step 2 as such:

1. Remove all whitespace on the right of NLB (i.e. after `\n`)
2. Scan for the first non-whitespace on the left of NLB (i.e. before `\n`), stopping on line break and document start
3. If non-whitespace was found, remove all whitespace after it and before NLB (i.e. current behaviour)
4. If none was found, remove whitespace after current caret position and before NLB

And step 3 as such:

3. **If non-whitespace was found,** insert 1 space at old NLB position and set caret after it. **Otherwise, remove NLB and set caret at its old position** (technically changing position is unnecessary since no symbols are removed before the caret in the only-whitespace case).

Example (`_` = space):

```
__|__
__a__
__b__
```

After new sub-step 2.1:

```
__|__
a__
__b__
```

2.2 finds no non-whitespace, hitting document start. 2.3 is skipped. 2.4 produces final result:

```
__|a__
__b__
```

On calling Ctrl+J again, 2.1 produces:

```
__|a__
b__
```

2.2 finds non-whitespace `a`. 2.3 (and 3) produce final result (2.4 is skipped), which is the same as calling Ctrl+J on the above document using the current implementation:

```
__a_|b__
```

**Comment by cshnik** [comment]
Completed.
