### ISSUE TITLE
Remove input length limit in dialogs

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#408]
Inputs in Alt+M, Alt+Q and possibly elsewhere don't accept more than 255 symbols (not bytes). Ctrl+F/H inputs accept 500 at most which is better but still insufficient. What is the reason for these limits?

**Comment by cshnik** [comment]
General ``EDITFINDREPLACE`` structure contains the following text buffers:
<img src="https://user-images.githubusercontent.com/8019354/172916315-f221c91d-af74-4c47-928d-895fb73dd220.png" width="400px"/>
512 - is the max string length (including trailing 0) internally allowed (for now) for proper Find/Replace work.

Other procs use predefined buffers:
<img src="https://user-images.githubusercontent.com/8019354/172918250-0e553689-ba54-4b3a-9d8f-38306fa8620c.png" width="300px"/>

**Comment by ProgerXP** [comment]
@cshnik Do text inputs have any limits of their own in WinAPI? Or Notepad2's limits are the only reason?

**Comment by cshnik** [comment]
MSDN states edit control text length limits ([EM_LIMITTEXT](https://docs.microsoft.com/en-us/windows/win32/controls/em-limittext)):
> For single-line edit controls, the text limit is either 0x7FFFFFFE bytes or the value of the wParam parameter, whichever is smaller. For multiline edit controls, this value is either -1 byte or the value of the wParam parameter, whichever is smaller.

Changes required to support unlimited text length are:
1. Replace fixed length text buffers with struct ``pointer + length``
2. Implement procs for text buffers allocations/relocations
3. Review every call to text buffers and fix it accordingly

The simplest way would be to adjust fixed text length to a reasonable big value and let all the other code work as is.

**Comment by ProgerXP** [comment]
> The simplest way would be to adjust fixed text length to a reasonable big value and let all the other code work as is.

Indeed, let's increase all buffers' lengths by 10. Currently they use 5 KiB in total, this will be 50 KiB then (there is always one `_editfindreplace` instance per process, right?).

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
We've increased MRU (#447) and input limits but keep in mind WinAPI's limit of 32767 characters per INI section:

https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilesection
