### ISSUE TITLE
Improve File Change Notification for slow medium

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#409]
Since file monitoring is on the main thread (WM_TIMER), slow `FindFirstFile()` makes the program almost non-responsive. This is common with network shares outside of the local network. A simple solution is to disable monitoring or increase polling interval, but a better approach would be to move monitoring to another thread. I have briefly checked the code and it seems easy to convert `WatchTimerProc()` into a thread function.

Related to #241.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
I have started to see notifications on regular file save. This is extremely rare but I am confident there is a bug in the implementation.

**Comment by cshnik** [comment]
Fixed.
