### ISSUE TITLE
Line Comment to prefix all lines, even comments

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#410]
Currently, the `Special > Line Comment (Toggle)` command does not affect already prefixed lines (unless all lines are prefixed, then it works like un-comment). Remove this check.

```
function fn() {
  if (0) {
    // Foo.
    bar();
```

Result of Ctrl+Q on lines 2-4, before:

```
function fn() {
  //if (0) {
    // Foo.
  //  bar();
```

Desired:

```
function fn() {
  //if (0) {
  //  // Foo.
  //  bar();
```

**Comment by cshnik** [comment]
Fixed.
