### ISSUE TITLE
Add command to copy result of math expression

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#414]
Add `---` and `Copy &Result` (hotkey: Alt+Shift+R) to the end of Settings > Evaluate Math Expressions. The command is always enabled and works independently of the setting, as if the setting was set to `Current Selection or Line`: on non-empty selection it evaluates selection and copies the result, on empty - evaluates line and copies the result. "Copy" means the same action as left-clicking does on the status bar group (respecting current radix mode, #404, etc.). If the to-be-evaluated expression is invalid, clipboard is unchanged.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
> "Copy" means the same action as left-clicking does on the status bar group (respecting current radix mode, #404, etc.).

#404 was not implemented for this command.

**Comment by cshnik** [comment]
Fixed.
