### ISSUE TITLE
Preserve edit state after Compress Whitespace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#421]
Commands like Alt+W, Alt+R, etc. attempt to keep original selection, scroll, etc. even if the document was modified. Implement the same for Alt+P.

**Comment by cshnik** [comment]
In my local tests Alt+P behave near the same way as Alt+R: selection get adjusted according to the applied command and remains visible on screen.
Please provide steps to reproduce to see the difference in these commands.

**Comment by ProgerXP** [comment]
> In my local tests Alt+P behave near the same way as Alt+R: selection get adjusted according to the applied command and remains visible on screen.

But caret doesn't.


```
a__|a_
```

After Alt+W:

```
a__|a
```

After Alt+P:

```
|a_a
```

---

```
a


a|
```

After Alt+R:

```
a

a|
```

**Comment by cshnik** [comment]
Fixed.
