### ISSUE TITLE
Customize Windows shutdown prevention message on modified file

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#422]
Run Notepad2, modify document, initiate Windows shutdown or sign out. Notepad2 will display the "Save changes?" box before Windows shows the blue screen with pending programs. If you then cancel the shutdown, return to desktop, and press No in the message box, Notepad2 will do nothing instead of exiting.

On a related note, what is the mechanism of customizing the message shown by Windows on this blue screen (under the program's name), like some programs do?

**Comment by cshnik** [comment]
> If you then cancel the shutdown, return to desktop, and press No in the message box, Notepad2 will do nothing instead of exiting.

This is a standard behavior for foreign applications, e.g. for ``notepad`` and ``mspaint``.
Applications will not quit after closing "Save changes"-prompt in case of cancelled logout/shutdown.

> On a related note, what is the mechanism of customizing the message shown by Windows on this blue screen (under the program's name), like some programs do?

[ShutdownBlockReasonCreate](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-shutdownblockreasoncreate) is responsible for providing custom reason string.

**Comment by ProgerXP** [comment]
> This is a standard behavior for foreign applications, e.g. for `notepad` and `mspaint`.

Didn't know that.  What code is responsible for this behaviour in Notepad2/e?

> [ShutdownBlockReasonCreate](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-shutdownblockreasoncreate) is responsible for providing custom reason string.

Let's display the string `Unsaved <file name>` (`ShutdownBlockReasonCreate` restricts the message to be `MAX_STR_BLOCKREASON`, i.e. 256 characters long so not showing full path).
