### ISSUE TITLE
Find Next/Previous must skip first match

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#424]
Some recent commit has changed the following behaviour found in Notepad2/e:

```
|aa aa
```

or

```
aa aa|
```

When you press Ctrl+F3 (or Ctrl+Shift+F3 for the second example), recent versions (R220 1c36b48 and R240 4c1abae) will select the `aa` near the cursor. However, that match must be ignored and another `aa` must be immediately selected. In R205 9de5ced this works as expected.

Update: it seems like a related problem exists: in absence of word under cursor, nearby word is not searched for (R205 did this correctly, R220+ no longer do):

```
|.aa aa   C+F3
aa aa.|   C+S+F3
```

**Comment by cshnik** [comment]
The bug was accidentally introduced during the work on #321. Fixed.
