### ISSUE TITLE
Ignore Alt keypress in Find/Replace/Go To

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#426]
Similarly to #399, in these three non-modal dialogs Alt by itself (i.e. Alt followed by Enter, Space, Arrow Down, etc.) should do nothing instead of invoking system menu because it often gets in the way of various accelerator hotkeys (Alt+C, etc.). The menu can be still invoked by the Alt+Space keystroke, or right-clicking on the title bar.

Alternatively (and ideally), this can be implemented for all dialogs in the program, not just these three.

**Comment by cshnik** [comment]
Done. All dialogs ignore Alt keypress while accelerators are still available.
