### ISSUE TITLE
Alt+Home/End to navigate line, not subline

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#429]
Currently, Alt+Home/End put the caret to the beginning/end of the wrapped subline, Shift+Alt+Home toggles between selection to line start with/out indentation, and Shift+Alt+End selects to line end.

Change these to ignore indentation and subline boundaries, always putting caret/selecting to line start/end.

Example (a single wrapped line with 3 sublines, `.` = space):

```
..abcd
ef|gh
ij
```

Alt+Home: `|..abcd`
Shift+Alt+Home: `[..abcd ef]gh`
Alt+End: `ij|`
Shift+Alt+End: `[gh ij]` (matches current behaviour)

**Comment by cshnik** [comment]
Done.
