### ISSUE TITLE
Change default toolbar buttons

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#431]
~~Customize Toolbar dialog's Reset button must apply the same buttons and order as the program uses in absence of an INI file. For example, Reset currently doesn't add Save Settings On Exit.~~ Apparently I have messed up - there's a single place where toolbar is initialized so the order must be the same in both places.

Before doing so, change the set of default buttons:

```
New
Open
Favorites
Open Previous
Open Next
Save
Binary-Safe Save
---
Undo
Redo
---
Cut
Copy
Paste
---
Find
Print
---
Split Vertically
Split Horizontally
Close Split
---
Word Wrap
Selection Mode
Always On Top
Save Settings On Exit
---
Zoom In
Zoom Out
```

Due to lack of free space, removed previously default Browse button (most users don't have Metapath), Select Scheme (can be called by double clicking in the last status bar group), Customize Schemes (rarely used, reachable via the main menu), Replace (reachable via Find), Exit (close using the titlebar).

**Comment by cshnik** [comment]
Done.
