### ISSUE TITLE
Alt+PageUp/PageDown to move caret to page top/bottom

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#433]
This is like `H L M` in Vim.

The hotkeys put caret on the first/last line that would not cause scrolling as a result of `ScrollYCaretPolicy`. 

For example, if currently visible lines are:

```
first
second
third
fourth
fifth
sixth
```

Assume `ScrollYCaretPolicy` is as such that when caret is on line 1 then page is scrolled but not if on line 2 or below. In this case Alt+PageUp would place caret on line `second` (and the original column) while Alt+PageDown - on `fifth`.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Works only if there are no wrapped lines - otherwise caret position is calculated incorrectly.

**Comment by cshnik** [comment]
Fixed.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Minor/future issue: this currently sets caret to the first subline so if there's a long wrapped line on top of the screen whose leading sublines are invisible, Alt+PageUp will actually scroll the viewport.
