### ISSUE TITLE
Add hotkeys to cycle MRUs in Find/Replace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#434]
Ctrl+N: sets Search String to the item after current item (if there's no current then sets to the first item in the list). If there's no next item then does nothing.

Shift+Ctrl+N: sets to the previous item, if any. If there's no current item, sets to the last.

Shift/Ctrl+H: same for Replace With (Replace dialog only). 

Add hints to inputs: Search String (`Select next (Ctrl+N), previous (with Shift)`), Replace With (same but `Ctrl+H`).

**Comment by cshnik** [comment]
Done.
