### ISSUE TITLE
Find - disable Match whole/beginning of word when Regexp is checked

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#439]
Enabling Regexp search is incompatible with `Match whole word` and `Match beginning of word`. When Regexp is checked, those two are disabled and their check marks disappear even though if you subsequently disable Regexp, they will reappear. This is especially confusing due to the feature of Ctrl+F3 that disables Regexp search - if user has previously noticed that Regexp is on while `Match` are (visually) off, he doesn't expect Ctrl+F3 to search with `Match` on (yet this is what happens).

Because Regexp search isn't automatically enabled, the only way to turn it on is by user clicking on it or using an accelerator. Therefore when this happens, uncheck `Match whole word` and `Match beginning of word` in addition to disabling them.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Changes done in scope of this issue:

- Ctrl+F3 now unsets not only the Regexp flag but also the two Word flags
- Checkmark in the two Word checkboxes is no longer removed if those checkboxes are disabled - Word flags are still ignored when Regexp is enabled but user clearly sees what state the Word checkboxes will be if he unchecks Regexp 
- Made the two Word checkboxes mutually exclusive in the UI: checking one immediately unchecks another

**Comment by ProgerXP** [comment]
> Ctrl+F3 now unsets not only the Regexp flag but also the two Word flags

On the second thought, unconditionally clearing Word flags is wrong because user could have enabled one of them without enabling Regexp meaning Ctrl+F3 should use that mode (it's occasionally useful). This change should be altered by only clearing Word flags if Regexp was present; if it wasn't, leave Word flags as they were.

**Comment by cshnik** [comment]
Fixed.
