### ISSUE TITLE
Always save Find strings to MRU

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#440]
This is a Notepad2 behaviour. It appears that only Search String's explicitly entered into the dialog are saved to MRU (and INI). Implement saving of all strings used to perform Find or Replace even once (including Alt+F3, Ctrl+F3, Ctrl+8).

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
Also add for Alt+F3.

**Comment by cshnik** [comment]
Done.
