### ISSUE TITLE
Join Lines/Paragraphs - Alt modifier to not add space

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#451]
Extend both commands so that when Alt is present they do not add space between former lines. Otherwise respect current behaviour and earlier issues: #407 #160 #135.

Add two new commands to Edit > Lines: `Join Lines Without Space` (after Join Lines) and `Join Paragraphs Without Space` (after Join Paragraphs).

```
[a
b

c
d]
```

Ctrl+J, Alt+Ctrl+J:

```
[a b  c d]
[ab cd]
```

Ctrl+Shift+J:

```
a b

c d
```

Alt+Ctrl+Shift+J:

```
ab

cd
```

**Comment by cshnik** [comment]
Done.
