### ISSUE TITLE
Upgrade default ToolbarButtons value

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#457]
Implement a mechanism of updating default toolbar configuration according to program changes. In other words, determine default values of `ToolbarButtons` from git history (including the original value of Notepad2 4.2.25), record them into a static array and test current `ToolbarButtons` value: if it's part of that array, clear it (i.e. set `ToolbarButtons` to current default value), else keep it. To keep the array short it's possible to exclude short-lived `TOolbarButtons` values (present in code for several commits/days only).

This will allow users of old versions who didn't customize the toolbar have the new set of buttons (including split view and show outline) when they upgrade to latest Notepad 2e.

**Comment by cshnik** [comment]
Done.
