### ISSUE TITLE
How is it compared to zufuliu's Notepad2?

### ISSUE THREAD

**Issue by tn1997tn** [ProgerXP/Notepad2e#458]
His fork is more active developed than you. Is there any reasons one should use your version instead?

https://github.com/zufuliu/notepad2

**Comment by ProgerXP** [comment]
> Is there any reasons one should use your version instead?

Plenty thereof, and they're all described in the README and, if you're having trouble reading it, in the one-line project description:

>  Word highlighting, **simultaneous editing, split views, math evaluation, un/grep, comment reformatting**, UAC elevation, complete regexps (PCRE), **Lua lexers**, DPI awareness and more (XP+)
