### ISSUE TITLE
But can we haz the code folding?

### ISSUE THREAD

**Issue by babanga** [ProgerXP/Notepad2e#463]
Hi, that's a really great mod I've been using for year. But have you checked the possibility to implement the code folding part. I remember there was another mod that had it /XhmikosR/notepad2-mod Would it be possible to port that functionality?

**Comment by ProgerXP** [comment]
> Would it be possible to port that functionality?

Like you said, there's a bunch of alternatives - possibly the first thing most Notepad2 mods implement is (visual) code folding. However, I personally don't need it and so we focus on more distinct features. There wasn't much public demand for folding anyway.

Note that there are still commands working with internal document structure based on folding (#432, #441, etc.).

**Comment by YouveGotMeowxy** [comment]
+1 for bringing back Code Folding! :)

![image](https://github.com/ProgerXP/Notepad2e/assets/39491297/4467ac6c-6b75-4e4d-be7a-58110f2d06ae)

**Comment by ProgerXP** [comment]
More implementing or porting then bringing back... Well, public demand is still not high enough :)
