### ISSUE TITLE
Hotkeys emitting control characters if a dialog is visible

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#467]
Perform a Find that shows `The specified text was not found.` or `Reached the end...` message (non-modal). Focus the main text area and press Ctrl+F/H/G (maybe others as well).  Observe that the document gets `ACK`, `BS`, `BEL` printed. Rather, the current (topmost) window must be focused in this case.

Check all potential commands and messages for this fix.

Update: when Replace or Go To is visible and Ctrl+F is pressed, the message is dismissed and the dialog is switched. Same with Ctrl+H/G.

**Comment by cshnik** [comment]
Done.
