### ISSUE TITLE
Inconsistent word selection of Find Word

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#469]
Unlike other commands (e.g. Ctrl+F3), #38 doesn't attempt to select word preceding caret on the same line (as if an implied Ctrl+Space was issued before the operation):

```
.a.|
.b.|
.a.
.b.
```

With Ctrl+F3, if caret is on the line with `a`, `a` is made the search term. If caret is on `b`, then `b` is searched.

With Ctrl+8, first case results in `b` being chosen while second case searches for `a` (and finds nothing).

Related: #205 #319

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
I don't see any change in behaviour. Ctrl+8 still differs from Ctrl+F3:

> With Ctrl+8, first case results in `b` being chosen while second case searches for `a` (and finds nothing).

**Comment by cshnik** [comment]
> I don't see any change in behaviour. Ctrl+8 still differs from Ctrl+F3:
> 
> > With Ctrl+8, first case results in `b` being chosen while second case searches for `a` (and finds nothing).

Fixed.
