### ISSUE TITLE
 Save Find Text (Alt+F3) to work on empty selection (next word)

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#470]
Similarly to #319, Alt+F3 must operate on the nearby word if there's no selection. Currently it doesn't save any text in such case.

According to changes in #321, I see this command is implemented together with Ctrl+F3 and that one correctly works on empty selection. I wonder why doesn't Alt+F3 work the same?

**Comment by cshnik** [comment]
Fixed.
