### ISSUE TITLE
Refresh selection highlighting after window resize

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#474]
Open a document with several matches on different lines, select one of them (with all others visible) and resize the window in such a way that some matches stop being visible - the highlighting (#1) will still indicate that all matches are visible. 

This is especially troublesome with Edit Word (#18): if you resize the window so the match with the caret moves off screen and press Ctrl+Tab, you'll see the document is scrolled and the tooltip (`Editing %d occurrences`) appears around that match (off-screen) and yet it won't be made part of the edit region.

![sc](https://github.com/ProgerXP/Notepad2e/assets/1643195/c1596ca0-837d-4ed2-9bba-d4f61eb304a1)

**Comment by cshnik** [comment]
Fixed.
Edit mode get disabled (if active), pending changes are automatically applied.
