### ISSUE TITLE
Implement Notepad's right click behavior

### ISSUE THREAD

**Issue by DerpMcDerp** [ProgerXP/Notepad2e#54]
1. when you right click somewhere, Notepad2e shouldn't move the caret there.
2. when you right click outside of selected text, Notepad2e shouldn't deselect the text.

**Comment by ProgerXP** [comment]
I use right click to reposition the caret all the time. The best thing we can do is make a setting that will be off by default. @hacc how hard it looks to implement these 2?

**Comment by ProgerXP** [comment]
@cshnik How complex is to implement these 2?

If a matter of an hour or so, let's add an INI setting `MoveCaretOnRightClick` (0/1) and a checkbox menu item called `Move Caret On Right Click` below `Settings | Esc Key Function`. As @DerpMcDerp said, if it's disabled (default is enabled) right click will preserve selection and caret position and will only display the context menu.

**Comment by ProgerXP** [comment]
Wait, why some Notepad2e settings are inside `[Section]`, not `[Notepad2e]`? Review INI sections of new settings again.

Additionally, some settings are not effective if .ini is changed and Settings | Reload From Disk is used.

@DerpMcDerp This feature was implemented. Download EXE from here (https://github.com/ProgerXP/Notepad2e/blob/dev/bin/Win32/Release/Notepad2e.exe), open/close the program, open .ini, search for `MoveCaretOnRightClick` and set it to 0.
