### ISSUE TITLE
Adjust codying style of the files changed back to the original one

### ISSUE THREAD

**Issue by victorimnetz** [ProgerXP/Notepad2e#55]
The Notepad2e base line has a certain coding style; the files which were updated in course of Notepad2e development are not in line with the original coding style; those files are to be reformatted.

Here is the file list:

1. Dialogs.c/h
2. Edit.c/h
3. Helpers.c/h
4. Notepad2.c/h
5. resource.h
6. Styles.c/h
7. version.h

That doesn't include namings update like e.g. changing HL_xxx into author's style.

**Comment by victorimnetz** [comment]
Findings:
1. The original baseline of the Notepad2e, notepad2_4.2.25, doesn't have a consistent code formatting;
I've studied what the code style is and adjusted the corresponding settings of the VS2015 (Tools->Options->TextEditor->C/C++->Formatting); then I've applied them to the original Edit.c of the notepad2_4.2.25 and found 414 diffs; I've checked them and found that the edit.c is not consistent in terms of code style;
2. Assuming that code formatting must be automated and be easily done, re-formatting just changes between Notepad2e v1.0 and notepad2_4.2.25 is not the option;
3. My view is that we have to reformat all the src code now using the code style of the original notepad2_4.2.25 and then stick to this style

**Comment by ProgerXP** [comment]
> 3. My view is that we have to reformat all the src code now using the code style of the original notepad2_4.2.25 and then stick to this style 

I agree. Current formatting rules are good enough, as close as we can get.

Two questions:
1. Why did you chose not to insert spaces in function definition argument list? Is it more common? From edit.c I this style appears to be used as often as another, and if that's the case it's cleaner if we insert spaces instead of removing them.
2. Is it possible to obtain a unified diff on all files so that I can see edits made in Notepad2e as opposed to Notepad2 version it's based on, discarding all formatting differences?

**Comment by victorimnetz** [comment]
> 1. Why did you chose not to insert spaces in function definition argument list? Is it more common? From edit.c I this style appears to be used as often as another, and if that's the case it's cleaner if we insert spaces instead of removing them.
Yes, I had an impression it is more common. I would go for spaces as well.

>2. Is it possible to obtain a unified diff on all files so that I can see edits made in Notepad2e as opposed to Notepad2 version it's based on, discarding all formatting differences?
Yes, it is. Will do that.

**Comment by victorimnetz** [comment]
Done, pull request is ready for inspection: #57
