### ISSUE TITLE
Find dialog not refreshing buttons

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#59]
Recent addition of regexp checking doesn't listen for paste (either via context menu or with Ctrl+V).

1. Ctrl+F or H
2. Paste any text into Search String 
3. Buttons are disabled (wrong)

**Comment by cshnik** [comment]
[Done.](https://github.com/ProgerXP/Notepad2e/commit/304da9acc1e875861d60fabacc579ad833cf0f3e)

**Comment by ProgerXP** [comment]
Don't close issues, instead commit the exe and assign the issue to me (**Assignees** on the right) so I can check and  close it.

Also no need to post commit link - github automatically adds it if you are using #nnn.
