### ISSUE TITLE
Rename menu items

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#60]
* File | Open Previous (Alt+G) -> Recall Previous
* File | Launch | Open With (capitalize)
* File | Launch | Shell Menu (capitalize)
* Edit | Undo+Redo -> Go To Last Change
* Edit | Goto -> Go To
* Edit | Block | Unwrap Bracke**t**s At Cursor (typo, "t" missing)
* Edit | Convert | Lower Case (add space/capitalize)
* Edit | Convert | Upper Case (add space/capitalize)
* Settings | Highlight Current Word (capitalize) and move under View | Highlight Current Line
* Settings | Ctrl+Wheel Scroll (capitalize) and move under Settings | Esc Key
* Settings | Reload from disk -> Settings | Reload Settings From Disk
* Settings | Replace settings in all instances -> Settings | Replace Settings In Other Instances

**Comment by ProgerXP** [comment]
More:
* In Replace dialog (Ctrl+H) rename `Replace with` -> `Replace With` (capitalize)

**Comment by ProgerXP** [comment]
Not done:

> * In Replace dialog (Ctrl+H) rename `Replace with` -> `Replace With` (capitalize)
> * Title of the Ctrl+G dialog to `Go To` 

Did you find any other "goto"s?
> * **Search for other occurrences of "goto" string (without space)**

**Comment by ProgerXP** [comment]
New:
- Remove `ml` extension from `C/C++` because it's present in the new scheme `OCaml`.

**Comment by cshnik** [comment]
> In Replace dialog (Ctrl+H) rename Replace with -> Replace With (capitalize)

Already implemented:
![replace_with](https://cloud.githubusercontent.com/assets/8019354/20461681/e806d076-af37-11e6-8820-2bc457e4a358.png)
> Remove ml extension from C/C++ because it's present in the new scheme OCaml.

Where should I find it?
![c_extensions](https://cloud.githubusercontent.com/assets/8019354/20461682/eaff00fa-af37-11e6-97f0-d67bee8655de.png)

**Comment by ProgerXP** [comment]
>>In Replace dialog (Ctrl+H) rename Replace with -> Replace With (capitalize)
>Already implemented:

This is what I see (XP), in last and previous builds:
http://i.imgur.com/ZBG6znN.png

> I can't find ml extension in the C/C++ scheme:

It was my custom setting, it seems.

**Comment by cshnik** [comment]
> This is what I see (XP), in last and previous builds:
> http://i.imgur.com/ZBG6znN.png

Fixed.

**Comment by ProgerXP** [comment]
What was the cause, why it worked on your system?

**Comment by ProgerXP** [comment]
One more thing:

- Remove "Settings" from two last items in the Settings menu (Reload ~~Settings~~... and Replace ~~Settings~~...).
