### ISSUE TITLE
Always treat Shift+Tab as unindent

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#61]
Currently unindent only happens if cursor is after spaces/tabs at line start. Need to remove check for the cursor position (and not change its position after unindenting). Don't do anything if can't unindent (no spaces/tabs).

Example:
```
document
  lin|e2
```
Current behaviour after Shift+Tab:
```
document
  l|ine2
```
Required:
```
document
lin|e2
```

If there is not enough spaces/tabs (i.e. <> indent size) they are still removed.

**Comment by ProgerXP** [comment]
It turns out Shift+Tab is mapped to Edit | Block | Unindent but it isn't exactly the same. If you use the menu item indentation will be removed regardless of the caret position. This is what we need for Shift+Tab too - make it identical to this menu item.

**Comment by cshnik** [comment]
Shift+Tab hotkey was not properly assigned for the menu item and was actually processed by Scintilla's internals. This caused the specified problem with dual behavior of "Unindent"-functionality.

There is a similar issue with "Indent"-functionality (Edit | Block | Indent): it looks like it has a Tab hotkey assigned while actually it is not. Probably, we need to assign new hotkey, e.g. Ctrl+Tab but it is already assigned for "Edit Selection"(Edit | Edit Selection).

**Comment by ProgerXP** [comment]
Tab works fine even though it's handled by Sci, not that menu item. 

Do you mean that we can't use Shift+Tab for Edit | Block | Indent at all?

**Comment by cshnik** [comment]
Now "Unindent"-function has properly assigned hotkey \<Shift+Tab\> and it works the same in both cases: when using menu item or hotkey itself.
While "Indent"-function has no assigned hotkey. Displayed \<Tab\> is wrong. We need to assign another hotkey to provide a smooth way to call these similar functions by their hotkeys.
![indent_hotkey](https://cloud.githubusercontent.com/assets/8019354/20282457/4f23bae4-aae7-11e6-8fc9-300338c3997a.png)

**Comment by ProgerXP** [comment]
I understand now.

So you fixed Unindent/Shift+Tab, it works like I want.

About Indent/Tab. I understand what you mean - current menu item behaviour is different than pressing just Tab. Tab inserts either \t or spaces according to cursor column. But it's expected even if there's a slight discrepancy between the actions. Current Tab behaviour is very useful to align lines.

So this is done.

**Comment by ProgerXP** [comment]
This is **not** implemented the in last build?!

**Comment by cshnik** [comment]
> This is **not** implemented the in last build?!

Recent [rollback for the Shift+Tab hotkey](https://github.com/ProgerXP/Notepad2e/commit/dad08f5362e5a6dc458271c7542aa7c9f4c8221a) has switched back Notepad2e to original internal Scintilla's Shift+Tab handler and this caused the issue to reappear.
Now required changes were implemented directly in the Scintilla's [source code](https://github.com/ProgerXP/Notepad2e/commit/4aad69e7c53cfc2b18f43d502f9e70dae437805e).

To validate the fix please make sure next option is ON:
Settings> Tab Settings> Tab key reformats indention
