### ISSUE TITLE
Features questions

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#62]
1. How does Sort (Alt+O) | Column Sort work? It's always disabled for me.
2. What's the difference between **Justify (paragraph mode)** and just **Justify** в Align Lines (Alt+J)?

**Comment by cshnik** [comment]
1. Select lines> Alt+O> "Sort Lines"-dialog will popup
2. "Justify (paragraph mode)" works the same as regular "Justify"-option with the only difference : it will skip justifications for the last paragraph's line in all selected paragraphs.

**Comment by ProgerXP** [comment]
> Select lines> Alt+O> "Sort Lines"-dialog will popup

I know it will pop up, I mean when it will be available for checking? For me this checkbox (`Column sort (rectangular selection)`) is always disabled (grayed). Other checkboxes and radios in that dialog are normal.

> Justify (paragraph mode)"

Understood. Rename to: 
```
Justify (skip last line in paragraph)
```

**Comment by cshnik** [comment]
>> Select lines> Alt+O> "Sort Lines"-dialog will popup

>I know it will pop up, I mean when it will be available for checking? For me this checkbox (`Column sort (rectangular selection)`) is always disabled (grayed). Other checkboxes and radios in that dialog are normal.

Special "rectangular" text selection mode should be selected to make "Column sort" checkbox enabled.
But there are no calls for switching selection mode in the Notepad2/Notepad2e source code. Probably, there is a Scintilla's internal logic for selection mode switching.
