### ISSUE TITLE
Ctrl+CapsLock

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#64]
Is it possible to turn off CapsLock after this hotkey (used for `Edit word on the same line`)?

**Comment by cshnik** [comment]
I made few tests for switching back of CapsLock toggle's state after the moment the Ctrl+CapsLock hotkey handler was called and found this code unusable. In my tests this switching is not reliable and for some reason depends on different factors (the speed of keypress, the moment when Ctrl-key is released, etc).
At this point I see no way how to make CapsLock act as a regular key (to skip switching of CapsLock toggle) when Ctrl+CapsLock is pressed.

**Comment by ProgerXP** [comment]
I will think about a different hotkey.

**Comment by ProgerXP** [comment]
Let's assign Ctrl+Alt+Tab to Edit | Edit Selection On Line.

**Comment by cshnik** [comment]
> Let's assign Ctrl+Alt+Tab to Edit | Edit Selection On Line.

Ctrl+Alt+Tab is a global hotkey and it can't be normally assigned to a command.

**Comment by ProgerXP** [comment]
> Ctrl+Alt+Tab is a global hotkey and it can't be normally assigned to a command.

Then Ctrl+backtick (U+0060).

**Comment by cshnik** [comment]
Done.
