### ISSUE TITLE
New Line Below disabled by Auto Indent

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#67]
New Line commands should insert new line regardless of Auto Indent, only new indent depends on that setting. Right now if Auto Indent is disabled - Line Below works as regular Enter.

```
var obj = {
  str: ‘concat’ + 
       ‘and c|at’ +
       ‘till cut’
}
```
Caret anywhere on line 3, AI disabled, Ctrl+Shift+Enter:
```
var obj = {
  str: ‘concat’ + 
       ‘and c
|at’ +
       ‘till cut’
}
```
Expected (AI off):
```
var obj = {
  str: ‘concat’ + 
       ‘and cat’ +
|
       ‘till cut’
}
```
Expected (AI on, currently works):
```
var obj = {
  str: ‘concat’ + 
       ‘and cat’ +
       |
       ‘till cut’
}
```

**Comment by cshnik** [comment]
Fixed behavior for "New Line Below"-command when Auto Indent setting is OFF.
