### ISSUE TITLE
Unused settings

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#69]
Where these are used (from .ini)?
- SelectionScrollTimeout
- ActiveSelectionForeground
- ActiveSelectionBackground

**Comment by cshnik** [comment]
SelectionScrollTimeout - loaded from ini, saved to ini, NOT used
ActiveSelectionForeground - NOT loaded from ini, NOT saved to ini, NOT used
ActiveSelectionBackground - NOT loaded from ini, NOT saved to ini, NOT used

**Comment by ProgerXP** [comment]
Remove all of them.
