### ISSUE TITLE
Removing line breaks from Find

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#70]
How did you implement this? I can't find the email where you described it.

Was it implemented for Search String only or for Replace with too? 
Are you removing just CR LF or all symbols <0x20?

**Comment by cshnik** [comment]
CR/LF removed only. Implemented for Find/Replace-dialogs. [Commit](https://github.com/ProgerXP/Notepad2e/commit/dfa4a45b074f936b2df38dc2f2a63bb55ea5a295#diff-48a5a85854c59e2f93f4a0461c37c16d).

**Comment by ProgerXP** [comment]
1. Even though I can't test it because there's no exe, I'm sure adjustNewLines shouldn't be set for Edit | Swap.
2. What did that old HL_find_overrride winproc do?
3. Didn't know about `^c` in `Replace with`...

**Comment by cshnik** [comment]
> 1. Even though I can't test it because there's no exe, I'm sure adjustNewLines shouldn't be set for Edit | Swap.


Edit|Swap-command handler's logic was not changed during this checkin. And now it works absolutely the same as before. Please clarify the case you want to ~~fix~~ change.

> 2. What did that old HL_find_overrride winproc do?

This commented code implemented key filtering for "search string"-edit in find/replace dialogs. The filter prevents dialog closing when pressing ESC and ENTER keys.

> 3. Didn't know about ^c in Replace with...

^c is an alias for clipboard value.

**Comment by ProgerXP** [comment]
> Edit|Swap-command handler's logic was not changed during this checkin. And now it works absolutely the same as before. Please clarify the case you want to fix change.

I am talking about this line:
https://github.com/ProgerXP/Notepad2e/commit/dfa4a45b074f936b2df38dc2f2a63bb55ea5a295#diff-48bae158fb0090d9775d5d9523aa0ce2L2713

```C

     case IDM_EDIT_SWAP:
       if (SendMessage(hwndEdit, SCI_GETSELECTIONEND, 0, 0) -
           SendMessage(hwndEdit, SCI_GETSELECTIONSTART, 0, 0) == 0)
       {
         int iNewPos = -1;
         int iPos = (int)SendMessage(hwndEdit, SCI_GETCURRENTPOS, 0, 0);
         SendMessage(hwndEdit, SCI_PASTE, 0, 0);
         iNewPos = (int)SendMessage(hwndEdit, SCI_GETCURRENTPOS, 0, 0);
         SendMessage(hwndEdit, SCI_SETSEL, iPos, iNewPos);
         SendMessage(hwnd, WM_COMMAND, MAKELONG(IDM_EDIT_CLEARCLIPBOARD, 1), 0);
       }
       else
       {
         int iPos = (int)SendMessage(hwndEdit, SCI_GETCURRENTPOS, 0, 0);
         int iAnchor = (int)SendMessage(hwndEdit, SCI_GETANCHOR, 0, 0);
-        char *pClip = EditGetClipboardText(hwndEdit);
+        char *pClip = EditGetClipboardText(hwndEdit, TRUE);
         if (flagPasteBoard)
         {
           bLastCopyFromMe = TRUE;
```

```C

-char *EditGetClipboardText(HWND hwnd)
+char *EditGetClipboardText(HWND hwnd, BOOL adjustNewLines)
```

Does it mean you remove newlines on Edit | Swap?

**Comment by cshnik** [comment]
> Does it mean you remove newlines on Edit | Swap?

No. EditGetClipboardText()-call with adjustNewLines argument set to TRUE will return the text from the clipboard with converted newline characters considering the currently used Line-Endings mode (CRLF/LF/CR).
And that's how Edit | Swap always worked because previous version of EditGetClipboardText() always did such adjustment when extracting clipboard's text.

**Comment by ProgerXP** [comment]
That's right, I was inattentive.
