### ISSUE TITLE
Line Below and empty line

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#73]
Try this:
```
  lala
  lala|

  lala
```

Press Ctrl+Enter (AI enabled):
```
  lala
  lala
|

  lala
```
Okay, now Ctrl+Shift+Enter (Line Below):
Press Ctrl+Enter (AI enabled):
```
  lala
  lala

|

  lala
```

It seems that the caret is at line start. However, in reality it has two spaces:
```
|__
```
Why the caret is not set after those spaces?

**Comment by cshnik** [comment]
It looks like changes related to #68 fixed the issue.
