### ISSUE TITLE
Merge dev

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#74]
Merge dev into master and delete the branch. Report any conflicts, please.

**Comment by ProgerXP** [comment]
Any progress on this one?

When you have cleaned up code style, we talked about cleaning up unused code in general. But I still see huge blocks of commented code and `#ifdef 0`. Why it wasn't done?

What's up with Scintilla_ChangeLog.md? It's an unreadable mess of markup and raw text. Reformat it please.

**Comment by ProgerXP** [comment]
What is the status of this ticket?

**Comment by cshnik** [comment]
> What is the status of this ticket?

Pull request #83 was created for this task, Please check it for details.

**Comment by cshnik** [comment]
Should we proceed on this task?

**Comment by ProgerXP** [comment]
> Should we proceed on this task?

When all other issues are resolved.
