### ISSUE TITLE
"Open With..."-menu command causes application crash

### ISSUE THREAD

**Issue by cshnik** [ProgerXP/Notepad2e#75]
Select menu command: File>Launch>Open With  or press Alt+L hotkey

**Comment by ProgerXP** [comment]
Doesn't crash for me. When it happens?

**Comment by cshnik** [comment]
There are some calls to lstrcpyn() with NULL agrument provided. This causes an "access violation reading location 0x000000000"-exception which is visible in debugger only. The point here is that lstrcpyn hits an access violation then it catches it, and then returns, so that the application can keep going.
Please confirm if we need to fix these incorrect calls to lstrcpyn().

**Comment by ProgerXP** [comment]
> Please confirm if we need to fix these incorrect calls to lstrcpyn().

Yes, of course, working on null is a bad idea.
