### ISSUE TITLE
Regexp not recognized when encoding is UTF-8

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#78]
1. New document, contains Cyrillic letters.
2. Set encoding to UTF-8 (Shift+F8).
3. Ctrl+F, `\D`, regexp.
4. Result: nothing found. Expected: Cyrillic letter selected.

```
абцдеф
```

5. Switch to ANSI encoding.
6. Ctrl+F, `\D`, regexp.
7. Result is as expected.

**Comment by cshnik** [comment]
Currently used regexp implementation does not properly support unicode:
http://stackoverflow.com/questions/17103925/how-well-is-unicode-supported-in-c11

**Comment by ProgerXP** [comment]
I thought we used Scintilla's own regexp features. Does Sci use C++11 regexps?

**Comment by ProgerXP** [comment]
Notepad++ (https://notepad-plus-plus.org/) doesn't have this problem, apparently it uses some other regexp library. It's also open source. Can you check what it uses?

**Comment by cshnik** [comment]
> Notepad++ (https://notepad-plus-plus.org/) doesn't have this problem, apparently it uses some other regexp library. It's also open source. Can you check what it uses?

Notepad++ uses boost regex version.

**Comment by ProgerXP** [comment]
Boost is large. Can Sci's regexp library be replaced by another one? Or if we want to support both better regexp and modern Sci then we have to integrate C++11 and boost regexps?

Notepad++ must be also Scintilla-based, how they have solved this?

**Comment by cshnik** [comment]
> Can Sci's regexp library be replaced by another one?

Sure. We can embed any implementation of regex likewise Notepad++ did that with boost::regex.
> Or if we want to support both better regexp and modern Sci then we have to integrate C++11 and boost regexps?

There is no need to integrate C++11 since it is a part of VS2015 which is already used to build this project. Currently integrated version of Scintilla contains implementation of regex which is based on the C++11 version (this is how we solved the PCRE-upgrade task).
> Notepad++ must be also Scintilla-based, how they have solved this?

Scintilla offers base interface (RegexSearchBase) which should be used for embedding of custom regex-engine into the editor. Developer implements derived class (BoostRegexSearch in Notepad++) which will perform all required actions using specific regex-engine.

**Comment by ProgerXP** [comment]
How time consuming is to integrate boost RE?

**Comment by cshnik** [comment]
> How time consuming is to integrate boost RE?

This task may take up to 3 hours.

**Comment by ProgerXP** [comment]
Then you can do it.

**Comment by cshnik** [comment]
Done.

**Comment by ProgerXP** [comment]
@cshnik 
Which regexp implementation we ended up using right now? I got confused as we have changed it several times.

**Comment by cshnik** [comment]
> Which regexp implementation we ended up using right now? Boost? I got confused as we have changed it several times.

We use adopted boost regex implementation which originally came from Notepad++. There were no changes related to regex engine migration/switching.
![image](https://user-images.githubusercontent.com/8019354/37683363-f8851ede-2cbe-11e8-80b4-b49c772442e3.png)

**Comment by csware** [comment]
Is boost really required? Can't std::wregex be used or pcre? - Both look more easy to integrate to me.

**Comment by ProgerXP** [comment]
True, [Boost is large](https://github.com/ProgerXP/Notepad2e/issues/78#issuecomment-269021485). But Notepad2's regexp library has numerous issues, most of which are listed in the readme. Two main problems - lack of charset support and lack of even basic PCRE features like captures.

For charset, try Replace All `.` With `w` on a UTF-8 buffer containing Cyrillic (or other national) symbols such as `фцд` - result would be not `www` but `wwwww`, because Notepad2's regexps operate on bytes, not codepoints/symbols.

**Comment by csware** [comment]
Yeah, I see. This hinders the easy integrating Notepad2e as a submodule into TGit - as you have to bootstrap boost first.

**Comment by ProgerXP** [comment]
> This hinders the easy integrating Notepad2e as a submodule into TGit - as you have to bootstrap boost first.

Submodules can be nested, why not add Boost as another submodule? You will have to checkout Notepad2e's submodule anyway, can as well make it recursive.

> Can't std::wregex be used or pcre? - Both look more easy to integrate to me.

@cshnik Do you think these are more lightweight and will still work in our scenarios?

**Comment by csware** [comment]
std:wregexp would require double memory for a UTF-16 copy of the text-buffer.

**Comment by ProgerXP** [comment]
> With latest VS2017 I get the correct result?!

Yes, even on WinXP. ICU build allows to further expand regexp capabilities on national alphabets. #162
