### ISSUE TITLE
Search string changed to �

### ISSUE THREAD

**Issue by cshnik** [ProgerXP/Notepad2e#79]
1. Create new document
2. Set encoding to UTF-8 (Shift+F8).
3. Paste text: абцдеф, move cursor to line start
4. Ctrl+F, search string: \D, regexp is ON, press OK
5. press Ctrl+F

Result: Search string changed to �

**Comment by ProgerXP** [comment]
There were at least 3 encoding-related bugs so far. This is serious. Can you review the code related to encoding and search, how it works in both ASCII and Unicode modes?

**Comment by cshnik** [comment]
Unfortunately, I can't reproduce this bug anymore. I started again from #78-scenario and tried to find out the bug/scenario directly in the sources but my attempts were unsuccessful. It looks like specified steps to reproduce are incomplete and the actual problem appeared in the previous unknown scenario.

**Comment by cshnik** [comment]
> Can you review the code related to encoding and search, how it works in both ASCII and Unicode modes? 

Actually, this is a complex task and will take much time. To my mind, the best/effective way is to fix the issues if these reappear. Please confirm if we still need to proceed on code review.

**Comment by ProgerXP** [comment]
> Please confirm if we still need to proceed on code review.

Let's postpone this task.
