### ISSUE TITLE
INI sections

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#80]
From https://github.com/ProgerXP/Notepad2e/issues/54#issuecomment-264400313.

> Wait, why some Notepad2e settings are inside `[Section]`, not `[Notepad2e]`? Review INI sections of new settings again.

This is not fixed. 

1. Put Notepad2e.exe in an empty folder, run it.
2. Press F7, Notepad2e.ini is created. 
3. Open it:

```
[Settings]
HightLightSelection=1
WheelScroll=1
```

1. Why are these here, not in `[Notepad2e]`?
2. Rename `HightLightSelection` to `HighlightSelection` (~~t~~, `L` > `l`).
3. `HightLightSelection` controls current word highlighting, right? View | Highlight Current Word

**Comment by cshnik** [comment]
> 1. Why are these here, not in [Notepad2e]?

Fixed.

> 2. Rename HightLightSelection to HighlightSelection (t, L > l).

Fixed.

> 3. HightLightSelection controls current word highlighting, right? View | Highlight Current Word

Yes, you are right.

**Comment by ProgerXP** [comment]
Build?

**Comment by cshnik** [comment]
Test build is [here](https://github.com/ProgerXP/Notepad2e/blob/05eca2e2665afd56c28b7ee1f6132195fa891f94/bin/Win32/Release/Notepad2e.exe?raw=true).

VirusTotal showed new detection ratio as 3/55 o_O
While test debug build gave me 1/55.
