### ISSUE TITLE
Unindent and whitespace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#82]
After  #61 has been implemented and Shift+Tab working as Edit | Block | Unindent, I discovered that this command isn't the same as old Shift+Tab behaviour: when any line has no indentation, the command is cancelled instead of removing as much indentation as it can.

Need to correct Edit | Block | Unindent so that it works as former Shift+Tab, i.e. doesn't stop if a line has no indentation.

Given this document and indent size = 2 spaces:
```
a
 b
  c
   d
```

Old behaviour (wrong, nothing changed):
```
a
 b
  c
   d
```

New:
```
a
b
c
 d
```

**Comment by cshnik** [comment]
Fixed.
I rolled back the hotkey mistakenly added in #61.

**Comment by ProgerXP** [comment]
New problem:

```
a
| b
```

Shift+Tab:
```
a|
b
```
Not:
```
a
|b
```

**Comment by cshnik** [comment]
I was able to reproduce the issue using Edit>Block>Unindent-menu command (which is not the same as Shift+Tab hotkey).
The fix was committed as a part for currently closed #61.
