### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#84]
Hotkeys of most Edit | Special commands do nothing for me.

**Comment by cshnik** [comment]
There were 2 problems with hotkeys: 
1. Missing hotkey for "Hex To Char"-menu command (Ctrl+Alt+C) <b>Fixed</b>
1. "URL Decode" command's hotkey (Ctrl+Shift+R) is already in use for File> Launch> Shell Menu  <b>TODO</b>

<b>Please provide new hotkey(s) to resolve the issue 2.</b>

---
Here are some details on the commands behavior:

+ Line Comment (Ctrl+Q): comment selected lines with //
+ Stream Comment (Ctrl+Shift+Q): comment selected block with /**/
+ URL Encode	(Ctrl+Shift+E): encode selected text, e.g. http://google.com => http:%2F%2Fgoogle.com
+ URL Decode	(Ctrl+Shift+R): decode selected text, e.g. http:%2F%2Fgoogle.com => http://google.com
+ Escape C Chars (Ctrl+Alt+E): convert  \ => \\
+ Unescape C Chars (Ctrl+Alt+R): convert \\ => \
+ Strip HTML Tags (Shift+Alt+X): convert &lt;tag&gt;text&lt;/tag&gt; => text
+ Escape HTML Tags (Ctrl+Shift+Alt+X): convert &lt;tag&gt;text&lt;/tag&gt; => &amp;lt;tag&amp;gt;text&amp;lt;/tag&amp;gt;
+ Char To Hex	 (Ctrl+Alt+X): convert single selected char to hex-code, e.g. a => \x61
+ Hex to Char	(Ctrl+Alt+C):  convert \x61 => a
+ Find Matching Brace (Ctrl+B): go to matching brace, e.g. ()[]{}
+ Select to Matching Brace (Ctrl+Shift+B)
+ Select to Next (F2): select text, press Ctrl+F to copy text to search string, press Enter, &lt;F2&gt; will increase current selection to include next entry
+ Select to Previous (Shift+F2): select text, press Ctrl+F to copy text to search string, press Enter, &lt;Shift+F2&gt; will increase current selection to include previous entry

**Comment by cshnik** [comment]
@ProgerXP, one more thing. Actually, I found another reason when hotkeys do not properly work: my desktop launcher application installed some global hotkeys with the same key combinations as Notepad2e internally uses. Global hotkey overlays internal application's accelerator and this may prevent Notepad2e hotkeys to work properly. I had to disable launcher tool to test commands from this issue.

**Comment by ProgerXP** [comment]
> "URL Decode" command's hotkey (Ctrl+Shift+R) is already in use for File> Launch> Shell Menu 

Is Ctrl+Shift+L free? If yes then use it for URL Decode (keep Shell Menu as is).

> Global hotkey overlays internal application's accelerator and this may prevent Notepad2e hotkeys to work properly. I 

Yes, I know about this.

**Comment by cshnik** [comment]
> Is Ctrl+Shift+L free?

No. Ctrl+Shift+L is reserved for "View> Long Line Marker".

**Comment by ProgerXP** [comment]
Uhm... What are the free hotkeys right now (all modifiers: Ctrl/Alt/Shift and combinations)? Notepad2 has some undocumented features so can you generate this list from the source code? This will be useful for the README as well.

**Comment by cshnik** [comment]
Please check attached files:
[busy_hotkeys.txt](https://github.com/ProgerXP/Notepad2e/files/771719/busy.txt)
[free_hotkeys.txt](https://github.com/ProgerXP/Notepad2e/files/771720/free.txt)

**Comment by ProgerXP** [comment]
> "URL Decode" command's hotkey (Ctrl+Shift+R) is already in use for File> Launch> Shell Menu TODO

Let's use `Ctrl+Alt+Shift+E`.

**Comment by cshnik** [comment]
> What do these do?
* Ctrl+Shift+A: reload current file using default encoding (ANSI)
* Ctrl+Shift+F: recode current file using default encoding (ANSI)
* Ctrl+Shift+K: copy current window position parameter to clipboard, e.g. "/pos -921,361,919,661,0"
* Ctrl+Shift+O: reload current file using default OEM encoding
* Ctrl+Shift+P: move/resize window to default position
* F11: switch to default lexer/scheme
* Ctrl+F11: switch to HTML lexer/scheme
* Ctrl+Shift+F11: switch to XML lexer/scheme
* Shift+F5: replace "$Date:^$" with current date/time in current selection/file, e.g: $Date:^$ -> $Date: 2017/02/15 23:15:41 $
* Ctrl+,: move cursor to current selection start (scroll window up)
* Ctrl+.: move cursor to current selection end (scroll window down)
* Ctrl+Alt++: Zoom In
* Ctrl+Alt+-: Zoom Out

**Comment by cshnik** [comment]
> Let's use Ctrl+Alt+Shift+E.
Done.

**Comment by ProgerXP** [comment]
>Ctrl+Shift+P: move/resize window to default position

Where is this default position defined, in the ini? Or is it hardcoded?

**Comment by ProgerXP** [comment]
> Where is this default position defined, in the ini? Or is it hardcoded?

@cshnik Ping.
