### ISSUE TITLE
Losing changes on new line above/below

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#85]
If a document has no changes (no `*` in the title) and I do shift/alt+ctrl+enter this does not mark the document as changed **and all further changes never mark it so operations like ctrl+o, ctrl+n, etc. DO NOT BRING UP A PROMPT FOR SAVE**.

What have you done? Triple check and test the code!

**Comment by cshnik** [comment]
Fixed. Removed wrong call to Scintilla in EditInsertNewLine().

**Comment by ProgerXP** [comment]
How could this have been happened anyway? Breaking entire buffer modification with one command?
