### ISSUE TITLE
Language indication

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#86]
Add a new ini setting `TitleLanguage` with values:
- `0` - default; nothing, current behaviour
- `1` - add space, `[`, short language ID, `]` to the titlebar (`Untitled - Notepad 2e [EN]`)
- `2` - same as `1` but when system keyboard language is English, do not add it, else - add:
```
Untitled - Notepad 2e 
Untitled - Notepad 2e [RU]
Untitled - Notepad 2e [ES]
```

Of course, language indication must be updated when keyboard language is switched.

**Comment by cshnik** [comment]
Done. Language indicator submenu was added as a part of the fix:
![language_indicator_submenu](https://cloud.githubusercontent.com/assets/8019354/23033242/e71cfffc-f4a9-11e6-86d7-a039d2db42b3.png)
