### ISSUE TITLE
Char/Hex

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#87]
Currently there are 2 commands: Char To Hex and Hex To Hex.

1. Rename them to `Char To C Hex` and `C Hex To Char`.
2. Add 2 new commands below `C Hex To Char`: 1) `String To Hex` 2) `Hex To String`
3. Implement them in the same way as currently C Hex works except:
 * accept any number of characters, not only 1.
  * do not include `\x` prefix.
  * encode whitespace (<=0x20) as is; on decode ignore (i.e. space = `20` but on Hex->Char spaces are ignored).
  * after encode/decode select produced result.
  * without selection encode/decode entire document.
  * on decode keep line breaks as is, don't convert to document's format.
  * ~~on decode ignore (copy to result as is) wrong symbols: `61X62`=`aXb` and symbols without pair: `616`=`a6`.~~
  * on decode ignore char case, i.e. `2C`=`2c`.

For example:
```
abc
def
```
Gives:
```
6162630D0A646566
```

**Comment by cshnik** [comment]
I started my work on this and found some additional behavior of the "Char 2 Hex"-command which may affect this task. The point is:
1. ASCII characters encoded as \xNN, where NN - hex code
2. UNICODE characters encoded as \uNNNN, where NNNN - extended hex code

So how we should encode UNICODE characters?

**Comment by ProgerXP** [comment]
I see, so chat to hex is a more complex command than I thought.

What I need is to get the same binary output as if I have saved the file. I.e. multibyte characters encoded into the file's encoding (UTF-8, ANSI, other). Same when decoding - decode hex bytes according to the file's encoding, merging multiple bytes into one character.

If a decoding error occurs, then stop immediately, selecting only decoded text: `61X62` = `[a]X62`.

**Comment by ProgerXP** [comment]
When implemented, assign hotkeys Shift+Alt+A (to hex) Ctrl+Shift+Alt+A (from hex).

**Comment by cshnik** [comment]
Done.
Implemented functionality can be easily switched to support different modes (if required), e.g:
1. If a decoding error occurs, then stop immediately, selecting only decoded text: 61X62 = [a]X62.
2. on decode ignore (copy to result as is) wrong symbols: 61X62=aXb and symbols without pair: 616=a6.

**Comment by ProgerXP** [comment]
> If a decoding error occurs, then stop immediately, selecting only decoded text: 61X62 = [a]X62.

Currently you do this, right? If
