### ISSUE TITLE
MathEval INI setting

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#88]
Values:
- 0 - original Notepad2 behavior, don't eval selection; file size column in the status bar always reflects file size.
- 1 - current behavior, eval selection, replace file size column if the selection is a valid expression.
- 2 - new behavior: in addition to `1`, if there's no selection - try evaluating current line (with the caret) as if selection = from current line's start to end.

**Comment by cshnik** [comment]
Done.
Additional changes: added Settings submenu for fast switching:
Settings>
&nbsp;&nbsp;Evaluate Math Expressions>
&nbsp;&nbsp;&nbsp;&nbsp;Disabled
&nbsp;&nbsp;&nbsp;&nbsp;Current Selection
&nbsp;&nbsp;&nbsp;&nbsp;Current Line

**Comment by ProgerXP** [comment]
>  Additional changes: added Settings submenu for fast switching:

Yes, very convenient.

---

This is hilarious, VC++ recognized as a "virus":

```
Antivirus 	Result 	
Bkav 	[Microsoft Visual C++ 8] 
```
