### ISSUE TITLE
Feature (or hack) request: ctrl+arrow behavior toggle?

### ISSUE THREAD

**Issue by Zzooouhh** [ProgerXP/Notepad2e#89]
Notepad2 by default features ctrl+arrow left/right hotkeys for "word jumping", just like the original windows Notepad.exe (further referred to as just "Notepad"). However this functionality in Notepad2 is slightly different regarding whether it skips punctuation or not - try for example traversing the following text in both editors with the ctrl+right hotkey from start to end:

go,to.the.bathroom.
go, to. the. bathroom.
go ,to .the .bathroom .
go , to . the . bathroom .

When going through each line one by one, all four lines take 8 ctrl+right strokes to go through on Notepad2, because the jumps stop before and after each period and comma. However in Notepad, it's respectively 1, 4, 5 and 8 strokes for all lines, because the stops happen at the beginning of each word instead. The former behavior undeniably comes useful when editing code featuring a lot of punctuation, however for any other text I find the latter's behaviour preferable, **and thus I'd like to ask whether it's possible to implement a toggle between these two "modes" of ctrl+left/right.**

I've tried comparing it with Notepad++ (also based on Scintilla) and that one behaves the exact same as Notepad2, so I suspect that this might be related to a core setting of Scintilla and its two SCI_WORDLEFT and SCI_WORDRIGHT functions. **If a toggle is too much work to implement or it's possible to alter via a simple hack, I'd like to know at least some pointers on what needs to be altered within the source, so I can benefit from the behavior of Notepad within Notepad2.**

**Comment by ProgerXP** [comment]
>I've tried comparing it with Notepad++ (also based on Scintilla) and that one behaves the exact same as Notepad2

This behaviour is actually more common than Notepad's - Firefox for example does the same. I find it more convenient.

@cshnik There is probably some Scintilla setting with the list of stop symbols, right?

**Comment by cshnik** [comment]
> There is probably some Scintilla setting with the list of stop symbols, right?

No, there was no such an option in the Scintilla's engine.

Alternative Ctrl+Arrow navigation mode implemented. Corresponding setting and mode switch added:
![notepad2_ctrlarrow_setting](https://cloud.githubusercontent.com/assets/8019354/23581769/bf5189a6-014d-11e7-90bd-c8f46ed71f96.png)

**Comment by ProgerXP** [comment]
@Zzooouhh This seems to be implemented as per your description. Download the EXE from here:
https://github.com/ProgerXP/Notepad2e/blob/dev/bin/Win32/Release/Notepad2e.exe

**Comment by Zzooouhh** [comment]
This works pretty much perfectly! Thank you very much for this.

**Comment by ProgerXP** [comment]
Document:

```
a
 b (note the leading space)
```

Regular Ctrl+Right jumps from `a|` to `\n |b` while accelerated also jumps to `| b`. Need to remove this discrepancy (intermediate jump in accelerated mode).

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Another discrepancy:

```
a
b|
```

Regular Ctrl+Right motions: `|b`, `a|`, `|a`. But accelerated are different: `|b`, `|a` (no `a|`).

**Comment by cshnik** [comment]
Cannot reproduce.
Tested both Ctrl/Alt+Left/Right on the most recent build from master-branch.

**Comment by ProgerXP** [comment]
Strange. Present in de04487 but not in master.
