### ISSUE TITLE
Regexp: confine to single line

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#90]
After integrating boost regexp (#78), behaviour has changed: in the original Notepad2, regexp never spans multiple lines but not it does.

Document:
```
a;b
foo
c; d
```

Original behaviour on replace from = `\W.*` to = empty:
```
a
foo
c
```

Current behaviour:
```
a
```

This happens because in current implementation `*` takes all document from first `;` until EOF while in previous implementation the match never exceeded line break. Note that in C++11 regexp this worked as expected.

Is there some regexp flag you should set?

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
I don't like your solution, it's fragile and unreliable due to manual regexp parsing and Scintilla core changes. However, I have checked Notepad++ and it behaves the same (regexp is not confined to line boundary). Looks like this was the advantage of the old Notepad2 regexp implementation.

Just to make sure, are you sure there is no flag we can just set on the regexp object to behave as I've described, without modifying the libraries' code?

**Comment by cshnik** [comment]
> I don't like your solution, it's fragile and unreliable due to manual regexp parsing and Scintilla core changes. However, I have checked Notepad++ and it behaves the same (regexp is not confined to line boundary). Looks like this was the advantage of the old Notepad2 regexp implementation.

I made an additional research and found the proper way to fix BoostRegex-implementation.

> Just to make sure, are you sure there is no flag we can just set on the regexp object to behave as I've described, without modifying the libraries' code?

There were no actual changes in the libraries code. Here are some points:
1. Moving of the RESearchRange class to header file was required to make it possible to use it outside of the Scintilla's Editor.cxx module. There were no other changes related to Scintilla's internals.
2. RESearchRange class was originally used for both "internal regex" and "Cxx11 regex" find implementations to make it possible to search in a set of lines (not a plain text with line feed characters).
3. I made a rollback for previous fix to get rid of manual regexp checks, made some optimizations in the "boost regex" and remade it to work in very the same way as "Cxx11 regex".

Fixed. Please retest new implementation.

**Comment by ProgerXP** [comment]
There are still changes in boost but it seems to work so let's keep it for now.
