### ISSUE TITLE
Shift+Tab unindent and whitespace

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#91]
Improper operation when caret is located on the indentation (whitespace between line start and the caret).

Given this document:
```
    |foo
```
Actual behaviour:
```
|  foo
```
Expected:
```
  |foo
```

Similarly when a line contains just whitespace, e.g.:
```
    |
```

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Something is broken: now cursor is shifted to the start of the line instead of staying where it was (this worked before your fix).

```
    foo|
```
becomes
```
  |foo
```

**Comment by cshnik** [comment]
Fixed. Additional testing was performed on the previously mentioned test-cases specified in the other Shift-Tab related issues.
