### ISSUE TITLE
New line commands must stop selection editing

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#93]
Document: `aa |aa`. Press Ctrl+Tab. Both `aa` are outlined. Press one of the new line command hotkeys (like Ctrl+Shift) - document changes and editing mode is kept.

Proper behaviour: treat new line commands as regular Enter command, i.e. commit changes and turn off editing mode.

**Comment by cshnik** [comment]
Fixed.

**Comment by ProgerXP** [comment]
Reread please:

> Proper behaviour: treat new line commands **as regular Enter command**, i.e. commit changes and turn off editing mode.

**Comment by cshnik** [comment]
Can you describe in details the problem with current fix?

**Comment by ProgerXP** [comment]
It doesn't only end the edit mode but it inserts the new line. Compare this with Enter behaviour that ends the mode but doesn't insert any new line.

**Comment by cshnik** [comment]
Fixed.
