### ISSUE TITLE
Toolbar icons

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#95]
1. Need to replace Replace command's icon.
2. Need to add a button to control Settings > Save Settings On Exit.

Toolbar.bmp with new icons:
![](http://i.imgur.com/yGaMRxI.png)

**Comment by cshnik** [comment]
Done.
Additional cleanup was made for some other toolbar icons:
![notepad2_toolbarcleanup](https://cloud.githubusercontent.com/assets/8019354/23563250/755a6514-0078-11e7-87b8-9730ce0bbfef.png)
