### ISSUE TITLE
Controlling Save Settings On Exit

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#96]
I am trying to make Notepad 2e have this flag (Settings | Save Settings On Exit) unchecked on launch. For this I tried doing:

1. Unsetting it and pressing F7 to save the ini.
2. Setting SaveSettings=0 in the ini.

Nothing worked, this flag is still always checked. Can you reproduce it?

**Comment by cshnik** [comment]
You were right: there was a bug (introduced back in 2015) related to loading of SaveSetting option from INI-file. Fixed.

**Comment by ProgerXP** [comment]
Now we are fixing things.
