### ISSUE TITLE
HL cleanup

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#98]
In the code there are currently a lot of functions and variables from the previous 2e developer ("hl", "HL"). They need to be reorganized and/or renamed to use a prefix like "n2e_", plus your own changes in the codebase must be moved out of the original source files (both Notepad's and libraries') as much as possible.

This is part of my effort to keep close to the original code of Notepad2 (and minimize changes inside Scintilla/boost).

**Comment by ProgerXP** [comment]
What about this? Still not finished?

**Comment by cshnik** [comment]
In progress. There is a lot of thing to do here.

**Comment by cshnik** [comment]
Done.
