### ISSUE TITLE
Reuse Window not respecting Save Settings On Exit

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#99]
1. Disable Save Settings On Exit.
2. Toggle Reuse Window.
3. Exit Notepad2e.
4. Run Notepad2e.

You will notice that the new instance has Reuse Window set to the new value, not old value. Why new value is saved even if Save Settings On Exit is disabled? Is this intended Notepad2 behaviour or a bug?

Are there any other settings that don't respect this setting?

**Comment by cshnik** [comment]
These options are instantly saved to the INI file after they changed:  
* Settings> Sticky Window Position  
* Settings> Reuse Window  
* Settings> Single File Instance  
  
This is a legacy behaviour which came from Notepad2.
